// Code generated by ent, DO NOT EDIT.

package tlsfingerprintcapturesession

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldEQ(FieldUpdatedAt, v))
}

// TaskID applies equality check predicate on the "task_id" field. It's identical to TaskIDEQ.
func TaskID(v int64) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldEQ(FieldTaskID, v))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldEQ(FieldSessionID, v))
}

// ClientIP applies equality check predicate on the "client_ip" field. It's identical to ClientIPEQ.
func ClientIP(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldEQ(FieldClientIP, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldEQ(FieldPlatform, v))
}

// UserAgent applies equality check predicate on the "user_agent" field. It's identical to UserAgentEQ.
func UserAgent(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldEQ(FieldUserAgent, v))
}

// Originator applies equality check predicate on the "originator" field. It's identical to OriginatorEQ.
func Originator(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldEQ(FieldOriginator, v))
}

// AlpnNegotiated applies equality check predicate on the "alpn_negotiated" field. It's identical to AlpnNegotiatedEQ.
func AlpnNegotiated(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldEQ(FieldAlpnNegotiated, v))
}

// RawClientHello applies equality check predicate on the "raw_client_hello" field. It's identical to RawClientHelloEQ.
func RawClientHello(v []byte) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldEQ(FieldRawClientHello, v))
}

// SessionStatus applies equality check predicate on the "session_status" field. It's identical to SessionStatusEQ.
func SessionStatus(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldEQ(FieldSessionStatus, v))
}

// ErrorSummary applies equality check predicate on the "error_summary" field. It's identical to ErrorSummaryEQ.
func ErrorSummary(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldEQ(FieldErrorSummary, v))
}

// OpenedAt applies equality check predicate on the "opened_at" field. It's identical to OpenedAtEQ.
func OpenedAt(v time.Time) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldEQ(FieldOpenedAt, v))
}

// ClosedAt applies equality check predicate on the "closed_at" field. It's identical to ClosedAtEQ.
func ClosedAt(v time.Time) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldEQ(FieldClosedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldLTE(FieldUpdatedAt, v))
}

// TaskIDEQ applies the EQ predicate on the "task_id" field.
func TaskIDEQ(v int64) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldEQ(FieldTaskID, v))
}

// TaskIDNEQ applies the NEQ predicate on the "task_id" field.
func TaskIDNEQ(v int64) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldNEQ(FieldTaskID, v))
}

// TaskIDIn applies the In predicate on the "task_id" field.
func TaskIDIn(vs ...int64) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldIn(FieldTaskID, vs...))
}

// TaskIDNotIn applies the NotIn predicate on the "task_id" field.
func TaskIDNotIn(vs ...int64) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldNotIn(FieldTaskID, vs...))
}

// TaskIDGT applies the GT predicate on the "task_id" field.
func TaskIDGT(v int64) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldGT(FieldTaskID, v))
}

// TaskIDGTE applies the GTE predicate on the "task_id" field.
func TaskIDGTE(v int64) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldGTE(FieldTaskID, v))
}

// TaskIDLT applies the LT predicate on the "task_id" field.
func TaskIDLT(v int64) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldLT(FieldTaskID, v))
}

// TaskIDLTE applies the LTE predicate on the "task_id" field.
func TaskIDLTE(v int64) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldLTE(FieldTaskID, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldContainsFold(FieldSessionID, v))
}

// ClientIPEQ applies the EQ predicate on the "client_ip" field.
func ClientIPEQ(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldEQ(FieldClientIP, v))
}

// ClientIPNEQ applies the NEQ predicate on the "client_ip" field.
func ClientIPNEQ(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldNEQ(FieldClientIP, v))
}

// ClientIPIn applies the In predicate on the "client_ip" field.
func ClientIPIn(vs ...string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldIn(FieldClientIP, vs...))
}

// ClientIPNotIn applies the NotIn predicate on the "client_ip" field.
func ClientIPNotIn(vs ...string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldNotIn(FieldClientIP, vs...))
}

// ClientIPGT applies the GT predicate on the "client_ip" field.
func ClientIPGT(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldGT(FieldClientIP, v))
}

// ClientIPGTE applies the GTE predicate on the "client_ip" field.
func ClientIPGTE(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldGTE(FieldClientIP, v))
}

// ClientIPLT applies the LT predicate on the "client_ip" field.
func ClientIPLT(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldLT(FieldClientIP, v))
}

// ClientIPLTE applies the LTE predicate on the "client_ip" field.
func ClientIPLTE(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldLTE(FieldClientIP, v))
}

// ClientIPContains applies the Contains predicate on the "client_ip" field.
func ClientIPContains(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldContains(FieldClientIP, v))
}

// ClientIPHasPrefix applies the HasPrefix predicate on the "client_ip" field.
func ClientIPHasPrefix(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldHasPrefix(FieldClientIP, v))
}

// ClientIPHasSuffix applies the HasSuffix predicate on the "client_ip" field.
func ClientIPHasSuffix(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldHasSuffix(FieldClientIP, v))
}

// ClientIPEqualFold applies the EqualFold predicate on the "client_ip" field.
func ClientIPEqualFold(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldEqualFold(FieldClientIP, v))
}

// ClientIPContainsFold applies the ContainsFold predicate on the "client_ip" field.
func ClientIPContainsFold(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldContainsFold(FieldClientIP, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldContainsFold(FieldPlatform, v))
}

// UserAgentEQ applies the EQ predicate on the "user_agent" field.
func UserAgentEQ(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldEQ(FieldUserAgent, v))
}

// UserAgentNEQ applies the NEQ predicate on the "user_agent" field.
func UserAgentNEQ(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldNEQ(FieldUserAgent, v))
}

// UserAgentIn applies the In predicate on the "user_agent" field.
func UserAgentIn(vs ...string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldIn(FieldUserAgent, vs...))
}

// UserAgentNotIn applies the NotIn predicate on the "user_agent" field.
func UserAgentNotIn(vs ...string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldNotIn(FieldUserAgent, vs...))
}

// UserAgentGT applies the GT predicate on the "user_agent" field.
func UserAgentGT(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldGT(FieldUserAgent, v))
}

// UserAgentGTE applies the GTE predicate on the "user_agent" field.
func UserAgentGTE(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldGTE(FieldUserAgent, v))
}

// UserAgentLT applies the LT predicate on the "user_agent" field.
func UserAgentLT(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldLT(FieldUserAgent, v))
}

// UserAgentLTE applies the LTE predicate on the "user_agent" field.
func UserAgentLTE(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldLTE(FieldUserAgent, v))
}

// UserAgentContains applies the Contains predicate on the "user_agent" field.
func UserAgentContains(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldContains(FieldUserAgent, v))
}

// UserAgentHasPrefix applies the HasPrefix predicate on the "user_agent" field.
func UserAgentHasPrefix(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldHasPrefix(FieldUserAgent, v))
}

// UserAgentHasSuffix applies the HasSuffix predicate on the "user_agent" field.
func UserAgentHasSuffix(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldHasSuffix(FieldUserAgent, v))
}

// UserAgentEqualFold applies the EqualFold predicate on the "user_agent" field.
func UserAgentEqualFold(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldEqualFold(FieldUserAgent, v))
}

// UserAgentContainsFold applies the ContainsFold predicate on the "user_agent" field.
func UserAgentContainsFold(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldContainsFold(FieldUserAgent, v))
}

// OriginatorEQ applies the EQ predicate on the "originator" field.
func OriginatorEQ(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldEQ(FieldOriginator, v))
}

// OriginatorNEQ applies the NEQ predicate on the "originator" field.
func OriginatorNEQ(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldNEQ(FieldOriginator, v))
}

// OriginatorIn applies the In predicate on the "originator" field.
func OriginatorIn(vs ...string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldIn(FieldOriginator, vs...))
}

// OriginatorNotIn applies the NotIn predicate on the "originator" field.
func OriginatorNotIn(vs ...string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldNotIn(FieldOriginator, vs...))
}

// OriginatorGT applies the GT predicate on the "originator" field.
func OriginatorGT(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldGT(FieldOriginator, v))
}

// OriginatorGTE applies the GTE predicate on the "originator" field.
func OriginatorGTE(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldGTE(FieldOriginator, v))
}

// OriginatorLT applies the LT predicate on the "originator" field.
func OriginatorLT(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldLT(FieldOriginator, v))
}

// OriginatorLTE applies the LTE predicate on the "originator" field.
func OriginatorLTE(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldLTE(FieldOriginator, v))
}

// OriginatorContains applies the Contains predicate on the "originator" field.
func OriginatorContains(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldContains(FieldOriginator, v))
}

// OriginatorHasPrefix applies the HasPrefix predicate on the "originator" field.
func OriginatorHasPrefix(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldHasPrefix(FieldOriginator, v))
}

// OriginatorHasSuffix applies the HasSuffix predicate on the "originator" field.
func OriginatorHasSuffix(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldHasSuffix(FieldOriginator, v))
}

// OriginatorEqualFold applies the EqualFold predicate on the "originator" field.
func OriginatorEqualFold(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldEqualFold(FieldOriginator, v))
}

// OriginatorContainsFold applies the ContainsFold predicate on the "originator" field.
func OriginatorContainsFold(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldContainsFold(FieldOriginator, v))
}

// AlpnNegotiatedEQ applies the EQ predicate on the "alpn_negotiated" field.
func AlpnNegotiatedEQ(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldEQ(FieldAlpnNegotiated, v))
}

// AlpnNegotiatedNEQ applies the NEQ predicate on the "alpn_negotiated" field.
func AlpnNegotiatedNEQ(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldNEQ(FieldAlpnNegotiated, v))
}

// AlpnNegotiatedIn applies the In predicate on the "alpn_negotiated" field.
func AlpnNegotiatedIn(vs ...string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldIn(FieldAlpnNegotiated, vs...))
}

// AlpnNegotiatedNotIn applies the NotIn predicate on the "alpn_negotiated" field.
func AlpnNegotiatedNotIn(vs ...string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldNotIn(FieldAlpnNegotiated, vs...))
}

// AlpnNegotiatedGT applies the GT predicate on the "alpn_negotiated" field.
func AlpnNegotiatedGT(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldGT(FieldAlpnNegotiated, v))
}

// AlpnNegotiatedGTE applies the GTE predicate on the "alpn_negotiated" field.
func AlpnNegotiatedGTE(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldGTE(FieldAlpnNegotiated, v))
}

// AlpnNegotiatedLT applies the LT predicate on the "alpn_negotiated" field.
func AlpnNegotiatedLT(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldLT(FieldAlpnNegotiated, v))
}

// AlpnNegotiatedLTE applies the LTE predicate on the "alpn_negotiated" field.
func AlpnNegotiatedLTE(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldLTE(FieldAlpnNegotiated, v))
}

// AlpnNegotiatedContains applies the Contains predicate on the "alpn_negotiated" field.
func AlpnNegotiatedContains(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldContains(FieldAlpnNegotiated, v))
}

// AlpnNegotiatedHasPrefix applies the HasPrefix predicate on the "alpn_negotiated" field.
func AlpnNegotiatedHasPrefix(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldHasPrefix(FieldAlpnNegotiated, v))
}

// AlpnNegotiatedHasSuffix applies the HasSuffix predicate on the "alpn_negotiated" field.
func AlpnNegotiatedHasSuffix(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldHasSuffix(FieldAlpnNegotiated, v))
}

// AlpnNegotiatedEqualFold applies the EqualFold predicate on the "alpn_negotiated" field.
func AlpnNegotiatedEqualFold(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldEqualFold(FieldAlpnNegotiated, v))
}

// AlpnNegotiatedContainsFold applies the ContainsFold predicate on the "alpn_negotiated" field.
func AlpnNegotiatedContainsFold(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldContainsFold(FieldAlpnNegotiated, v))
}

// RawClientHelloEQ applies the EQ predicate on the "raw_client_hello" field.
func RawClientHelloEQ(v []byte) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldEQ(FieldRawClientHello, v))
}

// RawClientHelloNEQ applies the NEQ predicate on the "raw_client_hello" field.
func RawClientHelloNEQ(v []byte) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldNEQ(FieldRawClientHello, v))
}

// RawClientHelloIn applies the In predicate on the "raw_client_hello" field.
func RawClientHelloIn(vs ...[]byte) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldIn(FieldRawClientHello, vs...))
}

// RawClientHelloNotIn applies the NotIn predicate on the "raw_client_hello" field.
func RawClientHelloNotIn(vs ...[]byte) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldNotIn(FieldRawClientHello, vs...))
}

// RawClientHelloGT applies the GT predicate on the "raw_client_hello" field.
func RawClientHelloGT(v []byte) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldGT(FieldRawClientHello, v))
}

// RawClientHelloGTE applies the GTE predicate on the "raw_client_hello" field.
func RawClientHelloGTE(v []byte) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldGTE(FieldRawClientHello, v))
}

// RawClientHelloLT applies the LT predicate on the "raw_client_hello" field.
func RawClientHelloLT(v []byte) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldLT(FieldRawClientHello, v))
}

// RawClientHelloLTE applies the LTE predicate on the "raw_client_hello" field.
func RawClientHelloLTE(v []byte) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldLTE(FieldRawClientHello, v))
}

// RawClientHelloIsNil applies the IsNil predicate on the "raw_client_hello" field.
func RawClientHelloIsNil() predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldIsNull(FieldRawClientHello))
}

// RawClientHelloNotNil applies the NotNil predicate on the "raw_client_hello" field.
func RawClientHelloNotNil() predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldNotNull(FieldRawClientHello))
}

// SessionStatusEQ applies the EQ predicate on the "session_status" field.
func SessionStatusEQ(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldEQ(FieldSessionStatus, v))
}

// SessionStatusNEQ applies the NEQ predicate on the "session_status" field.
func SessionStatusNEQ(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldNEQ(FieldSessionStatus, v))
}

// SessionStatusIn applies the In predicate on the "session_status" field.
func SessionStatusIn(vs ...string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldIn(FieldSessionStatus, vs...))
}

// SessionStatusNotIn applies the NotIn predicate on the "session_status" field.
func SessionStatusNotIn(vs ...string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldNotIn(FieldSessionStatus, vs...))
}

// SessionStatusGT applies the GT predicate on the "session_status" field.
func SessionStatusGT(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldGT(FieldSessionStatus, v))
}

// SessionStatusGTE applies the GTE predicate on the "session_status" field.
func SessionStatusGTE(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldGTE(FieldSessionStatus, v))
}

// SessionStatusLT applies the LT predicate on the "session_status" field.
func SessionStatusLT(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldLT(FieldSessionStatus, v))
}

// SessionStatusLTE applies the LTE predicate on the "session_status" field.
func SessionStatusLTE(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldLTE(FieldSessionStatus, v))
}

// SessionStatusContains applies the Contains predicate on the "session_status" field.
func SessionStatusContains(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldContains(FieldSessionStatus, v))
}

// SessionStatusHasPrefix applies the HasPrefix predicate on the "session_status" field.
func SessionStatusHasPrefix(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldHasPrefix(FieldSessionStatus, v))
}

// SessionStatusHasSuffix applies the HasSuffix predicate on the "session_status" field.
func SessionStatusHasSuffix(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldHasSuffix(FieldSessionStatus, v))
}

// SessionStatusEqualFold applies the EqualFold predicate on the "session_status" field.
func SessionStatusEqualFold(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldEqualFold(FieldSessionStatus, v))
}

// SessionStatusContainsFold applies the ContainsFold predicate on the "session_status" field.
func SessionStatusContainsFold(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldContainsFold(FieldSessionStatus, v))
}

// ErrorSummaryEQ applies the EQ predicate on the "error_summary" field.
func ErrorSummaryEQ(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldEQ(FieldErrorSummary, v))
}

// ErrorSummaryNEQ applies the NEQ predicate on the "error_summary" field.
func ErrorSummaryNEQ(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldNEQ(FieldErrorSummary, v))
}

// ErrorSummaryIn applies the In predicate on the "error_summary" field.
func ErrorSummaryIn(vs ...string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldIn(FieldErrorSummary, vs...))
}

// ErrorSummaryNotIn applies the NotIn predicate on the "error_summary" field.
func ErrorSummaryNotIn(vs ...string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldNotIn(FieldErrorSummary, vs...))
}

// ErrorSummaryGT applies the GT predicate on the "error_summary" field.
func ErrorSummaryGT(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldGT(FieldErrorSummary, v))
}

// ErrorSummaryGTE applies the GTE predicate on the "error_summary" field.
func ErrorSummaryGTE(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldGTE(FieldErrorSummary, v))
}

// ErrorSummaryLT applies the LT predicate on the "error_summary" field.
func ErrorSummaryLT(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldLT(FieldErrorSummary, v))
}

// ErrorSummaryLTE applies the LTE predicate on the "error_summary" field.
func ErrorSummaryLTE(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldLTE(FieldErrorSummary, v))
}

// ErrorSummaryContains applies the Contains predicate on the "error_summary" field.
func ErrorSummaryContains(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldContains(FieldErrorSummary, v))
}

// ErrorSummaryHasPrefix applies the HasPrefix predicate on the "error_summary" field.
func ErrorSummaryHasPrefix(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldHasPrefix(FieldErrorSummary, v))
}

// ErrorSummaryHasSuffix applies the HasSuffix predicate on the "error_summary" field.
func ErrorSummaryHasSuffix(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldHasSuffix(FieldErrorSummary, v))
}

// ErrorSummaryEqualFold applies the EqualFold predicate on the "error_summary" field.
func ErrorSummaryEqualFold(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldEqualFold(FieldErrorSummary, v))
}

// ErrorSummaryContainsFold applies the ContainsFold predicate on the "error_summary" field.
func ErrorSummaryContainsFold(v string) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldContainsFold(FieldErrorSummary, v))
}

// OpenedAtEQ applies the EQ predicate on the "opened_at" field.
func OpenedAtEQ(v time.Time) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldEQ(FieldOpenedAt, v))
}

// OpenedAtNEQ applies the NEQ predicate on the "opened_at" field.
func OpenedAtNEQ(v time.Time) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldNEQ(FieldOpenedAt, v))
}

// OpenedAtIn applies the In predicate on the "opened_at" field.
func OpenedAtIn(vs ...time.Time) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldIn(FieldOpenedAt, vs...))
}

// OpenedAtNotIn applies the NotIn predicate on the "opened_at" field.
func OpenedAtNotIn(vs ...time.Time) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldNotIn(FieldOpenedAt, vs...))
}

// OpenedAtGT applies the GT predicate on the "opened_at" field.
func OpenedAtGT(v time.Time) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldGT(FieldOpenedAt, v))
}

// OpenedAtGTE applies the GTE predicate on the "opened_at" field.
func OpenedAtGTE(v time.Time) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldGTE(FieldOpenedAt, v))
}

// OpenedAtLT applies the LT predicate on the "opened_at" field.
func OpenedAtLT(v time.Time) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldLT(FieldOpenedAt, v))
}

// OpenedAtLTE applies the LTE predicate on the "opened_at" field.
func OpenedAtLTE(v time.Time) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldLTE(FieldOpenedAt, v))
}

// ClosedAtEQ applies the EQ predicate on the "closed_at" field.
func ClosedAtEQ(v time.Time) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldEQ(FieldClosedAt, v))
}

// ClosedAtNEQ applies the NEQ predicate on the "closed_at" field.
func ClosedAtNEQ(v time.Time) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldNEQ(FieldClosedAt, v))
}

// ClosedAtIn applies the In predicate on the "closed_at" field.
func ClosedAtIn(vs ...time.Time) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldIn(FieldClosedAt, vs...))
}

// ClosedAtNotIn applies the NotIn predicate on the "closed_at" field.
func ClosedAtNotIn(vs ...time.Time) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldNotIn(FieldClosedAt, vs...))
}

// ClosedAtGT applies the GT predicate on the "closed_at" field.
func ClosedAtGT(v time.Time) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldGT(FieldClosedAt, v))
}

// ClosedAtGTE applies the GTE predicate on the "closed_at" field.
func ClosedAtGTE(v time.Time) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldGTE(FieldClosedAt, v))
}

// ClosedAtLT applies the LT predicate on the "closed_at" field.
func ClosedAtLT(v time.Time) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldLT(FieldClosedAt, v))
}

// ClosedAtLTE applies the LTE predicate on the "closed_at" field.
func ClosedAtLTE(v time.Time) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldLTE(FieldClosedAt, v))
}

// ClosedAtIsNil applies the IsNil predicate on the "closed_at" field.
func ClosedAtIsNil() predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldIsNull(FieldClosedAt))
}

// ClosedAtNotNil applies the NotNil predicate on the "closed_at" field.
func ClosedAtNotNil() predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.FieldNotNull(FieldClosedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TLSFingerprintCaptureSession) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TLSFingerprintCaptureSession) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TLSFingerprintCaptureSession) predicate.TLSFingerprintCaptureSession {
	return predicate.TLSFingerprintCaptureSession(sql.NotPredicates(p))
}
