// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AIAsset is the predicate function for aiasset builders.
type AIAsset func(*sql.Selector)

// AIAuditLog is the predicate function for aiauditlog builders.
type AIAuditLog func(*sql.Selector)

// AIGenerationJob is the predicate function for aigenerationjob builders.
type AIGenerationJob func(*sql.Selector)

// AIPromptTemplate is the predicate function for aiprompttemplate builders.
type AIPromptTemplate func(*sql.Selector)

// AIPromptTemplateVersion is the predicate function for aiprompttemplateversion builders.
type AIPromptTemplateVersion func(*sql.Selector)

// AISession is the predicate function for aisession builders.
type AISession func(*sql.Selector)

// AISessionMessage is the predicate function for aisessionmessage builders.
type AISessionMessage func(*sql.Selector)

// AISkill is the predicate function for aiskill builders.
type AISkill func(*sql.Selector)

// AISkillInstall is the predicate function for aiskillinstall builders.
type AISkillInstall func(*sql.Selector)

// AISkillLike is the predicate function for aiskilllike builders.
type AISkillLike func(*sql.Selector)

// AISkillReview is the predicate function for aiskillreview builders.
type AISkillReview func(*sql.Selector)

// AISkillRun is the predicate function for aiskillrun builders.
type AISkillRun func(*sql.Selector)

// AISkillSettlement is the predicate function for aiskillsettlement builders.
type AISkillSettlement func(*sql.Selector)

// AISkillVersion is the predicate function for aiskillversion builders.
type AISkillVersion func(*sql.Selector)

// APIKey is the predicate function for apikey builders.
type APIKey func(*sql.Selector)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// AccountGroup is the predicate function for accountgroup builders.
type AccountGroup func(*sql.Selector)

// Announcement is the predicate function for announcement builders.
type Announcement func(*sql.Selector)

// AnnouncementRead is the predicate function for announcementread builders.
type AnnouncementRead func(*sql.Selector)

// AuthIdentity is the predicate function for authidentity builders.
type AuthIdentity func(*sql.Selector)

// AuthIdentityChannel is the predicate function for authidentitychannel builders.
type AuthIdentityChannel func(*sql.Selector)

// BatchImageEvent is the predicate function for batchimageevent builders.
type BatchImageEvent func(*sql.Selector)

// BatchImageItem is the predicate function for batchimageitem builders.
type BatchImageItem func(*sql.Selector)

// BatchImageJob is the predicate function for batchimagejob builders.
type BatchImageJob func(*sql.Selector)

// ChannelMonitor is the predicate function for channelmonitor builders.
type ChannelMonitor func(*sql.Selector)

// ChannelMonitorDailyRollup is the predicate function for channelmonitordailyrollup builders.
type ChannelMonitorDailyRollup func(*sql.Selector)

// ChannelMonitorHistory is the predicate function for channelmonitorhistory builders.
type ChannelMonitorHistory func(*sql.Selector)

// ChannelMonitorRequestTemplate is the predicate function for channelmonitorrequesttemplate builders.
type ChannelMonitorRequestTemplate func(*sql.Selector)

// ErrorPassthroughRule is the predicate function for errorpassthroughrule builders.
type ErrorPassthroughRule func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// IdempotencyRecord is the predicate function for idempotencyrecord builders.
type IdempotencyRecord func(*sql.Selector)

// IdentityAdoptionDecision is the predicate function for identityadoptiondecision builders.
type IdentityAdoptionDecision func(*sql.Selector)

// Invoice is the predicate function for invoice builders.
type Invoice func(*sql.Selector)

// InvoiceOrder is the predicate function for invoiceorder builders.
type InvoiceOrder func(*sql.Selector)

// PaymentAuditLog is the predicate function for paymentauditlog builders.
type PaymentAuditLog func(*sql.Selector)

// PaymentOrder is the predicate function for paymentorder builders.
type PaymentOrder func(*sql.Selector)

// PaymentProviderInstance is the predicate function for paymentproviderinstance builders.
type PaymentProviderInstance func(*sql.Selector)

// PendingAuthSession is the predicate function for pendingauthsession builders.
type PendingAuthSession func(*sql.Selector)

// PromoCode is the predicate function for promocode builders.
type PromoCode func(*sql.Selector)

// PromoCodeUsage is the predicate function for promocodeusage builders.
type PromoCodeUsage func(*sql.Selector)

// Proxy is the predicate function for proxy builders.
type Proxy func(*sql.Selector)

// RedeemCode is the predicate function for redeemcode builders.
type RedeemCode func(*sql.Selector)

// SecuritySecret is the predicate function for securitysecret builders.
type SecuritySecret func(*sql.Selector)

// Setting is the predicate function for setting builders.
type Setting func(*sql.Selector)

// SubscriptionPlan is the predicate function for subscriptionplan builders.
type SubscriptionPlan func(*sql.Selector)

// TLSFingerprintCaptureSample is the predicate function for tlsfingerprintcapturesample builders.
type TLSFingerprintCaptureSample func(*sql.Selector)

// TLSFingerprintCaptureSession is the predicate function for tlsfingerprintcapturesession builders.
type TLSFingerprintCaptureSession func(*sql.Selector)

// TLSFingerprintCaptureSessionEvent is the predicate function for tlsfingerprintcapturesessionevent builders.
type TLSFingerprintCaptureSessionEvent func(*sql.Selector)

// TLSFingerprintCaptureTask is the predicate function for tlsfingerprintcapturetask builders.
type TLSFingerprintCaptureTask func(*sql.Selector)

// TLSFingerprintProfile is the predicate function for tlsfingerprintprofile builders.
type TLSFingerprintProfile func(*sql.Selector)

// TLSFingerprintRouter is the predicate function for tlsfingerprintrouter builders.
type TLSFingerprintRouter func(*sql.Selector)

// UsageCleanupTask is the predicate function for usagecleanuptask builders.
type UsageCleanupTask func(*sql.Selector)

// UsageLog is the predicate function for usagelog builders.
type UsageLog func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserAllowedGroup is the predicate function for userallowedgroup builders.
type UserAllowedGroup func(*sql.Selector)

// UserAttributeDefinition is the predicate function for userattributedefinition builders.
type UserAttributeDefinition func(*sql.Selector)

// UserAttributeValue is the predicate function for userattributevalue builders.
type UserAttributeValue func(*sql.Selector)

// UserPlatformQuota is the predicate function for userplatformquota builders.
type UserPlatformQuota func(*sql.Selector)

// UserSubscription is the predicate function for usersubscription builders.
type UserSubscription func(*sql.Selector)
