// Code generated by ent, DO NOT EDIT.

package invoiceapplication

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the invoiceapplication type in the database.
	Label = "invoice_application"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOrderID holds the string denoting the order_id field in the database.
	FieldOrderID = "order_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldUserEmail holds the string denoting the user_email field in the database.
	FieldUserEmail = "user_email"
	// FieldOrderOutTradeNo holds the string denoting the order_out_trade_no field in the database.
	FieldOrderOutTradeNo = "order_out_trade_no"
	// FieldPaymentType holds the string denoting the payment_type field in the database.
	FieldPaymentType = "payment_type"
	// FieldProviderInstanceID holds the string denoting the provider_instance_id field in the database.
	FieldProviderInstanceID = "provider_instance_id"
	// FieldProviderKey holds the string denoting the provider_key field in the database.
	FieldProviderKey = "provider_key"
	// FieldInvoiceStatus holds the string denoting the invoice_status field in the database.
	FieldInvoiceStatus = "invoice_status"
	// FieldInvoiceAmount holds the string denoting the invoice_amount field in the database.
	FieldInvoiceAmount = "invoice_amount"
	// FieldInvoiceTitle holds the string denoting the invoice_title field in the database.
	FieldInvoiceTitle = "invoice_title"
	// FieldTaxNumber holds the string denoting the tax_number field in the database.
	FieldTaxNumber = "tax_number"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldContactName holds the string denoting the contact_name field in the database.
	FieldContactName = "contact_name"
	// FieldContactPhone holds the string denoting the contact_phone field in the database.
	FieldContactPhone = "contact_phone"
	// FieldRequestNote holds the string denoting the request_note field in the database.
	FieldRequestNote = "request_note"
	// FieldFileMediaID holds the string denoting the file_media_id field in the database.
	FieldFileMediaID = "file_media_id"
	// FieldFileName holds the string denoting the file_name field in the database.
	FieldFileName = "file_name"
	// FieldFileMimeType holds the string denoting the file_mime_type field in the database.
	FieldFileMimeType = "file_mime_type"
	// FieldFileSizeBytes holds the string denoting the file_size_bytes field in the database.
	FieldFileSizeBytes = "file_size_bytes"
	// FieldAppliedAt holds the string denoting the applied_at field in the database.
	FieldAppliedAt = "applied_at"
	// FieldCancelledAt holds the string denoting the cancelled_at field in the database.
	FieldCancelledAt = "cancelled_at"
	// FieldIssuedAt holds the string denoting the issued_at field in the database.
	FieldIssuedAt = "issued_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the invoiceapplication in the database.
	Table = "invoice_applications"
)

// Columns holds all SQL columns for invoiceapplication fields.
var Columns = []string{
	FieldID,
	FieldOrderID,
	FieldUserID,
	FieldUserEmail,
	FieldOrderOutTradeNo,
	FieldPaymentType,
	FieldProviderInstanceID,
	FieldProviderKey,
	FieldInvoiceStatus,
	FieldInvoiceAmount,
	FieldInvoiceTitle,
	FieldTaxNumber,
	FieldEmail,
	FieldContactName,
	FieldContactPhone,
	FieldRequestNote,
	FieldFileMediaID,
	FieldFileName,
	FieldFileMimeType,
	FieldFileSizeBytes,
	FieldAppliedAt,
	FieldCancelledAt,
	FieldIssuedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultUserEmail holds the default value on creation for the "user_email" field.
	DefaultUserEmail string
	// UserEmailValidator is a validator for the "user_email" field. It is called by the builders before save.
	UserEmailValidator func(string) error
	// DefaultOrderOutTradeNo holds the default value on creation for the "order_out_trade_no" field.
	DefaultOrderOutTradeNo string
	// OrderOutTradeNoValidator is a validator for the "order_out_trade_no" field. It is called by the builders before save.
	OrderOutTradeNoValidator func(string) error
	// DefaultPaymentType holds the default value on creation for the "payment_type" field.
	DefaultPaymentType string
	// PaymentTypeValidator is a validator for the "payment_type" field. It is called by the builders before save.
	PaymentTypeValidator func(string) error
	// DefaultProviderInstanceID holds the default value on creation for the "provider_instance_id" field.
	DefaultProviderInstanceID string
	// ProviderInstanceIDValidator is a validator for the "provider_instance_id" field. It is called by the builders before save.
	ProviderInstanceIDValidator func(string) error
	// DefaultProviderKey holds the default value on creation for the "provider_key" field.
	DefaultProviderKey string
	// ProviderKeyValidator is a validator for the "provider_key" field. It is called by the builders before save.
	ProviderKeyValidator func(string) error
	// DefaultInvoiceStatus holds the default value on creation for the "invoice_status" field.
	DefaultInvoiceStatus string
	// InvoiceStatusValidator is a validator for the "invoice_status" field. It is called by the builders before save.
	InvoiceStatusValidator func(string) error
	// DefaultInvoiceAmount holds the default value on creation for the "invoice_amount" field.
	DefaultInvoiceAmount float64
	// DefaultInvoiceTitle holds the default value on creation for the "invoice_title" field.
	DefaultInvoiceTitle string
	// InvoiceTitleValidator is a validator for the "invoice_title" field. It is called by the builders before save.
	InvoiceTitleValidator func(string) error
	// DefaultTaxNumber holds the default value on creation for the "tax_number" field.
	DefaultTaxNumber string
	// TaxNumberValidator is a validator for the "tax_number" field. It is called by the builders before save.
	TaxNumberValidator func(string) error
	// DefaultEmail holds the default value on creation for the "email" field.
	DefaultEmail string
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// DefaultContactName holds the default value on creation for the "contact_name" field.
	DefaultContactName string
	// ContactNameValidator is a validator for the "contact_name" field. It is called by the builders before save.
	ContactNameValidator func(string) error
	// DefaultContactPhone holds the default value on creation for the "contact_phone" field.
	DefaultContactPhone string
	// ContactPhoneValidator is a validator for the "contact_phone" field. It is called by the builders before save.
	ContactPhoneValidator func(string) error
	// DefaultFileName holds the default value on creation for the "file_name" field.
	DefaultFileName string
	// FileNameValidator is a validator for the "file_name" field. It is called by the builders before save.
	FileNameValidator func(string) error
	// DefaultFileMimeType holds the default value on creation for the "file_mime_type" field.
	DefaultFileMimeType string
	// FileMimeTypeValidator is a validator for the "file_mime_type" field. It is called by the builders before save.
	FileMimeTypeValidator func(string) error
	// DefaultFileSizeBytes holds the default value on creation for the "file_size_bytes" field.
	DefaultFileSizeBytes int64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the InvoiceApplication queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOrderID orders the results by the order_id field.
func ByOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByUserEmail orders the results by the user_email field.
func ByUserEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserEmail, opts...).ToFunc()
}

// ByOrderOutTradeNo orders the results by the order_out_trade_no field.
func ByOrderOutTradeNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderOutTradeNo, opts...).ToFunc()
}

// ByPaymentType orders the results by the payment_type field.
func ByPaymentType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaymentType, opts...).ToFunc()
}

// ByProviderInstanceID orders the results by the provider_instance_id field.
func ByProviderInstanceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderInstanceID, opts...).ToFunc()
}

// ByProviderKey orders the results by the provider_key field.
func ByProviderKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderKey, opts...).ToFunc()
}

// ByInvoiceStatus orders the results by the invoice_status field.
func ByInvoiceStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvoiceStatus, opts...).ToFunc()
}

// ByInvoiceAmount orders the results by the invoice_amount field.
func ByInvoiceAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvoiceAmount, opts...).ToFunc()
}

// ByInvoiceTitle orders the results by the invoice_title field.
func ByInvoiceTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvoiceTitle, opts...).ToFunc()
}

// ByTaxNumber orders the results by the tax_number field.
func ByTaxNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaxNumber, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByContactName orders the results by the contact_name field.
func ByContactName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContactName, opts...).ToFunc()
}

// ByContactPhone orders the results by the contact_phone field.
func ByContactPhone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContactPhone, opts...).ToFunc()
}

// ByRequestNote orders the results by the request_note field.
func ByRequestNote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestNote, opts...).ToFunc()
}

// ByFileMediaID orders the results by the file_media_id field.
func ByFileMediaID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileMediaID, opts...).ToFunc()
}

// ByFileName orders the results by the file_name field.
func ByFileName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileName, opts...).ToFunc()
}

// ByFileMimeType orders the results by the file_mime_type field.
func ByFileMimeType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileMimeType, opts...).ToFunc()
}

// ByFileSizeBytes orders the results by the file_size_bytes field.
func ByFileSizeBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileSizeBytes, opts...).ToFunc()
}

// ByAppliedAt orders the results by the applied_at field.
func ByAppliedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAppliedAt, opts...).ToFunc()
}

// ByCancelledAt orders the results by the cancelled_at field.
func ByCancelledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCancelledAt, opts...).ToFunc()
}

// ByIssuedAt orders the results by the issued_at field.
func ByIssuedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIssuedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
