ALTER TABLE usage_logs
    ADD COLUMN IF NOT EXISTS video_resolution VARCHAR(20),
    ADD COLUMN IF NOT EXISTS video_seconds INTEGER,
    ADD COLUMN IF NOT EXISTS video_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS video_unit_price NUMERIC(20,10);
