// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/aiauditlog"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AIAuditLogUpdate is the builder for updating AIAuditLog entities.
type AIAuditLogUpdate struct {
	config
	hooks    []Hook
	mutation *AIAuditLogMutation
}

// Where appends a list predicates to the AIAuditLogUpdate builder.
func (_u *AIAuditLogUpdate) Where(ps ...predicate.AIAuditLog) *AIAuditLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOperatorUserID sets the "operator_user_id" field.
func (_u *AIAuditLogUpdate) SetOperatorUserID(v int64) *AIAuditLogUpdate {
	_u.mutation.ResetOperatorUserID()
	_u.mutation.SetOperatorUserID(v)
	return _u
}

// SetNillableOperatorUserID sets the "operator_user_id" field if the given value is not nil.
func (_u *AIAuditLogUpdate) SetNillableOperatorUserID(v *int64) *AIAuditLogUpdate {
	if v != nil {
		_u.SetOperatorUserID(*v)
	}
	return _u
}

// AddOperatorUserID adds value to the "operator_user_id" field.
func (_u *AIAuditLogUpdate) AddOperatorUserID(v int64) *AIAuditLogUpdate {
	_u.mutation.AddOperatorUserID(v)
	return _u
}

// ClearOperatorUserID clears the value of the "operator_user_id" field.
func (_u *AIAuditLogUpdate) ClearOperatorUserID() *AIAuditLogUpdate {
	_u.mutation.ClearOperatorUserID()
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *AIAuditLogUpdate) SetOwnerUserID(v int64) *AIAuditLogUpdate {
	_u.mutation.ResetOwnerUserID()
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *AIAuditLogUpdate) SetNillableOwnerUserID(v *int64) *AIAuditLogUpdate {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// AddOwnerUserID adds value to the "owner_user_id" field.
func (_u *AIAuditLogUpdate) AddOwnerUserID(v int64) *AIAuditLogUpdate {
	_u.mutation.AddOwnerUserID(v)
	return _u
}

// ClearOwnerUserID clears the value of the "owner_user_id" field.
func (_u *AIAuditLogUpdate) ClearOwnerUserID() *AIAuditLogUpdate {
	_u.mutation.ClearOwnerUserID()
	return _u
}

// SetEntityType sets the "entity_type" field.
func (_u *AIAuditLogUpdate) SetEntityType(v string) *AIAuditLogUpdate {
	_u.mutation.SetEntityType(v)
	return _u
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (_u *AIAuditLogUpdate) SetNillableEntityType(v *string) *AIAuditLogUpdate {
	if v != nil {
		_u.SetEntityType(*v)
	}
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *AIAuditLogUpdate) SetEntityID(v int64) *AIAuditLogUpdate {
	_u.mutation.ResetEntityID()
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *AIAuditLogUpdate) SetNillableEntityID(v *int64) *AIAuditLogUpdate {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// AddEntityID adds value to the "entity_id" field.
func (_u *AIAuditLogUpdate) AddEntityID(v int64) *AIAuditLogUpdate {
	_u.mutation.AddEntityID(v)
	return _u
}

// ClearEntityID clears the value of the "entity_id" field.
func (_u *AIAuditLogUpdate) ClearEntityID() *AIAuditLogUpdate {
	_u.mutation.ClearEntityID()
	return _u
}

// SetAction sets the "action" field.
func (_u *AIAuditLogUpdate) SetAction(v string) *AIAuditLogUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *AIAuditLogUpdate) SetNillableAction(v *string) *AIAuditLogUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *AIAuditLogUpdate) SetReason(v string) *AIAuditLogUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *AIAuditLogUpdate) SetNillableReason(v *string) *AIAuditLogUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *AIAuditLogUpdate) ClearReason() *AIAuditLogUpdate {
	_u.mutation.ClearReason()
	return _u
}

// SetBeforeState sets the "before_state" field.
func (_u *AIAuditLogUpdate) SetBeforeState(v map[string]interface{}) *AIAuditLogUpdate {
	_u.mutation.SetBeforeState(v)
	return _u
}

// SetAfterState sets the "after_state" field.
func (_u *AIAuditLogUpdate) SetAfterState(v map[string]interface{}) *AIAuditLogUpdate {
	_u.mutation.SetAfterState(v)
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *AIAuditLogUpdate) SetRequestID(v string) *AIAuditLogUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *AIAuditLogUpdate) SetNillableRequestID(v *string) *AIAuditLogUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *AIAuditLogUpdate) ClearRequestID() *AIAuditLogUpdate {
	_u.mutation.ClearRequestID()
	return _u
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *AIAuditLogUpdate) SetUsageLogID(v int64) *AIAuditLogUpdate {
	_u.mutation.ResetUsageLogID()
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *AIAuditLogUpdate) SetNillableUsageLogID(v *int64) *AIAuditLogUpdate {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// AddUsageLogID adds value to the "usage_log_id" field.
func (_u *AIAuditLogUpdate) AddUsageLogID(v int64) *AIAuditLogUpdate {
	_u.mutation.AddUsageLogID(v)
	return _u
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (_u *AIAuditLogUpdate) ClearUsageLogID() *AIAuditLogUpdate {
	_u.mutation.ClearUsageLogID()
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *AIAuditLogUpdate) SetAPIKeyID(v int64) *AIAuditLogUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *AIAuditLogUpdate) SetNillableAPIKeyID(v *int64) *AIAuditLogUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *AIAuditLogUpdate) AddAPIKeyID(v int64) *AIAuditLogUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (_u *AIAuditLogUpdate) ClearAPIKeyID() *AIAuditLogUpdate {
	_u.mutation.ClearAPIKeyID()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *AIAuditLogUpdate) SetGroupID(v int64) *AIAuditLogUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *AIAuditLogUpdate) SetNillableGroupID(v *int64) *AIAuditLogUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *AIAuditLogUpdate) AddGroupID(v int64) *AIAuditLogUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *AIAuditLogUpdate) ClearGroupID() *AIAuditLogUpdate {
	_u.mutation.ClearGroupID()
	return _u
}

// Mutation returns the AIAuditLogMutation object of the builder.
func (_u *AIAuditLogUpdate) Mutation() *AIAuditLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AIAuditLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AIAuditLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AIAuditLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AIAuditLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AIAuditLogUpdate) check() error {
	if v, ok := _u.mutation.EntityType(); ok {
		if err := aiauditlog.EntityTypeValidator(v); err != nil {
			return &ValidationError{Name: "entity_type", err: fmt.Errorf(`ent: validator failed for field "AIAuditLog.entity_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Action(); ok {
		if err := aiauditlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "AIAuditLog.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := aiauditlog.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "AIAuditLog.request_id": %w`, err)}
		}
	}
	return nil
}

func (_u *AIAuditLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(aiauditlog.Table, aiauditlog.Columns, sqlgraph.NewFieldSpec(aiauditlog.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OperatorUserID(); ok {
		_spec.SetField(aiauditlog.FieldOperatorUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOperatorUserID(); ok {
		_spec.AddField(aiauditlog.FieldOperatorUserID, field.TypeInt64, value)
	}
	if _u.mutation.OperatorUserIDCleared() {
		_spec.ClearField(aiauditlog.FieldOperatorUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.OwnerUserID(); ok {
		_spec.SetField(aiauditlog.FieldOwnerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOwnerUserID(); ok {
		_spec.AddField(aiauditlog.FieldOwnerUserID, field.TypeInt64, value)
	}
	if _u.mutation.OwnerUserIDCleared() {
		_spec.ClearField(aiauditlog.FieldOwnerUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.EntityType(); ok {
		_spec.SetField(aiauditlog.FieldEntityType, field.TypeString, value)
	}
	if value, ok := _u.mutation.EntityID(); ok {
		_spec.SetField(aiauditlog.FieldEntityID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEntityID(); ok {
		_spec.AddField(aiauditlog.FieldEntityID, field.TypeInt64, value)
	}
	if _u.mutation.EntityIDCleared() {
		_spec.ClearField(aiauditlog.FieldEntityID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(aiauditlog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(aiauditlog.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(aiauditlog.FieldReason, field.TypeString)
	}
	if value, ok := _u.mutation.BeforeState(); ok {
		_spec.SetField(aiauditlog.FieldBeforeState, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AfterState(); ok {
		_spec.SetField(aiauditlog.FieldAfterState, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(aiauditlog.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(aiauditlog.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.UsageLogID(); ok {
		_spec.SetField(aiauditlog.FieldUsageLogID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsageLogID(); ok {
		_spec.AddField(aiauditlog.FieldUsageLogID, field.TypeInt64, value)
	}
	if _u.mutation.UsageLogIDCleared() {
		_spec.ClearField(aiauditlog.FieldUsageLogID, field.TypeInt64)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(aiauditlog.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(aiauditlog.FieldAPIKeyID, field.TypeInt64, value)
	}
	if _u.mutation.APIKeyIDCleared() {
		_spec.ClearField(aiauditlog.FieldAPIKeyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(aiauditlog.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(aiauditlog.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(aiauditlog.FieldGroupID, field.TypeInt64)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{aiauditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AIAuditLogUpdateOne is the builder for updating a single AIAuditLog entity.
type AIAuditLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AIAuditLogMutation
}

// SetOperatorUserID sets the "operator_user_id" field.
func (_u *AIAuditLogUpdateOne) SetOperatorUserID(v int64) *AIAuditLogUpdateOne {
	_u.mutation.ResetOperatorUserID()
	_u.mutation.SetOperatorUserID(v)
	return _u
}

// SetNillableOperatorUserID sets the "operator_user_id" field if the given value is not nil.
func (_u *AIAuditLogUpdateOne) SetNillableOperatorUserID(v *int64) *AIAuditLogUpdateOne {
	if v != nil {
		_u.SetOperatorUserID(*v)
	}
	return _u
}

// AddOperatorUserID adds value to the "operator_user_id" field.
func (_u *AIAuditLogUpdateOne) AddOperatorUserID(v int64) *AIAuditLogUpdateOne {
	_u.mutation.AddOperatorUserID(v)
	return _u
}

// ClearOperatorUserID clears the value of the "operator_user_id" field.
func (_u *AIAuditLogUpdateOne) ClearOperatorUserID() *AIAuditLogUpdateOne {
	_u.mutation.ClearOperatorUserID()
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *AIAuditLogUpdateOne) SetOwnerUserID(v int64) *AIAuditLogUpdateOne {
	_u.mutation.ResetOwnerUserID()
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *AIAuditLogUpdateOne) SetNillableOwnerUserID(v *int64) *AIAuditLogUpdateOne {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// AddOwnerUserID adds value to the "owner_user_id" field.
func (_u *AIAuditLogUpdateOne) AddOwnerUserID(v int64) *AIAuditLogUpdateOne {
	_u.mutation.AddOwnerUserID(v)
	return _u
}

// ClearOwnerUserID clears the value of the "owner_user_id" field.
func (_u *AIAuditLogUpdateOne) ClearOwnerUserID() *AIAuditLogUpdateOne {
	_u.mutation.ClearOwnerUserID()
	return _u
}

// SetEntityType sets the "entity_type" field.
func (_u *AIAuditLogUpdateOne) SetEntityType(v string) *AIAuditLogUpdateOne {
	_u.mutation.SetEntityType(v)
	return _u
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (_u *AIAuditLogUpdateOne) SetNillableEntityType(v *string) *AIAuditLogUpdateOne {
	if v != nil {
		_u.SetEntityType(*v)
	}
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *AIAuditLogUpdateOne) SetEntityID(v int64) *AIAuditLogUpdateOne {
	_u.mutation.ResetEntityID()
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *AIAuditLogUpdateOne) SetNillableEntityID(v *int64) *AIAuditLogUpdateOne {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// AddEntityID adds value to the "entity_id" field.
func (_u *AIAuditLogUpdateOne) AddEntityID(v int64) *AIAuditLogUpdateOne {
	_u.mutation.AddEntityID(v)
	return _u
}

// ClearEntityID clears the value of the "entity_id" field.
func (_u *AIAuditLogUpdateOne) ClearEntityID() *AIAuditLogUpdateOne {
	_u.mutation.ClearEntityID()
	return _u
}

// SetAction sets the "action" field.
func (_u *AIAuditLogUpdateOne) SetAction(v string) *AIAuditLogUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *AIAuditLogUpdateOne) SetNillableAction(v *string) *AIAuditLogUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *AIAuditLogUpdateOne) SetReason(v string) *AIAuditLogUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *AIAuditLogUpdateOne) SetNillableReason(v *string) *AIAuditLogUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *AIAuditLogUpdateOne) ClearReason() *AIAuditLogUpdateOne {
	_u.mutation.ClearReason()
	return _u
}

// SetBeforeState sets the "before_state" field.
func (_u *AIAuditLogUpdateOne) SetBeforeState(v map[string]interface{}) *AIAuditLogUpdateOne {
	_u.mutation.SetBeforeState(v)
	return _u
}

// SetAfterState sets the "after_state" field.
func (_u *AIAuditLogUpdateOne) SetAfterState(v map[string]interface{}) *AIAuditLogUpdateOne {
	_u.mutation.SetAfterState(v)
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *AIAuditLogUpdateOne) SetRequestID(v string) *AIAuditLogUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *AIAuditLogUpdateOne) SetNillableRequestID(v *string) *AIAuditLogUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *AIAuditLogUpdateOne) ClearRequestID() *AIAuditLogUpdateOne {
	_u.mutation.ClearRequestID()
	return _u
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *AIAuditLogUpdateOne) SetUsageLogID(v int64) *AIAuditLogUpdateOne {
	_u.mutation.ResetUsageLogID()
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *AIAuditLogUpdateOne) SetNillableUsageLogID(v *int64) *AIAuditLogUpdateOne {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// AddUsageLogID adds value to the "usage_log_id" field.
func (_u *AIAuditLogUpdateOne) AddUsageLogID(v int64) *AIAuditLogUpdateOne {
	_u.mutation.AddUsageLogID(v)
	return _u
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (_u *AIAuditLogUpdateOne) ClearUsageLogID() *AIAuditLogUpdateOne {
	_u.mutation.ClearUsageLogID()
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *AIAuditLogUpdateOne) SetAPIKeyID(v int64) *AIAuditLogUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *AIAuditLogUpdateOne) SetNillableAPIKeyID(v *int64) *AIAuditLogUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *AIAuditLogUpdateOne) AddAPIKeyID(v int64) *AIAuditLogUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (_u *AIAuditLogUpdateOne) ClearAPIKeyID() *AIAuditLogUpdateOne {
	_u.mutation.ClearAPIKeyID()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *AIAuditLogUpdateOne) SetGroupID(v int64) *AIAuditLogUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *AIAuditLogUpdateOne) SetNillableGroupID(v *int64) *AIAuditLogUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *AIAuditLogUpdateOne) AddGroupID(v int64) *AIAuditLogUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *AIAuditLogUpdateOne) ClearGroupID() *AIAuditLogUpdateOne {
	_u.mutation.ClearGroupID()
	return _u
}

// Mutation returns the AIAuditLogMutation object of the builder.
func (_u *AIAuditLogUpdateOne) Mutation() *AIAuditLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the AIAuditLogUpdate builder.
func (_u *AIAuditLogUpdateOne) Where(ps ...predicate.AIAuditLog) *AIAuditLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AIAuditLogUpdateOne) Select(field string, fields ...string) *AIAuditLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AIAuditLog entity.
func (_u *AIAuditLogUpdateOne) Save(ctx context.Context) (*AIAuditLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AIAuditLogUpdateOne) SaveX(ctx context.Context) *AIAuditLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AIAuditLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AIAuditLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AIAuditLogUpdateOne) check() error {
	if v, ok := _u.mutation.EntityType(); ok {
		if err := aiauditlog.EntityTypeValidator(v); err != nil {
			return &ValidationError{Name: "entity_type", err: fmt.Errorf(`ent: validator failed for field "AIAuditLog.entity_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Action(); ok {
		if err := aiauditlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "AIAuditLog.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := aiauditlog.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "AIAuditLog.request_id": %w`, err)}
		}
	}
	return nil
}

func (_u *AIAuditLogUpdateOne) sqlSave(ctx context.Context) (_node *AIAuditLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(aiauditlog.Table, aiauditlog.Columns, sqlgraph.NewFieldSpec(aiauditlog.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AIAuditLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, aiauditlog.FieldID)
		for _, f := range fields {
			if !aiauditlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != aiauditlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OperatorUserID(); ok {
		_spec.SetField(aiauditlog.FieldOperatorUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOperatorUserID(); ok {
		_spec.AddField(aiauditlog.FieldOperatorUserID, field.TypeInt64, value)
	}
	if _u.mutation.OperatorUserIDCleared() {
		_spec.ClearField(aiauditlog.FieldOperatorUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.OwnerUserID(); ok {
		_spec.SetField(aiauditlog.FieldOwnerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOwnerUserID(); ok {
		_spec.AddField(aiauditlog.FieldOwnerUserID, field.TypeInt64, value)
	}
	if _u.mutation.OwnerUserIDCleared() {
		_spec.ClearField(aiauditlog.FieldOwnerUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.EntityType(); ok {
		_spec.SetField(aiauditlog.FieldEntityType, field.TypeString, value)
	}
	if value, ok := _u.mutation.EntityID(); ok {
		_spec.SetField(aiauditlog.FieldEntityID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEntityID(); ok {
		_spec.AddField(aiauditlog.FieldEntityID, field.TypeInt64, value)
	}
	if _u.mutation.EntityIDCleared() {
		_spec.ClearField(aiauditlog.FieldEntityID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(aiauditlog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(aiauditlog.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(aiauditlog.FieldReason, field.TypeString)
	}
	if value, ok := _u.mutation.BeforeState(); ok {
		_spec.SetField(aiauditlog.FieldBeforeState, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AfterState(); ok {
		_spec.SetField(aiauditlog.FieldAfterState, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(aiauditlog.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(aiauditlog.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.UsageLogID(); ok {
		_spec.SetField(aiauditlog.FieldUsageLogID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsageLogID(); ok {
		_spec.AddField(aiauditlog.FieldUsageLogID, field.TypeInt64, value)
	}
	if _u.mutation.UsageLogIDCleared() {
		_spec.ClearField(aiauditlog.FieldUsageLogID, field.TypeInt64)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(aiauditlog.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(aiauditlog.FieldAPIKeyID, field.TypeInt64, value)
	}
	if _u.mutation.APIKeyIDCleared() {
		_spec.ClearField(aiauditlog.FieldAPIKeyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(aiauditlog.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(aiauditlog.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(aiauditlog.FieldGroupID, field.TypeInt64)
	}
	_node = &AIAuditLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{aiauditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
