// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/aigenerationjob"
	"github.com/Wei-Shaw/sub2api/ent/aiprompttemplate"
	"github.com/Wei-Shaw/sub2api/ent/aisession"
)

// AIGenerationJob is the model entity for the AIGenerationJob schema.
type AIGenerationJob struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// SessionID holds the value of the "session_id" field.
	SessionID *int64 `json:"session_id,omitempty"`
	// PromptTemplateID holds the value of the "prompt_template_id" field.
	PromptTemplateID *int64 `json:"prompt_template_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// Prompt holds the value of the "prompt" field.
	Prompt string `json:"prompt,omitempty"`
	// NegativePrompt holds the value of the "negative_prompt" field.
	NegativePrompt *string `json:"negative_prompt,omitempty"`
	// Size holds the value of the "size" field.
	Size *string `json:"size,omitempty"`
	// ImageCount holds the value of the "image_count" field.
	ImageCount int `json:"image_count,omitempty"`
	// Seed holds the value of the "seed" field.
	Seed *int64 `json:"seed,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage *string `json:"error_message,omitempty"`
	// Parameters holds the value of the "parameters" field.
	Parameters map[string]interface{} `json:"parameters,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID *string `json:"request_id,omitempty"`
	// UsageLogID holds the value of the "usage_log_id" field.
	UsageLogID *int64 `json:"usage_log_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID *int64 `json:"api_key_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID *int64 `json:"group_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AIGenerationJobQuery when eager-loading is set.
	Edges        AIGenerationJobEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AIGenerationJobEdges holds the relations/edges for other nodes in the graph.
type AIGenerationJobEdges struct {
	// Session holds the value of the session edge.
	Session *AISession `json:"session,omitempty"`
	// PromptTemplate holds the value of the prompt_template edge.
	PromptTemplate *AIPromptTemplate `json:"prompt_template,omitempty"`
	// Assets holds the value of the assets edge.
	Assets []*AIAsset `json:"assets,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// SessionOrErr returns the Session value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AIGenerationJobEdges) SessionOrErr() (*AISession, error) {
	if e.Session != nil {
		return e.Session, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: aisession.Label}
	}
	return nil, &NotLoadedError{edge: "session"}
}

// PromptTemplateOrErr returns the PromptTemplate value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AIGenerationJobEdges) PromptTemplateOrErr() (*AIPromptTemplate, error) {
	if e.PromptTemplate != nil {
		return e.PromptTemplate, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: aiprompttemplate.Label}
	}
	return nil, &NotLoadedError{edge: "prompt_template"}
}

// AssetsOrErr returns the Assets value or an error if the edge
// was not loaded in eager-loading.
func (e AIGenerationJobEdges) AssetsOrErr() ([]*AIAsset, error) {
	if e.loadedTypes[2] {
		return e.Assets, nil
	}
	return nil, &NotLoadedError{edge: "assets"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AIGenerationJob) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case aigenerationjob.FieldParameters:
			values[i] = new([]byte)
		case aigenerationjob.FieldID, aigenerationjob.FieldUserID, aigenerationjob.FieldSessionID, aigenerationjob.FieldPromptTemplateID, aigenerationjob.FieldImageCount, aigenerationjob.FieldSeed, aigenerationjob.FieldUsageLogID, aigenerationjob.FieldAPIKeyID, aigenerationjob.FieldGroupID:
			values[i] = new(sql.NullInt64)
		case aigenerationjob.FieldStatus, aigenerationjob.FieldModel, aigenerationjob.FieldPrompt, aigenerationjob.FieldNegativePrompt, aigenerationjob.FieldSize, aigenerationjob.FieldErrorMessage, aigenerationjob.FieldRequestID:
			values[i] = new(sql.NullString)
		case aigenerationjob.FieldCreatedAt, aigenerationjob.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AIGenerationJob fields.
func (_m *AIGenerationJob) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case aigenerationjob.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case aigenerationjob.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case aigenerationjob.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case aigenerationjob.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case aigenerationjob.FieldSessionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value.Valid {
				_m.SessionID = new(int64)
				*_m.SessionID = value.Int64
			}
		case aigenerationjob.FieldPromptTemplateID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field prompt_template_id", values[i])
			} else if value.Valid {
				_m.PromptTemplateID = new(int64)
				*_m.PromptTemplateID = value.Int64
			}
		case aigenerationjob.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case aigenerationjob.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case aigenerationjob.FieldPrompt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prompt", values[i])
			} else if value.Valid {
				_m.Prompt = value.String
			}
		case aigenerationjob.FieldNegativePrompt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field negative_prompt", values[i])
			} else if value.Valid {
				_m.NegativePrompt = new(string)
				*_m.NegativePrompt = value.String
			}
		case aigenerationjob.FieldSize:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field size", values[i])
			} else if value.Valid {
				_m.Size = new(string)
				*_m.Size = value.String
			}
		case aigenerationjob.FieldImageCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field image_count", values[i])
			} else if value.Valid {
				_m.ImageCount = int(value.Int64)
			}
		case aigenerationjob.FieldSeed:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field seed", values[i])
			} else if value.Valid {
				_m.Seed = new(int64)
				*_m.Seed = value.Int64
			}
		case aigenerationjob.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		case aigenerationjob.FieldParameters:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field parameters", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Parameters); err != nil {
					return fmt.Errorf("unmarshal field parameters: %w", err)
				}
			}
		case aigenerationjob.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = new(string)
				*_m.RequestID = value.String
			}
		case aigenerationjob.FieldUsageLogID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field usage_log_id", values[i])
			} else if value.Valid {
				_m.UsageLogID = new(int64)
				*_m.UsageLogID = value.Int64
			}
		case aigenerationjob.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = new(int64)
				*_m.APIKeyID = value.Int64
			}
		case aigenerationjob.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = new(int64)
				*_m.GroupID = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AIGenerationJob.
// This includes values selected through modifiers, order, etc.
func (_m *AIGenerationJob) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySession queries the "session" edge of the AIGenerationJob entity.
func (_m *AIGenerationJob) QuerySession() *AISessionQuery {
	return NewAIGenerationJobClient(_m.config).QuerySession(_m)
}

// QueryPromptTemplate queries the "prompt_template" edge of the AIGenerationJob entity.
func (_m *AIGenerationJob) QueryPromptTemplate() *AIPromptTemplateQuery {
	return NewAIGenerationJobClient(_m.config).QueryPromptTemplate(_m)
}

// QueryAssets queries the "assets" edge of the AIGenerationJob entity.
func (_m *AIGenerationJob) QueryAssets() *AIAssetQuery {
	return NewAIGenerationJobClient(_m.config).QueryAssets(_m)
}

// Update returns a builder for updating this AIGenerationJob.
// Note that you need to call AIGenerationJob.Unwrap() before calling this method if this AIGenerationJob
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AIGenerationJob) Update() *AIGenerationJobUpdateOne {
	return NewAIGenerationJobClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AIGenerationJob entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AIGenerationJob) Unwrap() *AIGenerationJob {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AIGenerationJob is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AIGenerationJob) String() string {
	var builder strings.Builder
	builder.WriteString("AIGenerationJob(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	if v := _m.SessionID; v != nil {
		builder.WriteString("session_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.PromptTemplateID; v != nil {
		builder.WriteString("prompt_template_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("prompt=")
	builder.WriteString(_m.Prompt)
	builder.WriteString(", ")
	if v := _m.NegativePrompt; v != nil {
		builder.WriteString("negative_prompt=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Size; v != nil {
		builder.WriteString("size=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("image_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ImageCount))
	builder.WriteString(", ")
	if v := _m.Seed; v != nil {
		builder.WriteString("seed=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("parameters=")
	builder.WriteString(fmt.Sprintf("%v", _m.Parameters))
	builder.WriteString(", ")
	if v := _m.RequestID; v != nil {
		builder.WriteString("request_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.UsageLogID; v != nil {
		builder.WriteString("usage_log_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.APIKeyID; v != nil {
		builder.WriteString("api_key_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.GroupID; v != nil {
		builder.WriteString("group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// AIGenerationJobs is a parsable slice of AIGenerationJob.
type AIGenerationJobs []*AIGenerationJob
