// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/aiasset"
	"github.com/Wei-Shaw/sub2api/ent/aigenerationjob"
	"github.com/Wei-Shaw/sub2api/ent/aiprompttemplate"
	"github.com/Wei-Shaw/sub2api/ent/aisession"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AIGenerationJobUpdate is the builder for updating AIGenerationJob entities.
type AIGenerationJobUpdate struct {
	config
	hooks    []Hook
	mutation *AIGenerationJobMutation
}

// Where appends a list predicates to the AIGenerationJobUpdate builder.
func (_u *AIGenerationJobUpdate) Where(ps ...predicate.AIGenerationJob) *AIGenerationJobUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AIGenerationJobUpdate) SetUpdatedAt(v time.Time) *AIGenerationJobUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AIGenerationJobUpdate) SetUserID(v int64) *AIGenerationJobUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AIGenerationJobUpdate) SetNillableUserID(v *int64) *AIGenerationJobUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *AIGenerationJobUpdate) AddUserID(v int64) *AIGenerationJobUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *AIGenerationJobUpdate) SetSessionID(v int64) *AIGenerationJobUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *AIGenerationJobUpdate) SetNillableSessionID(v *int64) *AIGenerationJobUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// ClearSessionID clears the value of the "session_id" field.
func (_u *AIGenerationJobUpdate) ClearSessionID() *AIGenerationJobUpdate {
	_u.mutation.ClearSessionID()
	return _u
}

// SetPromptTemplateID sets the "prompt_template_id" field.
func (_u *AIGenerationJobUpdate) SetPromptTemplateID(v int64) *AIGenerationJobUpdate {
	_u.mutation.SetPromptTemplateID(v)
	return _u
}

// SetNillablePromptTemplateID sets the "prompt_template_id" field if the given value is not nil.
func (_u *AIGenerationJobUpdate) SetNillablePromptTemplateID(v *int64) *AIGenerationJobUpdate {
	if v != nil {
		_u.SetPromptTemplateID(*v)
	}
	return _u
}

// ClearPromptTemplateID clears the value of the "prompt_template_id" field.
func (_u *AIGenerationJobUpdate) ClearPromptTemplateID() *AIGenerationJobUpdate {
	_u.mutation.ClearPromptTemplateID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *AIGenerationJobUpdate) SetStatus(v string) *AIGenerationJobUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AIGenerationJobUpdate) SetNillableStatus(v *string) *AIGenerationJobUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *AIGenerationJobUpdate) SetModel(v string) *AIGenerationJobUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *AIGenerationJobUpdate) SetNillableModel(v *string) *AIGenerationJobUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetPrompt sets the "prompt" field.
func (_u *AIGenerationJobUpdate) SetPrompt(v string) *AIGenerationJobUpdate {
	_u.mutation.SetPrompt(v)
	return _u
}

// SetNillablePrompt sets the "prompt" field if the given value is not nil.
func (_u *AIGenerationJobUpdate) SetNillablePrompt(v *string) *AIGenerationJobUpdate {
	if v != nil {
		_u.SetPrompt(*v)
	}
	return _u
}

// SetNegativePrompt sets the "negative_prompt" field.
func (_u *AIGenerationJobUpdate) SetNegativePrompt(v string) *AIGenerationJobUpdate {
	_u.mutation.SetNegativePrompt(v)
	return _u
}

// SetNillableNegativePrompt sets the "negative_prompt" field if the given value is not nil.
func (_u *AIGenerationJobUpdate) SetNillableNegativePrompt(v *string) *AIGenerationJobUpdate {
	if v != nil {
		_u.SetNegativePrompt(*v)
	}
	return _u
}

// ClearNegativePrompt clears the value of the "negative_prompt" field.
func (_u *AIGenerationJobUpdate) ClearNegativePrompt() *AIGenerationJobUpdate {
	_u.mutation.ClearNegativePrompt()
	return _u
}

// SetSize sets the "size" field.
func (_u *AIGenerationJobUpdate) SetSize(v string) *AIGenerationJobUpdate {
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *AIGenerationJobUpdate) SetNillableSize(v *string) *AIGenerationJobUpdate {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// ClearSize clears the value of the "size" field.
func (_u *AIGenerationJobUpdate) ClearSize() *AIGenerationJobUpdate {
	_u.mutation.ClearSize()
	return _u
}

// SetImageCount sets the "image_count" field.
func (_u *AIGenerationJobUpdate) SetImageCount(v int) *AIGenerationJobUpdate {
	_u.mutation.ResetImageCount()
	_u.mutation.SetImageCount(v)
	return _u
}

// SetNillableImageCount sets the "image_count" field if the given value is not nil.
func (_u *AIGenerationJobUpdate) SetNillableImageCount(v *int) *AIGenerationJobUpdate {
	if v != nil {
		_u.SetImageCount(*v)
	}
	return _u
}

// AddImageCount adds value to the "image_count" field.
func (_u *AIGenerationJobUpdate) AddImageCount(v int) *AIGenerationJobUpdate {
	_u.mutation.AddImageCount(v)
	return _u
}

// SetSeed sets the "seed" field.
func (_u *AIGenerationJobUpdate) SetSeed(v int64) *AIGenerationJobUpdate {
	_u.mutation.ResetSeed()
	_u.mutation.SetSeed(v)
	return _u
}

// SetNillableSeed sets the "seed" field if the given value is not nil.
func (_u *AIGenerationJobUpdate) SetNillableSeed(v *int64) *AIGenerationJobUpdate {
	if v != nil {
		_u.SetSeed(*v)
	}
	return _u
}

// AddSeed adds value to the "seed" field.
func (_u *AIGenerationJobUpdate) AddSeed(v int64) *AIGenerationJobUpdate {
	_u.mutation.AddSeed(v)
	return _u
}

// ClearSeed clears the value of the "seed" field.
func (_u *AIGenerationJobUpdate) ClearSeed() *AIGenerationJobUpdate {
	_u.mutation.ClearSeed()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *AIGenerationJobUpdate) SetErrorMessage(v string) *AIGenerationJobUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *AIGenerationJobUpdate) SetNillableErrorMessage(v *string) *AIGenerationJobUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *AIGenerationJobUpdate) ClearErrorMessage() *AIGenerationJobUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetParameters sets the "parameters" field.
func (_u *AIGenerationJobUpdate) SetParameters(v map[string]interface{}) *AIGenerationJobUpdate {
	_u.mutation.SetParameters(v)
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *AIGenerationJobUpdate) SetRequestID(v string) *AIGenerationJobUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *AIGenerationJobUpdate) SetNillableRequestID(v *string) *AIGenerationJobUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *AIGenerationJobUpdate) ClearRequestID() *AIGenerationJobUpdate {
	_u.mutation.ClearRequestID()
	return _u
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *AIGenerationJobUpdate) SetUsageLogID(v int64) *AIGenerationJobUpdate {
	_u.mutation.ResetUsageLogID()
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *AIGenerationJobUpdate) SetNillableUsageLogID(v *int64) *AIGenerationJobUpdate {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// AddUsageLogID adds value to the "usage_log_id" field.
func (_u *AIGenerationJobUpdate) AddUsageLogID(v int64) *AIGenerationJobUpdate {
	_u.mutation.AddUsageLogID(v)
	return _u
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (_u *AIGenerationJobUpdate) ClearUsageLogID() *AIGenerationJobUpdate {
	_u.mutation.ClearUsageLogID()
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *AIGenerationJobUpdate) SetAPIKeyID(v int64) *AIGenerationJobUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *AIGenerationJobUpdate) SetNillableAPIKeyID(v *int64) *AIGenerationJobUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *AIGenerationJobUpdate) AddAPIKeyID(v int64) *AIGenerationJobUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (_u *AIGenerationJobUpdate) ClearAPIKeyID() *AIGenerationJobUpdate {
	_u.mutation.ClearAPIKeyID()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *AIGenerationJobUpdate) SetGroupID(v int64) *AIGenerationJobUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *AIGenerationJobUpdate) SetNillableGroupID(v *int64) *AIGenerationJobUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *AIGenerationJobUpdate) AddGroupID(v int64) *AIGenerationJobUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *AIGenerationJobUpdate) ClearGroupID() *AIGenerationJobUpdate {
	_u.mutation.ClearGroupID()
	return _u
}

// SetSession sets the "session" edge to the AISession entity.
func (_u *AIGenerationJobUpdate) SetSession(v *AISession) *AIGenerationJobUpdate {
	return _u.SetSessionID(v.ID)
}

// SetPromptTemplate sets the "prompt_template" edge to the AIPromptTemplate entity.
func (_u *AIGenerationJobUpdate) SetPromptTemplate(v *AIPromptTemplate) *AIGenerationJobUpdate {
	return _u.SetPromptTemplateID(v.ID)
}

// AddAssetIDs adds the "assets" edge to the AIAsset entity by IDs.
func (_u *AIGenerationJobUpdate) AddAssetIDs(ids ...int64) *AIGenerationJobUpdate {
	_u.mutation.AddAssetIDs(ids...)
	return _u
}

// AddAssets adds the "assets" edges to the AIAsset entity.
func (_u *AIGenerationJobUpdate) AddAssets(v ...*AIAsset) *AIGenerationJobUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAssetIDs(ids...)
}

// Mutation returns the AIGenerationJobMutation object of the builder.
func (_u *AIGenerationJobUpdate) Mutation() *AIGenerationJobMutation {
	return _u.mutation
}

// ClearSession clears the "session" edge to the AISession entity.
func (_u *AIGenerationJobUpdate) ClearSession() *AIGenerationJobUpdate {
	_u.mutation.ClearSession()
	return _u
}

// ClearPromptTemplate clears the "prompt_template" edge to the AIPromptTemplate entity.
func (_u *AIGenerationJobUpdate) ClearPromptTemplate() *AIGenerationJobUpdate {
	_u.mutation.ClearPromptTemplate()
	return _u
}

// ClearAssets clears all "assets" edges to the AIAsset entity.
func (_u *AIGenerationJobUpdate) ClearAssets() *AIGenerationJobUpdate {
	_u.mutation.ClearAssets()
	return _u
}

// RemoveAssetIDs removes the "assets" edge to AIAsset entities by IDs.
func (_u *AIGenerationJobUpdate) RemoveAssetIDs(ids ...int64) *AIGenerationJobUpdate {
	_u.mutation.RemoveAssetIDs(ids...)
	return _u
}

// RemoveAssets removes "assets" edges to AIAsset entities.
func (_u *AIGenerationJobUpdate) RemoveAssets(v ...*AIAsset) *AIGenerationJobUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAssetIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AIGenerationJobUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AIGenerationJobUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AIGenerationJobUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AIGenerationJobUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AIGenerationJobUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := aigenerationjob.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AIGenerationJobUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := aigenerationjob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AIGenerationJob.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := aigenerationjob.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "AIGenerationJob.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Size(); ok {
		if err := aigenerationjob.SizeValidator(v); err != nil {
			return &ValidationError{Name: "size", err: fmt.Errorf(`ent: validator failed for field "AIGenerationJob.size": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := aigenerationjob.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "AIGenerationJob.request_id": %w`, err)}
		}
	}
	return nil
}

func (_u *AIGenerationJobUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(aigenerationjob.Table, aigenerationjob.Columns, sqlgraph.NewFieldSpec(aigenerationjob.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(aigenerationjob.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(aigenerationjob.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(aigenerationjob.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(aigenerationjob.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(aigenerationjob.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Prompt(); ok {
		_spec.SetField(aigenerationjob.FieldPrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.NegativePrompt(); ok {
		_spec.SetField(aigenerationjob.FieldNegativePrompt, field.TypeString, value)
	}
	if _u.mutation.NegativePromptCleared() {
		_spec.ClearField(aigenerationjob.FieldNegativePrompt, field.TypeString)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(aigenerationjob.FieldSize, field.TypeString, value)
	}
	if _u.mutation.SizeCleared() {
		_spec.ClearField(aigenerationjob.FieldSize, field.TypeString)
	}
	if value, ok := _u.mutation.ImageCount(); ok {
		_spec.SetField(aigenerationjob.FieldImageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedImageCount(); ok {
		_spec.AddField(aigenerationjob.FieldImageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Seed(); ok {
		_spec.SetField(aigenerationjob.FieldSeed, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSeed(); ok {
		_spec.AddField(aigenerationjob.FieldSeed, field.TypeInt64, value)
	}
	if _u.mutation.SeedCleared() {
		_spec.ClearField(aigenerationjob.FieldSeed, field.TypeInt64)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(aigenerationjob.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(aigenerationjob.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.Parameters(); ok {
		_spec.SetField(aigenerationjob.FieldParameters, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(aigenerationjob.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(aigenerationjob.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.UsageLogID(); ok {
		_spec.SetField(aigenerationjob.FieldUsageLogID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsageLogID(); ok {
		_spec.AddField(aigenerationjob.FieldUsageLogID, field.TypeInt64, value)
	}
	if _u.mutation.UsageLogIDCleared() {
		_spec.ClearField(aigenerationjob.FieldUsageLogID, field.TypeInt64)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(aigenerationjob.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(aigenerationjob.FieldAPIKeyID, field.TypeInt64, value)
	}
	if _u.mutation.APIKeyIDCleared() {
		_spec.ClearField(aigenerationjob.FieldAPIKeyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(aigenerationjob.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(aigenerationjob.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(aigenerationjob.FieldGroupID, field.TypeInt64)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aigenerationjob.SessionTable,
			Columns: []string{aigenerationjob.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aisession.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aigenerationjob.SessionTable,
			Columns: []string{aigenerationjob.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aisession.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PromptTemplateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aigenerationjob.PromptTemplateTable,
			Columns: []string{aigenerationjob.PromptTemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aiprompttemplate.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PromptTemplateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aigenerationjob.PromptTemplateTable,
			Columns: []string{aigenerationjob.PromptTemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aiprompttemplate.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aigenerationjob.AssetsTable,
			Columns: []string{aigenerationjob.AssetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aiasset.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAssetsIDs(); len(nodes) > 0 && !_u.mutation.AssetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aigenerationjob.AssetsTable,
			Columns: []string{aigenerationjob.AssetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aiasset.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aigenerationjob.AssetsTable,
			Columns: []string{aigenerationjob.AssetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aiasset.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{aigenerationjob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AIGenerationJobUpdateOne is the builder for updating a single AIGenerationJob entity.
type AIGenerationJobUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AIGenerationJobMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AIGenerationJobUpdateOne) SetUpdatedAt(v time.Time) *AIGenerationJobUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AIGenerationJobUpdateOne) SetUserID(v int64) *AIGenerationJobUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AIGenerationJobUpdateOne) SetNillableUserID(v *int64) *AIGenerationJobUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *AIGenerationJobUpdateOne) AddUserID(v int64) *AIGenerationJobUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *AIGenerationJobUpdateOne) SetSessionID(v int64) *AIGenerationJobUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *AIGenerationJobUpdateOne) SetNillableSessionID(v *int64) *AIGenerationJobUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// ClearSessionID clears the value of the "session_id" field.
func (_u *AIGenerationJobUpdateOne) ClearSessionID() *AIGenerationJobUpdateOne {
	_u.mutation.ClearSessionID()
	return _u
}

// SetPromptTemplateID sets the "prompt_template_id" field.
func (_u *AIGenerationJobUpdateOne) SetPromptTemplateID(v int64) *AIGenerationJobUpdateOne {
	_u.mutation.SetPromptTemplateID(v)
	return _u
}

// SetNillablePromptTemplateID sets the "prompt_template_id" field if the given value is not nil.
func (_u *AIGenerationJobUpdateOne) SetNillablePromptTemplateID(v *int64) *AIGenerationJobUpdateOne {
	if v != nil {
		_u.SetPromptTemplateID(*v)
	}
	return _u
}

// ClearPromptTemplateID clears the value of the "prompt_template_id" field.
func (_u *AIGenerationJobUpdateOne) ClearPromptTemplateID() *AIGenerationJobUpdateOne {
	_u.mutation.ClearPromptTemplateID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *AIGenerationJobUpdateOne) SetStatus(v string) *AIGenerationJobUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AIGenerationJobUpdateOne) SetNillableStatus(v *string) *AIGenerationJobUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *AIGenerationJobUpdateOne) SetModel(v string) *AIGenerationJobUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *AIGenerationJobUpdateOne) SetNillableModel(v *string) *AIGenerationJobUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetPrompt sets the "prompt" field.
func (_u *AIGenerationJobUpdateOne) SetPrompt(v string) *AIGenerationJobUpdateOne {
	_u.mutation.SetPrompt(v)
	return _u
}

// SetNillablePrompt sets the "prompt" field if the given value is not nil.
func (_u *AIGenerationJobUpdateOne) SetNillablePrompt(v *string) *AIGenerationJobUpdateOne {
	if v != nil {
		_u.SetPrompt(*v)
	}
	return _u
}

// SetNegativePrompt sets the "negative_prompt" field.
func (_u *AIGenerationJobUpdateOne) SetNegativePrompt(v string) *AIGenerationJobUpdateOne {
	_u.mutation.SetNegativePrompt(v)
	return _u
}

// SetNillableNegativePrompt sets the "negative_prompt" field if the given value is not nil.
func (_u *AIGenerationJobUpdateOne) SetNillableNegativePrompt(v *string) *AIGenerationJobUpdateOne {
	if v != nil {
		_u.SetNegativePrompt(*v)
	}
	return _u
}

// ClearNegativePrompt clears the value of the "negative_prompt" field.
func (_u *AIGenerationJobUpdateOne) ClearNegativePrompt() *AIGenerationJobUpdateOne {
	_u.mutation.ClearNegativePrompt()
	return _u
}

// SetSize sets the "size" field.
func (_u *AIGenerationJobUpdateOne) SetSize(v string) *AIGenerationJobUpdateOne {
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *AIGenerationJobUpdateOne) SetNillableSize(v *string) *AIGenerationJobUpdateOne {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// ClearSize clears the value of the "size" field.
func (_u *AIGenerationJobUpdateOne) ClearSize() *AIGenerationJobUpdateOne {
	_u.mutation.ClearSize()
	return _u
}

// SetImageCount sets the "image_count" field.
func (_u *AIGenerationJobUpdateOne) SetImageCount(v int) *AIGenerationJobUpdateOne {
	_u.mutation.ResetImageCount()
	_u.mutation.SetImageCount(v)
	return _u
}

// SetNillableImageCount sets the "image_count" field if the given value is not nil.
func (_u *AIGenerationJobUpdateOne) SetNillableImageCount(v *int) *AIGenerationJobUpdateOne {
	if v != nil {
		_u.SetImageCount(*v)
	}
	return _u
}

// AddImageCount adds value to the "image_count" field.
func (_u *AIGenerationJobUpdateOne) AddImageCount(v int) *AIGenerationJobUpdateOne {
	_u.mutation.AddImageCount(v)
	return _u
}

// SetSeed sets the "seed" field.
func (_u *AIGenerationJobUpdateOne) SetSeed(v int64) *AIGenerationJobUpdateOne {
	_u.mutation.ResetSeed()
	_u.mutation.SetSeed(v)
	return _u
}

// SetNillableSeed sets the "seed" field if the given value is not nil.
func (_u *AIGenerationJobUpdateOne) SetNillableSeed(v *int64) *AIGenerationJobUpdateOne {
	if v != nil {
		_u.SetSeed(*v)
	}
	return _u
}

// AddSeed adds value to the "seed" field.
func (_u *AIGenerationJobUpdateOne) AddSeed(v int64) *AIGenerationJobUpdateOne {
	_u.mutation.AddSeed(v)
	return _u
}

// ClearSeed clears the value of the "seed" field.
func (_u *AIGenerationJobUpdateOne) ClearSeed() *AIGenerationJobUpdateOne {
	_u.mutation.ClearSeed()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *AIGenerationJobUpdateOne) SetErrorMessage(v string) *AIGenerationJobUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *AIGenerationJobUpdateOne) SetNillableErrorMessage(v *string) *AIGenerationJobUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *AIGenerationJobUpdateOne) ClearErrorMessage() *AIGenerationJobUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetParameters sets the "parameters" field.
func (_u *AIGenerationJobUpdateOne) SetParameters(v map[string]interface{}) *AIGenerationJobUpdateOne {
	_u.mutation.SetParameters(v)
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *AIGenerationJobUpdateOne) SetRequestID(v string) *AIGenerationJobUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *AIGenerationJobUpdateOne) SetNillableRequestID(v *string) *AIGenerationJobUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *AIGenerationJobUpdateOne) ClearRequestID() *AIGenerationJobUpdateOne {
	_u.mutation.ClearRequestID()
	return _u
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *AIGenerationJobUpdateOne) SetUsageLogID(v int64) *AIGenerationJobUpdateOne {
	_u.mutation.ResetUsageLogID()
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *AIGenerationJobUpdateOne) SetNillableUsageLogID(v *int64) *AIGenerationJobUpdateOne {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// AddUsageLogID adds value to the "usage_log_id" field.
func (_u *AIGenerationJobUpdateOne) AddUsageLogID(v int64) *AIGenerationJobUpdateOne {
	_u.mutation.AddUsageLogID(v)
	return _u
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (_u *AIGenerationJobUpdateOne) ClearUsageLogID() *AIGenerationJobUpdateOne {
	_u.mutation.ClearUsageLogID()
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *AIGenerationJobUpdateOne) SetAPIKeyID(v int64) *AIGenerationJobUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *AIGenerationJobUpdateOne) SetNillableAPIKeyID(v *int64) *AIGenerationJobUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *AIGenerationJobUpdateOne) AddAPIKeyID(v int64) *AIGenerationJobUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (_u *AIGenerationJobUpdateOne) ClearAPIKeyID() *AIGenerationJobUpdateOne {
	_u.mutation.ClearAPIKeyID()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *AIGenerationJobUpdateOne) SetGroupID(v int64) *AIGenerationJobUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *AIGenerationJobUpdateOne) SetNillableGroupID(v *int64) *AIGenerationJobUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *AIGenerationJobUpdateOne) AddGroupID(v int64) *AIGenerationJobUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *AIGenerationJobUpdateOne) ClearGroupID() *AIGenerationJobUpdateOne {
	_u.mutation.ClearGroupID()
	return _u
}

// SetSession sets the "session" edge to the AISession entity.
func (_u *AIGenerationJobUpdateOne) SetSession(v *AISession) *AIGenerationJobUpdateOne {
	return _u.SetSessionID(v.ID)
}

// SetPromptTemplate sets the "prompt_template" edge to the AIPromptTemplate entity.
func (_u *AIGenerationJobUpdateOne) SetPromptTemplate(v *AIPromptTemplate) *AIGenerationJobUpdateOne {
	return _u.SetPromptTemplateID(v.ID)
}

// AddAssetIDs adds the "assets" edge to the AIAsset entity by IDs.
func (_u *AIGenerationJobUpdateOne) AddAssetIDs(ids ...int64) *AIGenerationJobUpdateOne {
	_u.mutation.AddAssetIDs(ids...)
	return _u
}

// AddAssets adds the "assets" edges to the AIAsset entity.
func (_u *AIGenerationJobUpdateOne) AddAssets(v ...*AIAsset) *AIGenerationJobUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAssetIDs(ids...)
}

// Mutation returns the AIGenerationJobMutation object of the builder.
func (_u *AIGenerationJobUpdateOne) Mutation() *AIGenerationJobMutation {
	return _u.mutation
}

// ClearSession clears the "session" edge to the AISession entity.
func (_u *AIGenerationJobUpdateOne) ClearSession() *AIGenerationJobUpdateOne {
	_u.mutation.ClearSession()
	return _u
}

// ClearPromptTemplate clears the "prompt_template" edge to the AIPromptTemplate entity.
func (_u *AIGenerationJobUpdateOne) ClearPromptTemplate() *AIGenerationJobUpdateOne {
	_u.mutation.ClearPromptTemplate()
	return _u
}

// ClearAssets clears all "assets" edges to the AIAsset entity.
func (_u *AIGenerationJobUpdateOne) ClearAssets() *AIGenerationJobUpdateOne {
	_u.mutation.ClearAssets()
	return _u
}

// RemoveAssetIDs removes the "assets" edge to AIAsset entities by IDs.
func (_u *AIGenerationJobUpdateOne) RemoveAssetIDs(ids ...int64) *AIGenerationJobUpdateOne {
	_u.mutation.RemoveAssetIDs(ids...)
	return _u
}

// RemoveAssets removes "assets" edges to AIAsset entities.
func (_u *AIGenerationJobUpdateOne) RemoveAssets(v ...*AIAsset) *AIGenerationJobUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAssetIDs(ids...)
}

// Where appends a list predicates to the AIGenerationJobUpdate builder.
func (_u *AIGenerationJobUpdateOne) Where(ps ...predicate.AIGenerationJob) *AIGenerationJobUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AIGenerationJobUpdateOne) Select(field string, fields ...string) *AIGenerationJobUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AIGenerationJob entity.
func (_u *AIGenerationJobUpdateOne) Save(ctx context.Context) (*AIGenerationJob, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AIGenerationJobUpdateOne) SaveX(ctx context.Context) *AIGenerationJob {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AIGenerationJobUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AIGenerationJobUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AIGenerationJobUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := aigenerationjob.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AIGenerationJobUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := aigenerationjob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AIGenerationJob.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := aigenerationjob.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "AIGenerationJob.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Size(); ok {
		if err := aigenerationjob.SizeValidator(v); err != nil {
			return &ValidationError{Name: "size", err: fmt.Errorf(`ent: validator failed for field "AIGenerationJob.size": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := aigenerationjob.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "AIGenerationJob.request_id": %w`, err)}
		}
	}
	return nil
}

func (_u *AIGenerationJobUpdateOne) sqlSave(ctx context.Context) (_node *AIGenerationJob, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(aigenerationjob.Table, aigenerationjob.Columns, sqlgraph.NewFieldSpec(aigenerationjob.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AIGenerationJob.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, aigenerationjob.FieldID)
		for _, f := range fields {
			if !aigenerationjob.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != aigenerationjob.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(aigenerationjob.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(aigenerationjob.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(aigenerationjob.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(aigenerationjob.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(aigenerationjob.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Prompt(); ok {
		_spec.SetField(aigenerationjob.FieldPrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.NegativePrompt(); ok {
		_spec.SetField(aigenerationjob.FieldNegativePrompt, field.TypeString, value)
	}
	if _u.mutation.NegativePromptCleared() {
		_spec.ClearField(aigenerationjob.FieldNegativePrompt, field.TypeString)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(aigenerationjob.FieldSize, field.TypeString, value)
	}
	if _u.mutation.SizeCleared() {
		_spec.ClearField(aigenerationjob.FieldSize, field.TypeString)
	}
	if value, ok := _u.mutation.ImageCount(); ok {
		_spec.SetField(aigenerationjob.FieldImageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedImageCount(); ok {
		_spec.AddField(aigenerationjob.FieldImageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Seed(); ok {
		_spec.SetField(aigenerationjob.FieldSeed, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSeed(); ok {
		_spec.AddField(aigenerationjob.FieldSeed, field.TypeInt64, value)
	}
	if _u.mutation.SeedCleared() {
		_spec.ClearField(aigenerationjob.FieldSeed, field.TypeInt64)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(aigenerationjob.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(aigenerationjob.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.Parameters(); ok {
		_spec.SetField(aigenerationjob.FieldParameters, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(aigenerationjob.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(aigenerationjob.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.UsageLogID(); ok {
		_spec.SetField(aigenerationjob.FieldUsageLogID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsageLogID(); ok {
		_spec.AddField(aigenerationjob.FieldUsageLogID, field.TypeInt64, value)
	}
	if _u.mutation.UsageLogIDCleared() {
		_spec.ClearField(aigenerationjob.FieldUsageLogID, field.TypeInt64)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(aigenerationjob.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(aigenerationjob.FieldAPIKeyID, field.TypeInt64, value)
	}
	if _u.mutation.APIKeyIDCleared() {
		_spec.ClearField(aigenerationjob.FieldAPIKeyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(aigenerationjob.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(aigenerationjob.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(aigenerationjob.FieldGroupID, field.TypeInt64)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aigenerationjob.SessionTable,
			Columns: []string{aigenerationjob.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aisession.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aigenerationjob.SessionTable,
			Columns: []string{aigenerationjob.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aisession.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PromptTemplateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aigenerationjob.PromptTemplateTable,
			Columns: []string{aigenerationjob.PromptTemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aiprompttemplate.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PromptTemplateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aigenerationjob.PromptTemplateTable,
			Columns: []string{aigenerationjob.PromptTemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aiprompttemplate.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aigenerationjob.AssetsTable,
			Columns: []string{aigenerationjob.AssetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aiasset.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAssetsIDs(); len(nodes) > 0 && !_u.mutation.AssetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aigenerationjob.AssetsTable,
			Columns: []string{aigenerationjob.AssetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aiasset.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aigenerationjob.AssetsTable,
			Columns: []string{aigenerationjob.AssetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aiasset.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AIGenerationJob{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{aigenerationjob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
