// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/aiprompttemplate"
	"github.com/Wei-Shaw/sub2api/ent/aiprompttemplateversion"
)

// AIPromptTemplateVersion is the model entity for the AIPromptTemplateVersion schema.
type AIPromptTemplateVersion struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// TemplateID holds the value of the "template_id" field.
	TemplateID int64 `json:"template_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Version holds the value of the "version" field.
	Version int `json:"version,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// ModelHint holds the value of the "model_hint" field.
	ModelHint *string `json:"model_hint,omitempty"`
	// Variables holds the value of the "variables" field.
	Variables []map[string]interface{} `json:"variables,omitempty"`
	// ChangeNote holds the value of the "change_note" field.
	ChangeNote *string `json:"change_note,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID *string `json:"request_id,omitempty"`
	// UsageLogID holds the value of the "usage_log_id" field.
	UsageLogID *int64 `json:"usage_log_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID *int64 `json:"api_key_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID *int64 `json:"group_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AIPromptTemplateVersionQuery when eager-loading is set.
	Edges        AIPromptTemplateVersionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AIPromptTemplateVersionEdges holds the relations/edges for other nodes in the graph.
type AIPromptTemplateVersionEdges struct {
	// Template holds the value of the template edge.
	Template *AIPromptTemplate `json:"template,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TemplateOrErr returns the Template value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AIPromptTemplateVersionEdges) TemplateOrErr() (*AIPromptTemplate, error) {
	if e.Template != nil {
		return e.Template, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: aiprompttemplate.Label}
	}
	return nil, &NotLoadedError{edge: "template"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AIPromptTemplateVersion) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case aiprompttemplateversion.FieldVariables, aiprompttemplateversion.FieldMetadata:
			values[i] = new([]byte)
		case aiprompttemplateversion.FieldID, aiprompttemplateversion.FieldTemplateID, aiprompttemplateversion.FieldUserID, aiprompttemplateversion.FieldVersion, aiprompttemplateversion.FieldUsageLogID, aiprompttemplateversion.FieldAPIKeyID, aiprompttemplateversion.FieldGroupID:
			values[i] = new(sql.NullInt64)
		case aiprompttemplateversion.FieldTitle, aiprompttemplateversion.FieldContent, aiprompttemplateversion.FieldModelHint, aiprompttemplateversion.FieldChangeNote, aiprompttemplateversion.FieldRequestID:
			values[i] = new(sql.NullString)
		case aiprompttemplateversion.FieldCreatedAt, aiprompttemplateversion.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AIPromptTemplateVersion fields.
func (_m *AIPromptTemplateVersion) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case aiprompttemplateversion.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case aiprompttemplateversion.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case aiprompttemplateversion.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case aiprompttemplateversion.FieldTemplateID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field template_id", values[i])
			} else if value.Valid {
				_m.TemplateID = value.Int64
			}
		case aiprompttemplateversion.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case aiprompttemplateversion.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = int(value.Int64)
			}
		case aiprompttemplateversion.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case aiprompttemplateversion.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case aiprompttemplateversion.FieldModelHint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_hint", values[i])
			} else if value.Valid {
				_m.ModelHint = new(string)
				*_m.ModelHint = value.String
			}
		case aiprompttemplateversion.FieldVariables:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field variables", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Variables); err != nil {
					return fmt.Errorf("unmarshal field variables: %w", err)
				}
			}
		case aiprompttemplateversion.FieldChangeNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field change_note", values[i])
			} else if value.Valid {
				_m.ChangeNote = new(string)
				*_m.ChangeNote = value.String
			}
		case aiprompttemplateversion.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case aiprompttemplateversion.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = new(string)
				*_m.RequestID = value.String
			}
		case aiprompttemplateversion.FieldUsageLogID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field usage_log_id", values[i])
			} else if value.Valid {
				_m.UsageLogID = new(int64)
				*_m.UsageLogID = value.Int64
			}
		case aiprompttemplateversion.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = new(int64)
				*_m.APIKeyID = value.Int64
			}
		case aiprompttemplateversion.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = new(int64)
				*_m.GroupID = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AIPromptTemplateVersion.
// This includes values selected through modifiers, order, etc.
func (_m *AIPromptTemplateVersion) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTemplate queries the "template" edge of the AIPromptTemplateVersion entity.
func (_m *AIPromptTemplateVersion) QueryTemplate() *AIPromptTemplateQuery {
	return NewAIPromptTemplateVersionClient(_m.config).QueryTemplate(_m)
}

// Update returns a builder for updating this AIPromptTemplateVersion.
// Note that you need to call AIPromptTemplateVersion.Unwrap() before calling this method if this AIPromptTemplateVersion
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AIPromptTemplateVersion) Update() *AIPromptTemplateVersionUpdateOne {
	return NewAIPromptTemplateVersionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AIPromptTemplateVersion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AIPromptTemplateVersion) Unwrap() *AIPromptTemplateVersion {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AIPromptTemplateVersion is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AIPromptTemplateVersion) String() string {
	var builder strings.Builder
	builder.WriteString("AIPromptTemplateVersion(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("template_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TemplateID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	if v := _m.ModelHint; v != nil {
		builder.WriteString("model_hint=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("variables=")
	builder.WriteString(fmt.Sprintf("%v", _m.Variables))
	builder.WriteString(", ")
	if v := _m.ChangeNote; v != nil {
		builder.WriteString("change_note=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	if v := _m.RequestID; v != nil {
		builder.WriteString("request_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.UsageLogID; v != nil {
		builder.WriteString("usage_log_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.APIKeyID; v != nil {
		builder.WriteString("api_key_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.GroupID; v != nil {
		builder.WriteString("group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// AIPromptTemplateVersions is a parsable slice of AIPromptTemplateVersion.
type AIPromptTemplateVersions []*AIPromptTemplateVersion
