// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/aisession"
)

// AISession is the model entity for the AISession schema.
type AISession struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// SystemPrompt holds the value of the "system_prompt" field.
	SystemPrompt *string `json:"system_prompt,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// LastMessageAt holds the value of the "last_message_at" field.
	LastMessageAt *time.Time `json:"last_message_at,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID *string `json:"request_id,omitempty"`
	// UsageLogID holds the value of the "usage_log_id" field.
	UsageLogID *int64 `json:"usage_log_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID *int64 `json:"api_key_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID *int64 `json:"group_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AISessionQuery when eager-loading is set.
	Edges        AISessionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AISessionEdges holds the relations/edges for other nodes in the graph.
type AISessionEdges struct {
	// Messages holds the value of the messages edge.
	Messages []*AISessionMessage `json:"messages,omitempty"`
	// GenerationJobs holds the value of the generation_jobs edge.
	GenerationJobs []*AIGenerationJob `json:"generation_jobs,omitempty"`
	// Assets holds the value of the assets edge.
	Assets []*AIAsset `json:"assets,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// MessagesOrErr returns the Messages value or an error if the edge
// was not loaded in eager-loading.
func (e AISessionEdges) MessagesOrErr() ([]*AISessionMessage, error) {
	if e.loadedTypes[0] {
		return e.Messages, nil
	}
	return nil, &NotLoadedError{edge: "messages"}
}

// GenerationJobsOrErr returns the GenerationJobs value or an error if the edge
// was not loaded in eager-loading.
func (e AISessionEdges) GenerationJobsOrErr() ([]*AIGenerationJob, error) {
	if e.loadedTypes[1] {
		return e.GenerationJobs, nil
	}
	return nil, &NotLoadedError{edge: "generation_jobs"}
}

// AssetsOrErr returns the Assets value or an error if the edge
// was not loaded in eager-loading.
func (e AISessionEdges) AssetsOrErr() ([]*AIAsset, error) {
	if e.loadedTypes[2] {
		return e.Assets, nil
	}
	return nil, &NotLoadedError{edge: "assets"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AISession) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case aisession.FieldMetadata:
			values[i] = new([]byte)
		case aisession.FieldID, aisession.FieldUserID, aisession.FieldUsageLogID, aisession.FieldAPIKeyID, aisession.FieldGroupID:
			values[i] = new(sql.NullInt64)
		case aisession.FieldTitle, aisession.FieldStatus, aisession.FieldSystemPrompt, aisession.FieldRequestID:
			values[i] = new(sql.NullString)
		case aisession.FieldCreatedAt, aisession.FieldUpdatedAt, aisession.FieldDeletedAt, aisession.FieldLastMessageAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AISession fields.
func (_m *AISession) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case aisession.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case aisession.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case aisession.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case aisession.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case aisession.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case aisession.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case aisession.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case aisession.FieldSystemPrompt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field system_prompt", values[i])
			} else if value.Valid {
				_m.SystemPrompt = new(string)
				*_m.SystemPrompt = value.String
			}
		case aisession.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case aisession.FieldLastMessageAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_message_at", values[i])
			} else if value.Valid {
				_m.LastMessageAt = new(time.Time)
				*_m.LastMessageAt = value.Time
			}
		case aisession.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = new(string)
				*_m.RequestID = value.String
			}
		case aisession.FieldUsageLogID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field usage_log_id", values[i])
			} else if value.Valid {
				_m.UsageLogID = new(int64)
				*_m.UsageLogID = value.Int64
			}
		case aisession.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = new(int64)
				*_m.APIKeyID = value.Int64
			}
		case aisession.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = new(int64)
				*_m.GroupID = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AISession.
// This includes values selected through modifiers, order, etc.
func (_m *AISession) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMessages queries the "messages" edge of the AISession entity.
func (_m *AISession) QueryMessages() *AISessionMessageQuery {
	return NewAISessionClient(_m.config).QueryMessages(_m)
}

// QueryGenerationJobs queries the "generation_jobs" edge of the AISession entity.
func (_m *AISession) QueryGenerationJobs() *AIGenerationJobQuery {
	return NewAISessionClient(_m.config).QueryGenerationJobs(_m)
}

// QueryAssets queries the "assets" edge of the AISession entity.
func (_m *AISession) QueryAssets() *AIAssetQuery {
	return NewAISessionClient(_m.config).QueryAssets(_m)
}

// Update returns a builder for updating this AISession.
// Note that you need to call AISession.Unwrap() before calling this method if this AISession
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AISession) Update() *AISessionUpdateOne {
	return NewAISessionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AISession entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AISession) Unwrap() *AISession {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AISession is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AISession) String() string {
	var builder strings.Builder
	builder.WriteString("AISession(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.SystemPrompt; v != nil {
		builder.WriteString("system_prompt=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	if v := _m.LastMessageAt; v != nil {
		builder.WriteString("last_message_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.RequestID; v != nil {
		builder.WriteString("request_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.UsageLogID; v != nil {
		builder.WriteString("usage_log_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.APIKeyID; v != nil {
		builder.WriteString("api_key_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.GroupID; v != nil {
		builder.WriteString("group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// AISessions is a parsable slice of AISession.
type AISessions []*AISession
