// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/aiskillversion"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AISkillVersionDelete is the builder for deleting a AISkillVersion entity.
type AISkillVersionDelete struct {
	config
	hooks    []Hook
	mutation *AISkillVersionMutation
}

// Where appends a list predicates to the AISkillVersionDelete builder.
func (_d *AISkillVersionDelete) Where(ps ...predicate.AISkillVersion) *AISkillVersionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AISkillVersionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AISkillVersionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AISkillVersionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(aiskillversion.Table, sqlgraph.NewFieldSpec(aiskillversion.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AISkillVersionDeleteOne is the builder for deleting a single AISkillVersion entity.
type AISkillVersionDeleteOne struct {
	_d *AISkillVersionDelete
}

// Where appends a list predicates to the AISkillVersionDelete builder.
func (_d *AISkillVersionDeleteOne) Where(ps ...predicate.AISkillVersion) *AISkillVersionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AISkillVersionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{aiskillversion.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AISkillVersionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
