// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json/jsontext"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/creationimagejob"
	"github.com/Wei-Shaw/sub2api/ent/creationmessage"
	"github.com/Wei-Shaw/sub2api/ent/creationsession"
)

// CreationSessionCreate is the builder for creating a CreationSession entity.
type CreationSessionCreate struct {
	config
	mutation *CreationSessionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *CreationSessionCreate) SetCreatedAt(v time.Time) *CreationSessionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CreationSessionCreate) SetNillableCreatedAt(v *time.Time) *CreationSessionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CreationSessionCreate) SetUpdatedAt(v time.Time) *CreationSessionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CreationSessionCreate) SetNillableUpdatedAt(v *time.Time) *CreationSessionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *CreationSessionCreate) SetUserID(v int64) *CreationSessionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *CreationSessionCreate) SetGroupID(v int64) *CreationSessionCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *CreationSessionCreate) SetTitle(v string) *CreationSessionCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *CreationSessionCreate) SetNillableTitle(v *string) *CreationSessionCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *CreationSessionCreate) SetModel(v string) *CreationSessionCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *CreationSessionCreate) SetNillableModel(v *string) *CreationSessionCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetMode sets the "mode" field.
func (_c *CreationSessionCreate) SetMode(v string) *CreationSessionCreate {
	_c.mutation.SetMode(v)
	return _c
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_c *CreationSessionCreate) SetNillableMode(v *string) *CreationSessionCreate {
	if v != nil {
		_c.SetMode(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *CreationSessionCreate) SetStatus(v string) *CreationSessionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *CreationSessionCreate) SetNillableStatus(v *string) *CreationSessionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *CreationSessionCreate) SetMetadata(v jsontext.Value) *CreationSessionCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// AddMessageIDs adds the "messages" edge to the CreationMessage entity by IDs.
func (_c *CreationSessionCreate) AddMessageIDs(ids ...int64) *CreationSessionCreate {
	_c.mutation.AddMessageIDs(ids...)
	return _c
}

// AddMessages adds the "messages" edges to the CreationMessage entity.
func (_c *CreationSessionCreate) AddMessages(v ...*CreationMessage) *CreationSessionCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMessageIDs(ids...)
}

// AddImageJobIDs adds the "image_jobs" edge to the CreationImageJob entity by IDs.
func (_c *CreationSessionCreate) AddImageJobIDs(ids ...int64) *CreationSessionCreate {
	_c.mutation.AddImageJobIDs(ids...)
	return _c
}

// AddImageJobs adds the "image_jobs" edges to the CreationImageJob entity.
func (_c *CreationSessionCreate) AddImageJobs(v ...*CreationImageJob) *CreationSessionCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddImageJobIDs(ids...)
}

// Mutation returns the CreationSessionMutation object of the builder.
func (_c *CreationSessionCreate) Mutation() *CreationSessionMutation {
	return _c.mutation
}

// Save creates the CreationSession in the database.
func (_c *CreationSessionCreate) Save(ctx context.Context) (*CreationSession, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CreationSessionCreate) SaveX(ctx context.Context) *CreationSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CreationSessionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CreationSessionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CreationSessionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := creationsession.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := creationsession.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Title(); !ok {
		v := creationsession.DefaultTitle
		_c.mutation.SetTitle(v)
	}
	if _, ok := _c.mutation.Model(); !ok {
		v := creationsession.DefaultModel
		_c.mutation.SetModel(v)
	}
	if _, ok := _c.mutation.Mode(); !ok {
		v := creationsession.DefaultMode
		_c.mutation.SetMode(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := creationsession.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CreationSessionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CreationSession.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CreationSession.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "CreationSession.user_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "CreationSession.group_id"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "CreationSession.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := creationsession.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "CreationSession.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "CreationSession.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := creationsession.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "CreationSession.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Mode(); !ok {
		return &ValidationError{Name: "mode", err: errors.New(`ent: missing required field "CreationSession.mode"`)}
	}
	if v, ok := _c.mutation.Mode(); ok {
		if err := creationsession.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "CreationSession.mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "CreationSession.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := creationsession.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CreationSession.status": %w`, err)}
		}
	}
	return nil
}

func (_c *CreationSessionCreate) sqlSave(ctx context.Context) (*CreationSession, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CreationSessionCreate) createSpec() (*CreationSession, *sqlgraph.CreateSpec) {
	var (
		_node = &CreationSession{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(creationsession.Table, sqlgraph.NewFieldSpec(creationsession.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(creationsession.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(creationsession.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(creationsession.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(creationsession.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(creationsession.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(creationsession.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.Mode(); ok {
		_spec.SetField(creationsession.FieldMode, field.TypeString, value)
		_node.Mode = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(creationsession.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(creationsession.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if nodes := _c.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   creationsession.MessagesTable,
			Columns: []string{creationsession.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(creationmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ImageJobsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   creationsession.ImageJobsTable,
			Columns: []string{creationsession.ImageJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(creationimagejob.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CreationSession.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CreationSessionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CreationSessionCreate) OnConflict(opts ...sql.ConflictOption) *CreationSessionUpsertOne {
	_c.conflict = opts
	return &CreationSessionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CreationSession.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CreationSessionCreate) OnConflictColumns(columns ...string) *CreationSessionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CreationSessionUpsertOne{
		create: _c,
	}
}

type (
	// CreationSessionUpsertOne is the builder for "upsert"-ing
	//  one CreationSession node.
	CreationSessionUpsertOne struct {
		create *CreationSessionCreate
	}

	// CreationSessionUpsert is the "OnConflict" setter.
	CreationSessionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *CreationSessionUpsert) SetUpdatedAt(v time.Time) *CreationSessionUpsert {
	u.Set(creationsession.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CreationSessionUpsert) UpdateUpdatedAt() *CreationSessionUpsert {
	u.SetExcluded(creationsession.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *CreationSessionUpsert) SetUserID(v int64) *CreationSessionUpsert {
	u.Set(creationsession.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CreationSessionUpsert) UpdateUserID() *CreationSessionUpsert {
	u.SetExcluded(creationsession.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *CreationSessionUpsert) AddUserID(v int64) *CreationSessionUpsert {
	u.Add(creationsession.FieldUserID, v)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *CreationSessionUpsert) SetGroupID(v int64) *CreationSessionUpsert {
	u.Set(creationsession.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *CreationSessionUpsert) UpdateGroupID() *CreationSessionUpsert {
	u.SetExcluded(creationsession.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *CreationSessionUpsert) AddGroupID(v int64) *CreationSessionUpsert {
	u.Add(creationsession.FieldGroupID, v)
	return u
}

// SetTitle sets the "title" field.
func (u *CreationSessionUpsert) SetTitle(v string) *CreationSessionUpsert {
	u.Set(creationsession.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *CreationSessionUpsert) UpdateTitle() *CreationSessionUpsert {
	u.SetExcluded(creationsession.FieldTitle)
	return u
}

// SetModel sets the "model" field.
func (u *CreationSessionUpsert) SetModel(v string) *CreationSessionUpsert {
	u.Set(creationsession.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *CreationSessionUpsert) UpdateModel() *CreationSessionUpsert {
	u.SetExcluded(creationsession.FieldModel)
	return u
}

// SetMode sets the "mode" field.
func (u *CreationSessionUpsert) SetMode(v string) *CreationSessionUpsert {
	u.Set(creationsession.FieldMode, v)
	return u
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *CreationSessionUpsert) UpdateMode() *CreationSessionUpsert {
	u.SetExcluded(creationsession.FieldMode)
	return u
}

// SetStatus sets the "status" field.
func (u *CreationSessionUpsert) SetStatus(v string) *CreationSessionUpsert {
	u.Set(creationsession.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CreationSessionUpsert) UpdateStatus() *CreationSessionUpsert {
	u.SetExcluded(creationsession.FieldStatus)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *CreationSessionUpsert) SetMetadata(v jsontext.Value) *CreationSessionUpsert {
	u.Set(creationsession.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *CreationSessionUpsert) UpdateMetadata() *CreationSessionUpsert {
	u.SetExcluded(creationsession.FieldMetadata)
	return u
}

// ClearMetadata clears the value of the "metadata" field.
func (u *CreationSessionUpsert) ClearMetadata() *CreationSessionUpsert {
	u.SetNull(creationsession.FieldMetadata)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CreationSession.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CreationSessionUpsertOne) UpdateNewValues() *CreationSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(creationsession.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CreationSession.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CreationSessionUpsertOne) Ignore() *CreationSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CreationSessionUpsertOne) DoNothing() *CreationSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CreationSessionCreate.OnConflict
// documentation for more info.
func (u *CreationSessionUpsertOne) Update(set func(*CreationSessionUpsert)) *CreationSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CreationSessionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CreationSessionUpsertOne) SetUpdatedAt(v time.Time) *CreationSessionUpsertOne {
	return u.Update(func(s *CreationSessionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CreationSessionUpsertOne) UpdateUpdatedAt() *CreationSessionUpsertOne {
	return u.Update(func(s *CreationSessionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *CreationSessionUpsertOne) SetUserID(v int64) *CreationSessionUpsertOne {
	return u.Update(func(s *CreationSessionUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *CreationSessionUpsertOne) AddUserID(v int64) *CreationSessionUpsertOne {
	return u.Update(func(s *CreationSessionUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CreationSessionUpsertOne) UpdateUserID() *CreationSessionUpsertOne {
	return u.Update(func(s *CreationSessionUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *CreationSessionUpsertOne) SetGroupID(v int64) *CreationSessionUpsertOne {
	return u.Update(func(s *CreationSessionUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *CreationSessionUpsertOne) AddGroupID(v int64) *CreationSessionUpsertOne {
	return u.Update(func(s *CreationSessionUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *CreationSessionUpsertOne) UpdateGroupID() *CreationSessionUpsertOne {
	return u.Update(func(s *CreationSessionUpsert) {
		s.UpdateGroupID()
	})
}

// SetTitle sets the "title" field.
func (u *CreationSessionUpsertOne) SetTitle(v string) *CreationSessionUpsertOne {
	return u.Update(func(s *CreationSessionUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *CreationSessionUpsertOne) UpdateTitle() *CreationSessionUpsertOne {
	return u.Update(func(s *CreationSessionUpsert) {
		s.UpdateTitle()
	})
}

// SetModel sets the "model" field.
func (u *CreationSessionUpsertOne) SetModel(v string) *CreationSessionUpsertOne {
	return u.Update(func(s *CreationSessionUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *CreationSessionUpsertOne) UpdateModel() *CreationSessionUpsertOne {
	return u.Update(func(s *CreationSessionUpsert) {
		s.UpdateModel()
	})
}

// SetMode sets the "mode" field.
func (u *CreationSessionUpsertOne) SetMode(v string) *CreationSessionUpsertOne {
	return u.Update(func(s *CreationSessionUpsert) {
		s.SetMode(v)
	})
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *CreationSessionUpsertOne) UpdateMode() *CreationSessionUpsertOne {
	return u.Update(func(s *CreationSessionUpsert) {
		s.UpdateMode()
	})
}

// SetStatus sets the "status" field.
func (u *CreationSessionUpsertOne) SetStatus(v string) *CreationSessionUpsertOne {
	return u.Update(func(s *CreationSessionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CreationSessionUpsertOne) UpdateStatus() *CreationSessionUpsertOne {
	return u.Update(func(s *CreationSessionUpsert) {
		s.UpdateStatus()
	})
}

// SetMetadata sets the "metadata" field.
func (u *CreationSessionUpsertOne) SetMetadata(v jsontext.Value) *CreationSessionUpsertOne {
	return u.Update(func(s *CreationSessionUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *CreationSessionUpsertOne) UpdateMetadata() *CreationSessionUpsertOne {
	return u.Update(func(s *CreationSessionUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *CreationSessionUpsertOne) ClearMetadata() *CreationSessionUpsertOne {
	return u.Update(func(s *CreationSessionUpsert) {
		s.ClearMetadata()
	})
}

// Exec executes the query.
func (u *CreationSessionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CreationSessionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CreationSessionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CreationSessionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CreationSessionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CreationSessionCreateBulk is the builder for creating many CreationSession entities in bulk.
type CreationSessionCreateBulk struct {
	config
	err      error
	builders []*CreationSessionCreate
	conflict []sql.ConflictOption
}

// Save creates the CreationSession entities in the database.
func (_c *CreationSessionCreateBulk) Save(ctx context.Context) ([]*CreationSession, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CreationSession, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CreationSessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CreationSessionCreateBulk) SaveX(ctx context.Context) []*CreationSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CreationSessionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CreationSessionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CreationSession.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CreationSessionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CreationSessionCreateBulk) OnConflict(opts ...sql.ConflictOption) *CreationSessionUpsertBulk {
	_c.conflict = opts
	return &CreationSessionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CreationSession.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CreationSessionCreateBulk) OnConflictColumns(columns ...string) *CreationSessionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CreationSessionUpsertBulk{
		create: _c,
	}
}

// CreationSessionUpsertBulk is the builder for "upsert"-ing
// a bulk of CreationSession nodes.
type CreationSessionUpsertBulk struct {
	create *CreationSessionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CreationSession.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CreationSessionUpsertBulk) UpdateNewValues() *CreationSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(creationsession.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CreationSession.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CreationSessionUpsertBulk) Ignore() *CreationSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CreationSessionUpsertBulk) DoNothing() *CreationSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CreationSessionCreateBulk.OnConflict
// documentation for more info.
func (u *CreationSessionUpsertBulk) Update(set func(*CreationSessionUpsert)) *CreationSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CreationSessionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CreationSessionUpsertBulk) SetUpdatedAt(v time.Time) *CreationSessionUpsertBulk {
	return u.Update(func(s *CreationSessionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CreationSessionUpsertBulk) UpdateUpdatedAt() *CreationSessionUpsertBulk {
	return u.Update(func(s *CreationSessionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *CreationSessionUpsertBulk) SetUserID(v int64) *CreationSessionUpsertBulk {
	return u.Update(func(s *CreationSessionUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *CreationSessionUpsertBulk) AddUserID(v int64) *CreationSessionUpsertBulk {
	return u.Update(func(s *CreationSessionUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CreationSessionUpsertBulk) UpdateUserID() *CreationSessionUpsertBulk {
	return u.Update(func(s *CreationSessionUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *CreationSessionUpsertBulk) SetGroupID(v int64) *CreationSessionUpsertBulk {
	return u.Update(func(s *CreationSessionUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *CreationSessionUpsertBulk) AddGroupID(v int64) *CreationSessionUpsertBulk {
	return u.Update(func(s *CreationSessionUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *CreationSessionUpsertBulk) UpdateGroupID() *CreationSessionUpsertBulk {
	return u.Update(func(s *CreationSessionUpsert) {
		s.UpdateGroupID()
	})
}

// SetTitle sets the "title" field.
func (u *CreationSessionUpsertBulk) SetTitle(v string) *CreationSessionUpsertBulk {
	return u.Update(func(s *CreationSessionUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *CreationSessionUpsertBulk) UpdateTitle() *CreationSessionUpsertBulk {
	return u.Update(func(s *CreationSessionUpsert) {
		s.UpdateTitle()
	})
}

// SetModel sets the "model" field.
func (u *CreationSessionUpsertBulk) SetModel(v string) *CreationSessionUpsertBulk {
	return u.Update(func(s *CreationSessionUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *CreationSessionUpsertBulk) UpdateModel() *CreationSessionUpsertBulk {
	return u.Update(func(s *CreationSessionUpsert) {
		s.UpdateModel()
	})
}

// SetMode sets the "mode" field.
func (u *CreationSessionUpsertBulk) SetMode(v string) *CreationSessionUpsertBulk {
	return u.Update(func(s *CreationSessionUpsert) {
		s.SetMode(v)
	})
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *CreationSessionUpsertBulk) UpdateMode() *CreationSessionUpsertBulk {
	return u.Update(func(s *CreationSessionUpsert) {
		s.UpdateMode()
	})
}

// SetStatus sets the "status" field.
func (u *CreationSessionUpsertBulk) SetStatus(v string) *CreationSessionUpsertBulk {
	return u.Update(func(s *CreationSessionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CreationSessionUpsertBulk) UpdateStatus() *CreationSessionUpsertBulk {
	return u.Update(func(s *CreationSessionUpsert) {
		s.UpdateStatus()
	})
}

// SetMetadata sets the "metadata" field.
func (u *CreationSessionUpsertBulk) SetMetadata(v jsontext.Value) *CreationSessionUpsertBulk {
	return u.Update(func(s *CreationSessionUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *CreationSessionUpsertBulk) UpdateMetadata() *CreationSessionUpsertBulk {
	return u.Update(func(s *CreationSessionUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *CreationSessionUpsertBulk) ClearMetadata() *CreationSessionUpsertBulk {
	return u.Update(func(s *CreationSessionUpsert) {
		s.ClearMetadata()
	})
}

// Exec executes the query.
func (u *CreationSessionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CreationSessionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CreationSessionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CreationSessionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
