// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"encoding/json/jsontext"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/creationmessage"
	"github.com/Wei-Shaw/sub2api/ent/creationsession"
)

// CreationMessage is the model entity for the CreationMessage schema.
type CreationMessage struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// SessionID holds the value of the "session_id" field.
	SessionID int64 `json:"session_id,omitempty"`
	// Role holds the value of the "role" field.
	Role string `json:"role,omitempty"`
	// Content holds the value of the "content" field.
	Content jsontext.Value `json:"content,omitempty"`
	// Model holds the value of the "model" field.
	Model *string `json:"model,omitempty"`
	// InputTokens holds the value of the "input_tokens" field.
	InputTokens *int `json:"input_tokens,omitempty"`
	// OutputTokens holds the value of the "output_tokens" field.
	OutputTokens *int `json:"output_tokens,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CreationMessageQuery when eager-loading is set.
	Edges        CreationMessageEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CreationMessageEdges holds the relations/edges for other nodes in the graph.
type CreationMessageEdges struct {
	// Session holds the value of the session edge.
	Session *CreationSession `json:"session,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SessionOrErr returns the Session value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CreationMessageEdges) SessionOrErr() (*CreationSession, error) {
	if e.Session != nil {
		return e.Session, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: creationsession.Label}
	}
	return nil, &NotLoadedError{edge: "session"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CreationMessage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case creationmessage.FieldContent:
			values[i] = new([]byte)
		case creationmessage.FieldID, creationmessage.FieldSessionID, creationmessage.FieldInputTokens, creationmessage.FieldOutputTokens:
			values[i] = new(sql.NullInt64)
		case creationmessage.FieldRole, creationmessage.FieldModel:
			values[i] = new(sql.NullString)
		case creationmessage.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CreationMessage fields.
func (_m *CreationMessage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case creationmessage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case creationmessage.FieldSessionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value.Valid {
				_m.SessionID = value.Int64
			}
		case creationmessage.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = value.String
			}
		case creationmessage.FieldContent:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Content); err != nil {
					return fmt.Errorf("unmarshal field content: %w", err)
				}
			}
		case creationmessage.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = new(string)
				*_m.Model = value.String
			}
		case creationmessage.FieldInputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field input_tokens", values[i])
			} else if value.Valid {
				_m.InputTokens = new(int)
				*_m.InputTokens = int(value.Int64)
			}
		case creationmessage.FieldOutputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field output_tokens", values[i])
			} else if value.Valid {
				_m.OutputTokens = new(int)
				*_m.OutputTokens = int(value.Int64)
			}
		case creationmessage.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CreationMessage.
// This includes values selected through modifiers, order, etc.
func (_m *CreationMessage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySession queries the "session" edge of the CreationMessage entity.
func (_m *CreationMessage) QuerySession() *CreationSessionQuery {
	return NewCreationMessageClient(_m.config).QuerySession(_m)
}

// Update returns a builder for updating this CreationMessage.
// Note that you need to call CreationMessage.Unwrap() before calling this method if this CreationMessage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CreationMessage) Update() *CreationMessageUpdateOne {
	return NewCreationMessageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CreationMessage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CreationMessage) Unwrap() *CreationMessage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CreationMessage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CreationMessage) String() string {
	var builder strings.Builder
	builder.WriteString("CreationMessage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("session_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SessionID))
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(_m.Role)
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(fmt.Sprintf("%v", _m.Content))
	builder.WriteString(", ")
	if v := _m.Model; v != nil {
		builder.WriteString("model=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.InputTokens; v != nil {
		builder.WriteString("input_tokens=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.OutputTokens; v != nil {
		builder.WriteString("output_tokens=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CreationMessages is a parsable slice of CreationMessage.
type CreationMessages []*CreationMessage
