// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoice"
	"github.com/Wei-Shaw/sub2api/ent/invoiceorder"
)

// InvoiceCreate is the builder for creating a Invoice entity.
type InvoiceCreate struct {
	config
	mutation *InvoiceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *InvoiceCreate) SetUserID(v int64) *InvoiceCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetUserEmail sets the "user_email" field.
func (_c *InvoiceCreate) SetUserEmail(v string) *InvoiceCreate {
	_c.mutation.SetUserEmail(v)
	return _c
}

// SetNillableUserEmail sets the "user_email" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableUserEmail(v *string) *InvoiceCreate {
	if v != nil {
		_c.SetUserEmail(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *InvoiceCreate) SetStatus(v string) *InvoiceCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableStatus(v *string) *InvoiceCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetUnreadByAdmin sets the "unread_by_admin" field.
func (_c *InvoiceCreate) SetUnreadByAdmin(v bool) *InvoiceCreate {
	_c.mutation.SetUnreadByAdmin(v)
	return _c
}

// SetNillableUnreadByAdmin sets the "unread_by_admin" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableUnreadByAdmin(v *bool) *InvoiceCreate {
	if v != nil {
		_c.SetUnreadByAdmin(*v)
	}
	return _c
}

// SetInvoiceAmount sets the "invoice_amount" field.
func (_c *InvoiceCreate) SetInvoiceAmount(v float64) *InvoiceCreate {
	_c.mutation.SetInvoiceAmount(v)
	return _c
}

// SetNillableInvoiceAmount sets the "invoice_amount" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableInvoiceAmount(v *float64) *InvoiceCreate {
	if v != nil {
		_c.SetInvoiceAmount(*v)
	}
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *InvoiceCreate) SetCurrency(v string) *InvoiceCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableCurrency(v *string) *InvoiceCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetOrderCount sets the "order_count" field.
func (_c *InvoiceCreate) SetOrderCount(v int) *InvoiceCreate {
	_c.mutation.SetOrderCount(v)
	return _c
}

// SetNillableOrderCount sets the "order_count" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableOrderCount(v *int) *InvoiceCreate {
	if v != nil {
		_c.SetOrderCount(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *InvoiceCreate) SetTitle(v string) *InvoiceCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetTaxNumber sets the "tax_number" field.
func (_c *InvoiceCreate) SetTaxNumber(v string) *InvoiceCreate {
	_c.mutation.SetTaxNumber(v)
	return _c
}

// SetNillableTaxNumber sets the "tax_number" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableTaxNumber(v *string) *InvoiceCreate {
	if v != nil {
		_c.SetTaxNumber(*v)
	}
	return _c
}

// SetEmail sets the "email" field.
func (_c *InvoiceCreate) SetEmail(v string) *InvoiceCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetContactName sets the "contact_name" field.
func (_c *InvoiceCreate) SetContactName(v string) *InvoiceCreate {
	_c.mutation.SetContactName(v)
	return _c
}

// SetNillableContactName sets the "contact_name" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableContactName(v *string) *InvoiceCreate {
	if v != nil {
		_c.SetContactName(*v)
	}
	return _c
}

// SetContactPhone sets the "contact_phone" field.
func (_c *InvoiceCreate) SetContactPhone(v string) *InvoiceCreate {
	_c.mutation.SetContactPhone(v)
	return _c
}

// SetNillableContactPhone sets the "contact_phone" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableContactPhone(v *string) *InvoiceCreate {
	if v != nil {
		_c.SetContactPhone(*v)
	}
	return _c
}

// SetRequestNote sets the "request_note" field.
func (_c *InvoiceCreate) SetRequestNote(v string) *InvoiceCreate {
	_c.mutation.SetRequestNote(v)
	return _c
}

// SetNillableRequestNote sets the "request_note" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableRequestNote(v *string) *InvoiceCreate {
	if v != nil {
		_c.SetRequestNote(*v)
	}
	return _c
}

// SetFileMediaID sets the "file_media_id" field.
func (_c *InvoiceCreate) SetFileMediaID(v int64) *InvoiceCreate {
	_c.mutation.SetFileMediaID(v)
	return _c
}

// SetNillableFileMediaID sets the "file_media_id" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableFileMediaID(v *int64) *InvoiceCreate {
	if v != nil {
		_c.SetFileMediaID(*v)
	}
	return _c
}

// SetFileName sets the "file_name" field.
func (_c *InvoiceCreate) SetFileName(v string) *InvoiceCreate {
	_c.mutation.SetFileName(v)
	return _c
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableFileName(v *string) *InvoiceCreate {
	if v != nil {
		_c.SetFileName(*v)
	}
	return _c
}

// SetFileMimeType sets the "file_mime_type" field.
func (_c *InvoiceCreate) SetFileMimeType(v string) *InvoiceCreate {
	_c.mutation.SetFileMimeType(v)
	return _c
}

// SetNillableFileMimeType sets the "file_mime_type" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableFileMimeType(v *string) *InvoiceCreate {
	if v != nil {
		_c.SetFileMimeType(*v)
	}
	return _c
}

// SetFileSizeBytes sets the "file_size_bytes" field.
func (_c *InvoiceCreate) SetFileSizeBytes(v int64) *InvoiceCreate {
	_c.mutation.SetFileSizeBytes(v)
	return _c
}

// SetNillableFileSizeBytes sets the "file_size_bytes" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableFileSizeBytes(v *int64) *InvoiceCreate {
	if v != nil {
		_c.SetFileSizeBytes(*v)
	}
	return _c
}

// SetAppliedAt sets the "applied_at" field.
func (_c *InvoiceCreate) SetAppliedAt(v time.Time) *InvoiceCreate {
	_c.mutation.SetAppliedAt(v)
	return _c
}

// SetNillableAppliedAt sets the "applied_at" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableAppliedAt(v *time.Time) *InvoiceCreate {
	if v != nil {
		_c.SetAppliedAt(*v)
	}
	return _c
}

// SetCancelledAt sets the "cancelled_at" field.
func (_c *InvoiceCreate) SetCancelledAt(v time.Time) *InvoiceCreate {
	_c.mutation.SetCancelledAt(v)
	return _c
}

// SetNillableCancelledAt sets the "cancelled_at" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableCancelledAt(v *time.Time) *InvoiceCreate {
	if v != nil {
		_c.SetCancelledAt(*v)
	}
	return _c
}

// SetIssuedAt sets the "issued_at" field.
func (_c *InvoiceCreate) SetIssuedAt(v time.Time) *InvoiceCreate {
	_c.mutation.SetIssuedAt(v)
	return _c
}

// SetNillableIssuedAt sets the "issued_at" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableIssuedAt(v *time.Time) *InvoiceCreate {
	if v != nil {
		_c.SetIssuedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *InvoiceCreate) SetCreatedAt(v time.Time) *InvoiceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableCreatedAt(v *time.Time) *InvoiceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *InvoiceCreate) SetUpdatedAt(v time.Time) *InvoiceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableUpdatedAt(v *time.Time) *InvoiceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddOrderIDs adds the "orders" edge to the InvoiceOrder entity by IDs.
func (_c *InvoiceCreate) AddOrderIDs(ids ...int64) *InvoiceCreate {
	_c.mutation.AddOrderIDs(ids...)
	return _c
}

// AddOrders adds the "orders" edges to the InvoiceOrder entity.
func (_c *InvoiceCreate) AddOrders(v ...*InvoiceOrder) *InvoiceCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOrderIDs(ids...)
}

// Mutation returns the InvoiceMutation object of the builder.
func (_c *InvoiceCreate) Mutation() *InvoiceMutation {
	return _c.mutation
}

// Save creates the Invoice in the database.
func (_c *InvoiceCreate) Save(ctx context.Context) (*Invoice, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InvoiceCreate) SaveX(ctx context.Context) *Invoice {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InvoiceCreate) defaults() {
	if _, ok := _c.mutation.UserEmail(); !ok {
		v := invoice.DefaultUserEmail
		_c.mutation.SetUserEmail(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := invoice.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.UnreadByAdmin(); !ok {
		v := invoice.DefaultUnreadByAdmin
		_c.mutation.SetUnreadByAdmin(v)
	}
	if _, ok := _c.mutation.InvoiceAmount(); !ok {
		v := invoice.DefaultInvoiceAmount
		_c.mutation.SetInvoiceAmount(v)
	}
	if _, ok := _c.mutation.Currency(); !ok {
		v := invoice.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.OrderCount(); !ok {
		v := invoice.DefaultOrderCount
		_c.mutation.SetOrderCount(v)
	}
	if _, ok := _c.mutation.TaxNumber(); !ok {
		v := invoice.DefaultTaxNumber
		_c.mutation.SetTaxNumber(v)
	}
	if _, ok := _c.mutation.ContactName(); !ok {
		v := invoice.DefaultContactName
		_c.mutation.SetContactName(v)
	}
	if _, ok := _c.mutation.ContactPhone(); !ok {
		v := invoice.DefaultContactPhone
		_c.mutation.SetContactPhone(v)
	}
	if _, ok := _c.mutation.RequestNote(); !ok {
		v := invoice.DefaultRequestNote
		_c.mutation.SetRequestNote(v)
	}
	if _, ok := _c.mutation.FileName(); !ok {
		v := invoice.DefaultFileName
		_c.mutation.SetFileName(v)
	}
	if _, ok := _c.mutation.FileMimeType(); !ok {
		v := invoice.DefaultFileMimeType
		_c.mutation.SetFileMimeType(v)
	}
	if _, ok := _c.mutation.FileSizeBytes(); !ok {
		v := invoice.DefaultFileSizeBytes
		_c.mutation.SetFileSizeBytes(v)
	}
	if _, ok := _c.mutation.AppliedAt(); !ok {
		v := invoice.DefaultAppliedAt()
		_c.mutation.SetAppliedAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := invoice.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := invoice.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InvoiceCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Invoice.user_id"`)}
	}
	if _, ok := _c.mutation.UserEmail(); !ok {
		return &ValidationError{Name: "user_email", err: errors.New(`ent: missing required field "Invoice.user_email"`)}
	}
	if v, ok := _c.mutation.UserEmail(); ok {
		if err := invoice.UserEmailValidator(v); err != nil {
			return &ValidationError{Name: "user_email", err: fmt.Errorf(`ent: validator failed for field "Invoice.user_email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Invoice.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := invoice.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Invoice.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UnreadByAdmin(); !ok {
		return &ValidationError{Name: "unread_by_admin", err: errors.New(`ent: missing required field "Invoice.unread_by_admin"`)}
	}
	if _, ok := _c.mutation.InvoiceAmount(); !ok {
		return &ValidationError{Name: "invoice_amount", err: errors.New(`ent: missing required field "Invoice.invoice_amount"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "Invoice.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := invoice.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "Invoice.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OrderCount(); !ok {
		return &ValidationError{Name: "order_count", err: errors.New(`ent: missing required field "Invoice.order_count"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Invoice.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := invoice.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Invoice.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TaxNumber(); !ok {
		return &ValidationError{Name: "tax_number", err: errors.New(`ent: missing required field "Invoice.tax_number"`)}
	}
	if v, ok := _c.mutation.TaxNumber(); ok {
		if err := invoice.TaxNumberValidator(v); err != nil {
			return &ValidationError{Name: "tax_number", err: fmt.Errorf(`ent: validator failed for field "Invoice.tax_number": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "Invoice.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := invoice.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Invoice.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContactName(); !ok {
		return &ValidationError{Name: "contact_name", err: errors.New(`ent: missing required field "Invoice.contact_name"`)}
	}
	if v, ok := _c.mutation.ContactName(); ok {
		if err := invoice.ContactNameValidator(v); err != nil {
			return &ValidationError{Name: "contact_name", err: fmt.Errorf(`ent: validator failed for field "Invoice.contact_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContactPhone(); !ok {
		return &ValidationError{Name: "contact_phone", err: errors.New(`ent: missing required field "Invoice.contact_phone"`)}
	}
	if v, ok := _c.mutation.ContactPhone(); ok {
		if err := invoice.ContactPhoneValidator(v); err != nil {
			return &ValidationError{Name: "contact_phone", err: fmt.Errorf(`ent: validator failed for field "Invoice.contact_phone": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestNote(); !ok {
		return &ValidationError{Name: "request_note", err: errors.New(`ent: missing required field "Invoice.request_note"`)}
	}
	if _, ok := _c.mutation.FileName(); !ok {
		return &ValidationError{Name: "file_name", err: errors.New(`ent: missing required field "Invoice.file_name"`)}
	}
	if v, ok := _c.mutation.FileName(); ok {
		if err := invoice.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "Invoice.file_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FileMimeType(); !ok {
		return &ValidationError{Name: "file_mime_type", err: errors.New(`ent: missing required field "Invoice.file_mime_type"`)}
	}
	if v, ok := _c.mutation.FileMimeType(); ok {
		if err := invoice.FileMimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "file_mime_type", err: fmt.Errorf(`ent: validator failed for field "Invoice.file_mime_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FileSizeBytes(); !ok {
		return &ValidationError{Name: "file_size_bytes", err: errors.New(`ent: missing required field "Invoice.file_size_bytes"`)}
	}
	if _, ok := _c.mutation.AppliedAt(); !ok {
		return &ValidationError{Name: "applied_at", err: errors.New(`ent: missing required field "Invoice.applied_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Invoice.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Invoice.updated_at"`)}
	}
	return nil
}

func (_c *InvoiceCreate) sqlSave(ctx context.Context) (*Invoice, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InvoiceCreate) createSpec() (*Invoice, *sqlgraph.CreateSpec) {
	var (
		_node = &Invoice{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(invoice.Table, sqlgraph.NewFieldSpec(invoice.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(invoice.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.UserEmail(); ok {
		_spec.SetField(invoice.FieldUserEmail, field.TypeString, value)
		_node.UserEmail = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(invoice.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.UnreadByAdmin(); ok {
		_spec.SetField(invoice.FieldUnreadByAdmin, field.TypeBool, value)
		_node.UnreadByAdmin = value
	}
	if value, ok := _c.mutation.InvoiceAmount(); ok {
		_spec.SetField(invoice.FieldInvoiceAmount, field.TypeFloat64, value)
		_node.InvoiceAmount = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(invoice.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.OrderCount(); ok {
		_spec.SetField(invoice.FieldOrderCount, field.TypeInt, value)
		_node.OrderCount = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(invoice.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.TaxNumber(); ok {
		_spec.SetField(invoice.FieldTaxNumber, field.TypeString, value)
		_node.TaxNumber = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(invoice.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.ContactName(); ok {
		_spec.SetField(invoice.FieldContactName, field.TypeString, value)
		_node.ContactName = value
	}
	if value, ok := _c.mutation.ContactPhone(); ok {
		_spec.SetField(invoice.FieldContactPhone, field.TypeString, value)
		_node.ContactPhone = value
	}
	if value, ok := _c.mutation.RequestNote(); ok {
		_spec.SetField(invoice.FieldRequestNote, field.TypeString, value)
		_node.RequestNote = value
	}
	if value, ok := _c.mutation.FileMediaID(); ok {
		_spec.SetField(invoice.FieldFileMediaID, field.TypeInt64, value)
		_node.FileMediaID = &value
	}
	if value, ok := _c.mutation.FileName(); ok {
		_spec.SetField(invoice.FieldFileName, field.TypeString, value)
		_node.FileName = value
	}
	if value, ok := _c.mutation.FileMimeType(); ok {
		_spec.SetField(invoice.FieldFileMimeType, field.TypeString, value)
		_node.FileMimeType = value
	}
	if value, ok := _c.mutation.FileSizeBytes(); ok {
		_spec.SetField(invoice.FieldFileSizeBytes, field.TypeInt64, value)
		_node.FileSizeBytes = value
	}
	if value, ok := _c.mutation.AppliedAt(); ok {
		_spec.SetField(invoice.FieldAppliedAt, field.TypeTime, value)
		_node.AppliedAt = value
	}
	if value, ok := _c.mutation.CancelledAt(); ok {
		_spec.SetField(invoice.FieldCancelledAt, field.TypeTime, value)
		_node.CancelledAt = &value
	}
	if value, ok := _c.mutation.IssuedAt(); ok {
		_spec.SetField(invoice.FieldIssuedAt, field.TypeTime, value)
		_node.IssuedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(invoice.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(invoice.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.OrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invoice.OrdersTable,
			Columns: []string{invoice.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Invoice.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceCreate) OnConflict(opts ...sql.ConflictOption) *InvoiceUpsertOne {
	_c.conflict = opts
	return &InvoiceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Invoice.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceCreate) OnConflictColumns(columns ...string) *InvoiceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceUpsertOne{
		create: _c,
	}
}

type (
	// InvoiceUpsertOne is the builder for "upsert"-ing
	//  one Invoice node.
	InvoiceUpsertOne struct {
		create *InvoiceCreate
	}

	// InvoiceUpsert is the "OnConflict" setter.
	InvoiceUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *InvoiceUpsert) SetUserID(v int64) *InvoiceUpsert {
	u.Set(invoice.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateUserID() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *InvoiceUpsert) AddUserID(v int64) *InvoiceUpsert {
	u.Add(invoice.FieldUserID, v)
	return u
}

// SetUserEmail sets the "user_email" field.
func (u *InvoiceUpsert) SetUserEmail(v string) *InvoiceUpsert {
	u.Set(invoice.FieldUserEmail, v)
	return u
}

// UpdateUserEmail sets the "user_email" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateUserEmail() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldUserEmail)
	return u
}

// SetStatus sets the "status" field.
func (u *InvoiceUpsert) SetStatus(v string) *InvoiceUpsert {
	u.Set(invoice.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateStatus() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldStatus)
	return u
}

// SetUnreadByAdmin sets the "unread_by_admin" field.
func (u *InvoiceUpsert) SetUnreadByAdmin(v bool) *InvoiceUpsert {
	u.Set(invoice.FieldUnreadByAdmin, v)
	return u
}

// UpdateUnreadByAdmin sets the "unread_by_admin" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateUnreadByAdmin() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldUnreadByAdmin)
	return u
}

// SetInvoiceAmount sets the "invoice_amount" field.
func (u *InvoiceUpsert) SetInvoiceAmount(v float64) *InvoiceUpsert {
	u.Set(invoice.FieldInvoiceAmount, v)
	return u
}

// UpdateInvoiceAmount sets the "invoice_amount" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateInvoiceAmount() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldInvoiceAmount)
	return u
}

// AddInvoiceAmount adds v to the "invoice_amount" field.
func (u *InvoiceUpsert) AddInvoiceAmount(v float64) *InvoiceUpsert {
	u.Add(invoice.FieldInvoiceAmount, v)
	return u
}

// SetCurrency sets the "currency" field.
func (u *InvoiceUpsert) SetCurrency(v string) *InvoiceUpsert {
	u.Set(invoice.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateCurrency() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldCurrency)
	return u
}

// SetOrderCount sets the "order_count" field.
func (u *InvoiceUpsert) SetOrderCount(v int) *InvoiceUpsert {
	u.Set(invoice.FieldOrderCount, v)
	return u
}

// UpdateOrderCount sets the "order_count" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateOrderCount() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldOrderCount)
	return u
}

// AddOrderCount adds v to the "order_count" field.
func (u *InvoiceUpsert) AddOrderCount(v int) *InvoiceUpsert {
	u.Add(invoice.FieldOrderCount, v)
	return u
}

// SetTitle sets the "title" field.
func (u *InvoiceUpsert) SetTitle(v string) *InvoiceUpsert {
	u.Set(invoice.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateTitle() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldTitle)
	return u
}

// SetTaxNumber sets the "tax_number" field.
func (u *InvoiceUpsert) SetTaxNumber(v string) *InvoiceUpsert {
	u.Set(invoice.FieldTaxNumber, v)
	return u
}

// UpdateTaxNumber sets the "tax_number" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateTaxNumber() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldTaxNumber)
	return u
}

// SetEmail sets the "email" field.
func (u *InvoiceUpsert) SetEmail(v string) *InvoiceUpsert {
	u.Set(invoice.FieldEmail, v)
	return u
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateEmail() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldEmail)
	return u
}

// SetContactName sets the "contact_name" field.
func (u *InvoiceUpsert) SetContactName(v string) *InvoiceUpsert {
	u.Set(invoice.FieldContactName, v)
	return u
}

// UpdateContactName sets the "contact_name" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateContactName() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldContactName)
	return u
}

// SetContactPhone sets the "contact_phone" field.
func (u *InvoiceUpsert) SetContactPhone(v string) *InvoiceUpsert {
	u.Set(invoice.FieldContactPhone, v)
	return u
}

// UpdateContactPhone sets the "contact_phone" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateContactPhone() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldContactPhone)
	return u
}

// SetRequestNote sets the "request_note" field.
func (u *InvoiceUpsert) SetRequestNote(v string) *InvoiceUpsert {
	u.Set(invoice.FieldRequestNote, v)
	return u
}

// UpdateRequestNote sets the "request_note" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateRequestNote() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldRequestNote)
	return u
}

// SetFileMediaID sets the "file_media_id" field.
func (u *InvoiceUpsert) SetFileMediaID(v int64) *InvoiceUpsert {
	u.Set(invoice.FieldFileMediaID, v)
	return u
}

// UpdateFileMediaID sets the "file_media_id" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateFileMediaID() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldFileMediaID)
	return u
}

// AddFileMediaID adds v to the "file_media_id" field.
func (u *InvoiceUpsert) AddFileMediaID(v int64) *InvoiceUpsert {
	u.Add(invoice.FieldFileMediaID, v)
	return u
}

// ClearFileMediaID clears the value of the "file_media_id" field.
func (u *InvoiceUpsert) ClearFileMediaID() *InvoiceUpsert {
	u.SetNull(invoice.FieldFileMediaID)
	return u
}

// SetFileName sets the "file_name" field.
func (u *InvoiceUpsert) SetFileName(v string) *InvoiceUpsert {
	u.Set(invoice.FieldFileName, v)
	return u
}

// UpdateFileName sets the "file_name" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateFileName() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldFileName)
	return u
}

// SetFileMimeType sets the "file_mime_type" field.
func (u *InvoiceUpsert) SetFileMimeType(v string) *InvoiceUpsert {
	u.Set(invoice.FieldFileMimeType, v)
	return u
}

// UpdateFileMimeType sets the "file_mime_type" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateFileMimeType() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldFileMimeType)
	return u
}

// SetFileSizeBytes sets the "file_size_bytes" field.
func (u *InvoiceUpsert) SetFileSizeBytes(v int64) *InvoiceUpsert {
	u.Set(invoice.FieldFileSizeBytes, v)
	return u
}

// UpdateFileSizeBytes sets the "file_size_bytes" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateFileSizeBytes() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldFileSizeBytes)
	return u
}

// AddFileSizeBytes adds v to the "file_size_bytes" field.
func (u *InvoiceUpsert) AddFileSizeBytes(v int64) *InvoiceUpsert {
	u.Add(invoice.FieldFileSizeBytes, v)
	return u
}

// SetAppliedAt sets the "applied_at" field.
func (u *InvoiceUpsert) SetAppliedAt(v time.Time) *InvoiceUpsert {
	u.Set(invoice.FieldAppliedAt, v)
	return u
}

// UpdateAppliedAt sets the "applied_at" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateAppliedAt() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldAppliedAt)
	return u
}

// SetCancelledAt sets the "cancelled_at" field.
func (u *InvoiceUpsert) SetCancelledAt(v time.Time) *InvoiceUpsert {
	u.Set(invoice.FieldCancelledAt, v)
	return u
}

// UpdateCancelledAt sets the "cancelled_at" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateCancelledAt() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldCancelledAt)
	return u
}

// ClearCancelledAt clears the value of the "cancelled_at" field.
func (u *InvoiceUpsert) ClearCancelledAt() *InvoiceUpsert {
	u.SetNull(invoice.FieldCancelledAt)
	return u
}

// SetIssuedAt sets the "issued_at" field.
func (u *InvoiceUpsert) SetIssuedAt(v time.Time) *InvoiceUpsert {
	u.Set(invoice.FieldIssuedAt, v)
	return u
}

// UpdateIssuedAt sets the "issued_at" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateIssuedAt() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldIssuedAt)
	return u
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (u *InvoiceUpsert) ClearIssuedAt() *InvoiceUpsert {
	u.SetNull(invoice.FieldIssuedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceUpsert) SetUpdatedAt(v time.Time) *InvoiceUpsert {
	u.Set(invoice.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateUpdatedAt() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Invoice.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceUpsertOne) UpdateNewValues() *InvoiceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(invoice.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Invoice.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InvoiceUpsertOne) Ignore() *InvoiceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceUpsertOne) DoNothing() *InvoiceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceCreate.OnConflict
// documentation for more info.
func (u *InvoiceUpsertOne) Update(set func(*InvoiceUpsert)) *InvoiceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *InvoiceUpsertOne) SetUserID(v int64) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *InvoiceUpsertOne) AddUserID(v int64) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateUserID() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateUserID()
	})
}

// SetUserEmail sets the "user_email" field.
func (u *InvoiceUpsertOne) SetUserEmail(v string) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetUserEmail(v)
	})
}

// UpdateUserEmail sets the "user_email" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateUserEmail() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateUserEmail()
	})
}

// SetStatus sets the "status" field.
func (u *InvoiceUpsertOne) SetStatus(v string) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateStatus() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateStatus()
	})
}

// SetUnreadByAdmin sets the "unread_by_admin" field.
func (u *InvoiceUpsertOne) SetUnreadByAdmin(v bool) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetUnreadByAdmin(v)
	})
}

// UpdateUnreadByAdmin sets the "unread_by_admin" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateUnreadByAdmin() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateUnreadByAdmin()
	})
}

// SetInvoiceAmount sets the "invoice_amount" field.
func (u *InvoiceUpsertOne) SetInvoiceAmount(v float64) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetInvoiceAmount(v)
	})
}

// AddInvoiceAmount adds v to the "invoice_amount" field.
func (u *InvoiceUpsertOne) AddInvoiceAmount(v float64) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.AddInvoiceAmount(v)
	})
}

// UpdateInvoiceAmount sets the "invoice_amount" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateInvoiceAmount() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateInvoiceAmount()
	})
}

// SetCurrency sets the "currency" field.
func (u *InvoiceUpsertOne) SetCurrency(v string) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateCurrency() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateCurrency()
	})
}

// SetOrderCount sets the "order_count" field.
func (u *InvoiceUpsertOne) SetOrderCount(v int) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetOrderCount(v)
	})
}

// AddOrderCount adds v to the "order_count" field.
func (u *InvoiceUpsertOne) AddOrderCount(v int) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.AddOrderCount(v)
	})
}

// UpdateOrderCount sets the "order_count" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateOrderCount() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateOrderCount()
	})
}

// SetTitle sets the "title" field.
func (u *InvoiceUpsertOne) SetTitle(v string) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateTitle() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateTitle()
	})
}

// SetTaxNumber sets the "tax_number" field.
func (u *InvoiceUpsertOne) SetTaxNumber(v string) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetTaxNumber(v)
	})
}

// UpdateTaxNumber sets the "tax_number" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateTaxNumber() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateTaxNumber()
	})
}

// SetEmail sets the "email" field.
func (u *InvoiceUpsertOne) SetEmail(v string) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateEmail() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateEmail()
	})
}

// SetContactName sets the "contact_name" field.
func (u *InvoiceUpsertOne) SetContactName(v string) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetContactName(v)
	})
}

// UpdateContactName sets the "contact_name" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateContactName() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateContactName()
	})
}

// SetContactPhone sets the "contact_phone" field.
func (u *InvoiceUpsertOne) SetContactPhone(v string) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetContactPhone(v)
	})
}

// UpdateContactPhone sets the "contact_phone" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateContactPhone() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateContactPhone()
	})
}

// SetRequestNote sets the "request_note" field.
func (u *InvoiceUpsertOne) SetRequestNote(v string) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetRequestNote(v)
	})
}

// UpdateRequestNote sets the "request_note" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateRequestNote() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateRequestNote()
	})
}

// SetFileMediaID sets the "file_media_id" field.
func (u *InvoiceUpsertOne) SetFileMediaID(v int64) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetFileMediaID(v)
	})
}

// AddFileMediaID adds v to the "file_media_id" field.
func (u *InvoiceUpsertOne) AddFileMediaID(v int64) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.AddFileMediaID(v)
	})
}

// UpdateFileMediaID sets the "file_media_id" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateFileMediaID() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateFileMediaID()
	})
}

// ClearFileMediaID clears the value of the "file_media_id" field.
func (u *InvoiceUpsertOne) ClearFileMediaID() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.ClearFileMediaID()
	})
}

// SetFileName sets the "file_name" field.
func (u *InvoiceUpsertOne) SetFileName(v string) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetFileName(v)
	})
}

// UpdateFileName sets the "file_name" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateFileName() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateFileName()
	})
}

// SetFileMimeType sets the "file_mime_type" field.
func (u *InvoiceUpsertOne) SetFileMimeType(v string) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetFileMimeType(v)
	})
}

// UpdateFileMimeType sets the "file_mime_type" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateFileMimeType() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateFileMimeType()
	})
}

// SetFileSizeBytes sets the "file_size_bytes" field.
func (u *InvoiceUpsertOne) SetFileSizeBytes(v int64) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetFileSizeBytes(v)
	})
}

// AddFileSizeBytes adds v to the "file_size_bytes" field.
func (u *InvoiceUpsertOne) AddFileSizeBytes(v int64) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.AddFileSizeBytes(v)
	})
}

// UpdateFileSizeBytes sets the "file_size_bytes" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateFileSizeBytes() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateFileSizeBytes()
	})
}

// SetAppliedAt sets the "applied_at" field.
func (u *InvoiceUpsertOne) SetAppliedAt(v time.Time) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetAppliedAt(v)
	})
}

// UpdateAppliedAt sets the "applied_at" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateAppliedAt() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateAppliedAt()
	})
}

// SetCancelledAt sets the "cancelled_at" field.
func (u *InvoiceUpsertOne) SetCancelledAt(v time.Time) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetCancelledAt(v)
	})
}

// UpdateCancelledAt sets the "cancelled_at" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateCancelledAt() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateCancelledAt()
	})
}

// ClearCancelledAt clears the value of the "cancelled_at" field.
func (u *InvoiceUpsertOne) ClearCancelledAt() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.ClearCancelledAt()
	})
}

// SetIssuedAt sets the "issued_at" field.
func (u *InvoiceUpsertOne) SetIssuedAt(v time.Time) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetIssuedAt(v)
	})
}

// UpdateIssuedAt sets the "issued_at" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateIssuedAt() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateIssuedAt()
	})
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (u *InvoiceUpsertOne) ClearIssuedAt() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.ClearIssuedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceUpsertOne) SetUpdatedAt(v time.Time) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateUpdatedAt() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *InvoiceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InvoiceUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InvoiceUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InvoiceCreateBulk is the builder for creating many Invoice entities in bulk.
type InvoiceCreateBulk struct {
	config
	err      error
	builders []*InvoiceCreate
	conflict []sql.ConflictOption
}

// Save creates the Invoice entities in the database.
func (_c *InvoiceCreateBulk) Save(ctx context.Context) ([]*Invoice, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Invoice, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InvoiceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InvoiceCreateBulk) SaveX(ctx context.Context) []*Invoice {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Invoice.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceCreateBulk) OnConflict(opts ...sql.ConflictOption) *InvoiceUpsertBulk {
	_c.conflict = opts
	return &InvoiceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Invoice.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceCreateBulk) OnConflictColumns(columns ...string) *InvoiceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceUpsertBulk{
		create: _c,
	}
}

// InvoiceUpsertBulk is the builder for "upsert"-ing
// a bulk of Invoice nodes.
type InvoiceUpsertBulk struct {
	create *InvoiceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Invoice.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceUpsertBulk) UpdateNewValues() *InvoiceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(invoice.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Invoice.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InvoiceUpsertBulk) Ignore() *InvoiceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceUpsertBulk) DoNothing() *InvoiceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceCreateBulk.OnConflict
// documentation for more info.
func (u *InvoiceUpsertBulk) Update(set func(*InvoiceUpsert)) *InvoiceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *InvoiceUpsertBulk) SetUserID(v int64) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *InvoiceUpsertBulk) AddUserID(v int64) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateUserID() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateUserID()
	})
}

// SetUserEmail sets the "user_email" field.
func (u *InvoiceUpsertBulk) SetUserEmail(v string) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetUserEmail(v)
	})
}

// UpdateUserEmail sets the "user_email" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateUserEmail() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateUserEmail()
	})
}

// SetStatus sets the "status" field.
func (u *InvoiceUpsertBulk) SetStatus(v string) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateStatus() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateStatus()
	})
}

// SetUnreadByAdmin sets the "unread_by_admin" field.
func (u *InvoiceUpsertBulk) SetUnreadByAdmin(v bool) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetUnreadByAdmin(v)
	})
}

// UpdateUnreadByAdmin sets the "unread_by_admin" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateUnreadByAdmin() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateUnreadByAdmin()
	})
}

// SetInvoiceAmount sets the "invoice_amount" field.
func (u *InvoiceUpsertBulk) SetInvoiceAmount(v float64) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetInvoiceAmount(v)
	})
}

// AddInvoiceAmount adds v to the "invoice_amount" field.
func (u *InvoiceUpsertBulk) AddInvoiceAmount(v float64) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.AddInvoiceAmount(v)
	})
}

// UpdateInvoiceAmount sets the "invoice_amount" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateInvoiceAmount() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateInvoiceAmount()
	})
}

// SetCurrency sets the "currency" field.
func (u *InvoiceUpsertBulk) SetCurrency(v string) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateCurrency() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateCurrency()
	})
}

// SetOrderCount sets the "order_count" field.
func (u *InvoiceUpsertBulk) SetOrderCount(v int) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetOrderCount(v)
	})
}

// AddOrderCount adds v to the "order_count" field.
func (u *InvoiceUpsertBulk) AddOrderCount(v int) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.AddOrderCount(v)
	})
}

// UpdateOrderCount sets the "order_count" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateOrderCount() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateOrderCount()
	})
}

// SetTitle sets the "title" field.
func (u *InvoiceUpsertBulk) SetTitle(v string) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateTitle() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateTitle()
	})
}

// SetTaxNumber sets the "tax_number" field.
func (u *InvoiceUpsertBulk) SetTaxNumber(v string) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetTaxNumber(v)
	})
}

// UpdateTaxNumber sets the "tax_number" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateTaxNumber() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateTaxNumber()
	})
}

// SetEmail sets the "email" field.
func (u *InvoiceUpsertBulk) SetEmail(v string) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateEmail() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateEmail()
	})
}

// SetContactName sets the "contact_name" field.
func (u *InvoiceUpsertBulk) SetContactName(v string) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetContactName(v)
	})
}

// UpdateContactName sets the "contact_name" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateContactName() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateContactName()
	})
}

// SetContactPhone sets the "contact_phone" field.
func (u *InvoiceUpsertBulk) SetContactPhone(v string) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetContactPhone(v)
	})
}

// UpdateContactPhone sets the "contact_phone" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateContactPhone() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateContactPhone()
	})
}

// SetRequestNote sets the "request_note" field.
func (u *InvoiceUpsertBulk) SetRequestNote(v string) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetRequestNote(v)
	})
}

// UpdateRequestNote sets the "request_note" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateRequestNote() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateRequestNote()
	})
}

// SetFileMediaID sets the "file_media_id" field.
func (u *InvoiceUpsertBulk) SetFileMediaID(v int64) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetFileMediaID(v)
	})
}

// AddFileMediaID adds v to the "file_media_id" field.
func (u *InvoiceUpsertBulk) AddFileMediaID(v int64) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.AddFileMediaID(v)
	})
}

// UpdateFileMediaID sets the "file_media_id" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateFileMediaID() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateFileMediaID()
	})
}

// ClearFileMediaID clears the value of the "file_media_id" field.
func (u *InvoiceUpsertBulk) ClearFileMediaID() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.ClearFileMediaID()
	})
}

// SetFileName sets the "file_name" field.
func (u *InvoiceUpsertBulk) SetFileName(v string) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetFileName(v)
	})
}

// UpdateFileName sets the "file_name" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateFileName() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateFileName()
	})
}

// SetFileMimeType sets the "file_mime_type" field.
func (u *InvoiceUpsertBulk) SetFileMimeType(v string) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetFileMimeType(v)
	})
}

// UpdateFileMimeType sets the "file_mime_type" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateFileMimeType() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateFileMimeType()
	})
}

// SetFileSizeBytes sets the "file_size_bytes" field.
func (u *InvoiceUpsertBulk) SetFileSizeBytes(v int64) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetFileSizeBytes(v)
	})
}

// AddFileSizeBytes adds v to the "file_size_bytes" field.
func (u *InvoiceUpsertBulk) AddFileSizeBytes(v int64) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.AddFileSizeBytes(v)
	})
}

// UpdateFileSizeBytes sets the "file_size_bytes" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateFileSizeBytes() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateFileSizeBytes()
	})
}

// SetAppliedAt sets the "applied_at" field.
func (u *InvoiceUpsertBulk) SetAppliedAt(v time.Time) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetAppliedAt(v)
	})
}

// UpdateAppliedAt sets the "applied_at" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateAppliedAt() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateAppliedAt()
	})
}

// SetCancelledAt sets the "cancelled_at" field.
func (u *InvoiceUpsertBulk) SetCancelledAt(v time.Time) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetCancelledAt(v)
	})
}

// UpdateCancelledAt sets the "cancelled_at" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateCancelledAt() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateCancelledAt()
	})
}

// ClearCancelledAt clears the value of the "cancelled_at" field.
func (u *InvoiceUpsertBulk) ClearCancelledAt() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.ClearCancelledAt()
	})
}

// SetIssuedAt sets the "issued_at" field.
func (u *InvoiceUpsertBulk) SetIssuedAt(v time.Time) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetIssuedAt(v)
	})
}

// UpdateIssuedAt sets the "issued_at" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateIssuedAt() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateIssuedAt()
	})
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (u *InvoiceUpsertBulk) ClearIssuedAt() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.ClearIssuedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceUpsertBulk) SetUpdatedAt(v time.Time) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateUpdatedAt() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *InvoiceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InvoiceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
