// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/opsalertrule"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// OpsAlertRuleDelete is the builder for deleting a OpsAlertRule entity.
type OpsAlertRuleDelete struct {
	config
	hooks    []Hook
	mutation *OpsAlertRuleMutation
}

// Where appends a list predicates to the OpsAlertRuleDelete builder.
func (_d *OpsAlertRuleDelete) Where(ps ...predicate.OpsAlertRule) *OpsAlertRuleDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OpsAlertRuleDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OpsAlertRuleDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OpsAlertRuleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(opsalertrule.Table, sqlgraph.NewFieldSpec(opsalertrule.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OpsAlertRuleDeleteOne is the builder for deleting a single OpsAlertRule entity.
type OpsAlertRuleDeleteOne struct {
	_d *OpsAlertRuleDelete
}

// Where appends a list predicates to the OpsAlertRuleDelete builder.
func (_d *OpsAlertRuleDeleteOne) Where(ps ...predicate.OpsAlertRule) *OpsAlertRuleDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OpsAlertRuleDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{opsalertrule.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OpsAlertRuleDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
