// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/supportticket"
)

// SupportTicket is the model entity for the SupportTicket schema.
type SupportTicket struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// TicketNo holds the value of the "ticket_no" field.
	TicketNo string `json:"ticket_no,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Category holds the value of the "category" field.
	Category string `json:"category,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CurrentFormPayload holds the value of the "current_form_payload" field.
	CurrentFormPayload json.RawMessage `json:"current_form_payload,omitempty"`
	// CurrentRevisionNo holds the value of the "current_revision_no" field.
	CurrentRevisionNo int `json:"current_revision_no,omitempty"`
	// LatestMessageAt holds the value of the "latest_message_at" field.
	LatestMessageAt time.Time `json:"latest_message_at,omitempty"`
	// LastReplyRole holds the value of the "last_reply_role" field.
	LastReplyRole string `json:"last_reply_role,omitempty"`
	// UnreadByUser holds the value of the "unread_by_user" field.
	UnreadByUser bool `json:"unread_by_user,omitempty"`
	// UnreadByAdmin holds the value of the "unread_by_admin" field.
	UnreadByAdmin bool `json:"unread_by_admin,omitempty"`
	// SubmittedAt holds the value of the "submitted_at" field.
	SubmittedAt *time.Time `json:"submitted_at,omitempty"`
	// ClosedAt holds the value of the "closed_at" field.
	ClosedAt *time.Time `json:"closed_at,omitempty"`
	// WithdrawnAt holds the value of the "withdrawn_at" field.
	WithdrawnAt *time.Time `json:"withdrawn_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SupportTicketQuery when eager-loading is set.
	Edges        SupportTicketEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SupportTicketEdges holds the relations/edges for other nodes in the graph.
type SupportTicketEdges struct {
	// Messages holds the value of the messages edge.
	Messages []*SupportTicketMessage `json:"messages,omitempty"`
	// Revisions holds the value of the revisions edge.
	Revisions []*SupportTicketRevision `json:"revisions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// MessagesOrErr returns the Messages value or an error if the edge
// was not loaded in eager-loading.
func (e SupportTicketEdges) MessagesOrErr() ([]*SupportTicketMessage, error) {
	if e.loadedTypes[0] {
		return e.Messages, nil
	}
	return nil, &NotLoadedError{edge: "messages"}
}

// RevisionsOrErr returns the Revisions value or an error if the edge
// was not loaded in eager-loading.
func (e SupportTicketEdges) RevisionsOrErr() ([]*SupportTicketRevision, error) {
	if e.loadedTypes[1] {
		return e.Revisions, nil
	}
	return nil, &NotLoadedError{edge: "revisions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SupportTicket) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case supportticket.FieldCurrentFormPayload:
			values[i] = new([]byte)
		case supportticket.FieldUnreadByUser, supportticket.FieldUnreadByAdmin:
			values[i] = new(sql.NullBool)
		case supportticket.FieldID, supportticket.FieldUserID, supportticket.FieldCurrentRevisionNo:
			values[i] = new(sql.NullInt64)
		case supportticket.FieldTicketNo, supportticket.FieldCategory, supportticket.FieldTitle, supportticket.FieldStatus, supportticket.FieldLastReplyRole:
			values[i] = new(sql.NullString)
		case supportticket.FieldLatestMessageAt, supportticket.FieldSubmittedAt, supportticket.FieldClosedAt, supportticket.FieldWithdrawnAt, supportticket.FieldCreatedAt, supportticket.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SupportTicket fields.
func (_m *SupportTicket) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case supportticket.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case supportticket.FieldTicketNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ticket_no", values[i])
			} else if value.Valid {
				_m.TicketNo = value.String
			}
		case supportticket.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case supportticket.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = value.String
			}
		case supportticket.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case supportticket.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case supportticket.FieldCurrentFormPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field current_form_payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.CurrentFormPayload); err != nil {
					return fmt.Errorf("unmarshal field current_form_payload: %w", err)
				}
			}
		case supportticket.FieldCurrentRevisionNo:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field current_revision_no", values[i])
			} else if value.Valid {
				_m.CurrentRevisionNo = int(value.Int64)
			}
		case supportticket.FieldLatestMessageAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field latest_message_at", values[i])
			} else if value.Valid {
				_m.LatestMessageAt = value.Time
			}
		case supportticket.FieldLastReplyRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_reply_role", values[i])
			} else if value.Valid {
				_m.LastReplyRole = value.String
			}
		case supportticket.FieldUnreadByUser:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field unread_by_user", values[i])
			} else if value.Valid {
				_m.UnreadByUser = value.Bool
			}
		case supportticket.FieldUnreadByAdmin:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field unread_by_admin", values[i])
			} else if value.Valid {
				_m.UnreadByAdmin = value.Bool
			}
		case supportticket.FieldSubmittedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field submitted_at", values[i])
			} else if value.Valid {
				_m.SubmittedAt = new(time.Time)
				*_m.SubmittedAt = value.Time
			}
		case supportticket.FieldClosedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field closed_at", values[i])
			} else if value.Valid {
				_m.ClosedAt = new(time.Time)
				*_m.ClosedAt = value.Time
			}
		case supportticket.FieldWithdrawnAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field withdrawn_at", values[i])
			} else if value.Valid {
				_m.WithdrawnAt = new(time.Time)
				*_m.WithdrawnAt = value.Time
			}
		case supportticket.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case supportticket.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SupportTicket.
// This includes values selected through modifiers, order, etc.
func (_m *SupportTicket) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMessages queries the "messages" edge of the SupportTicket entity.
func (_m *SupportTicket) QueryMessages() *SupportTicketMessageQuery {
	return NewSupportTicketClient(_m.config).QueryMessages(_m)
}

// QueryRevisions queries the "revisions" edge of the SupportTicket entity.
func (_m *SupportTicket) QueryRevisions() *SupportTicketRevisionQuery {
	return NewSupportTicketClient(_m.config).QueryRevisions(_m)
}

// Update returns a builder for updating this SupportTicket.
// Note that you need to call SupportTicket.Unwrap() before calling this method if this SupportTicket
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SupportTicket) Update() *SupportTicketUpdateOne {
	return NewSupportTicketClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SupportTicket entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SupportTicket) Unwrap() *SupportTicket {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SupportTicket is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SupportTicket) String() string {
	var builder strings.Builder
	builder.WriteString("SupportTicket(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("ticket_no=")
	builder.WriteString(_m.TicketNo)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(_m.Category)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("current_form_payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.CurrentFormPayload))
	builder.WriteString(", ")
	builder.WriteString("current_revision_no=")
	builder.WriteString(fmt.Sprintf("%v", _m.CurrentRevisionNo))
	builder.WriteString(", ")
	builder.WriteString("latest_message_at=")
	builder.WriteString(_m.LatestMessageAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_reply_role=")
	builder.WriteString(_m.LastReplyRole)
	builder.WriteString(", ")
	builder.WriteString("unread_by_user=")
	builder.WriteString(fmt.Sprintf("%v", _m.UnreadByUser))
	builder.WriteString(", ")
	builder.WriteString("unread_by_admin=")
	builder.WriteString(fmt.Sprintf("%v", _m.UnreadByAdmin))
	builder.WriteString(", ")
	if v := _m.SubmittedAt; v != nil {
		builder.WriteString("submitted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ClosedAt; v != nil {
		builder.WriteString("closed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.WithdrawnAt; v != nil {
		builder.WriteString("withdrawn_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SupportTickets is a parsable slice of SupportTicket.
type SupportTickets []*SupportTicket
