// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/supportticketreplytemplate"
)

// SupportTicketReplyTemplateUpdate is the builder for updating SupportTicketReplyTemplate entities.
type SupportTicketReplyTemplateUpdate struct {
	config
	hooks    []Hook
	mutation *SupportTicketReplyTemplateMutation
}

// Where appends a list predicates to the SupportTicketReplyTemplateUpdate builder.
func (_u *SupportTicketReplyTemplateUpdate) Where(ps ...predicate.SupportTicketReplyTemplate) *SupportTicketReplyTemplateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *SupportTicketReplyTemplateUpdate) SetTitle(v string) *SupportTicketReplyTemplateUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *SupportTicketReplyTemplateUpdate) SetNillableTitle(v *string) *SupportTicketReplyTemplateUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *SupportTicketReplyTemplateUpdate) SetContent(v string) *SupportTicketReplyTemplateUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *SupportTicketReplyTemplateUpdate) SetNillableContent(v *string) *SupportTicketReplyTemplateUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *SupportTicketReplyTemplateUpdate) SetSortOrder(v int) *SupportTicketReplyTemplateUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *SupportTicketReplyTemplateUpdate) SetNillableSortOrder(v *int) *SupportTicketReplyTemplateUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *SupportTicketReplyTemplateUpdate) AddSortOrder(v int) *SupportTicketReplyTemplateUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SupportTicketReplyTemplateUpdate) SetUpdatedAt(v time.Time) *SupportTicketReplyTemplateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SupportTicketReplyTemplateMutation object of the builder.
func (_u *SupportTicketReplyTemplateUpdate) Mutation() *SupportTicketReplyTemplateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SupportTicketReplyTemplateUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupportTicketReplyTemplateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SupportTicketReplyTemplateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupportTicketReplyTemplateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SupportTicketReplyTemplateUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := supportticketreplytemplate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupportTicketReplyTemplateUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := supportticketreplytemplate.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "SupportTicketReplyTemplate.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := supportticketreplytemplate.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "SupportTicketReplyTemplate.content": %w`, err)}
		}
	}
	return nil
}

func (_u *SupportTicketReplyTemplateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supportticketreplytemplate.Table, supportticketreplytemplate.Columns, sqlgraph.NewFieldSpec(supportticketreplytemplate.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(supportticketreplytemplate.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(supportticketreplytemplate.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(supportticketreplytemplate.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(supportticketreplytemplate.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(supportticketreplytemplate.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportticketreplytemplate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SupportTicketReplyTemplateUpdateOne is the builder for updating a single SupportTicketReplyTemplate entity.
type SupportTicketReplyTemplateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SupportTicketReplyTemplateMutation
}

// SetTitle sets the "title" field.
func (_u *SupportTicketReplyTemplateUpdateOne) SetTitle(v string) *SupportTicketReplyTemplateUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *SupportTicketReplyTemplateUpdateOne) SetNillableTitle(v *string) *SupportTicketReplyTemplateUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *SupportTicketReplyTemplateUpdateOne) SetContent(v string) *SupportTicketReplyTemplateUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *SupportTicketReplyTemplateUpdateOne) SetNillableContent(v *string) *SupportTicketReplyTemplateUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *SupportTicketReplyTemplateUpdateOne) SetSortOrder(v int) *SupportTicketReplyTemplateUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *SupportTicketReplyTemplateUpdateOne) SetNillableSortOrder(v *int) *SupportTicketReplyTemplateUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *SupportTicketReplyTemplateUpdateOne) AddSortOrder(v int) *SupportTicketReplyTemplateUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SupportTicketReplyTemplateUpdateOne) SetUpdatedAt(v time.Time) *SupportTicketReplyTemplateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SupportTicketReplyTemplateMutation object of the builder.
func (_u *SupportTicketReplyTemplateUpdateOne) Mutation() *SupportTicketReplyTemplateMutation {
	return _u.mutation
}

// Where appends a list predicates to the SupportTicketReplyTemplateUpdate builder.
func (_u *SupportTicketReplyTemplateUpdateOne) Where(ps ...predicate.SupportTicketReplyTemplate) *SupportTicketReplyTemplateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SupportTicketReplyTemplateUpdateOne) Select(field string, fields ...string) *SupportTicketReplyTemplateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SupportTicketReplyTemplate entity.
func (_u *SupportTicketReplyTemplateUpdateOne) Save(ctx context.Context) (*SupportTicketReplyTemplate, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupportTicketReplyTemplateUpdateOne) SaveX(ctx context.Context) *SupportTicketReplyTemplate {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SupportTicketReplyTemplateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupportTicketReplyTemplateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SupportTicketReplyTemplateUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := supportticketreplytemplate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupportTicketReplyTemplateUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := supportticketreplytemplate.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "SupportTicketReplyTemplate.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := supportticketreplytemplate.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "SupportTicketReplyTemplate.content": %w`, err)}
		}
	}
	return nil
}

func (_u *SupportTicketReplyTemplateUpdateOne) sqlSave(ctx context.Context) (_node *SupportTicketReplyTemplate, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supportticketreplytemplate.Table, supportticketreplytemplate.Columns, sqlgraph.NewFieldSpec(supportticketreplytemplate.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SupportTicketReplyTemplate.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, supportticketreplytemplate.FieldID)
		for _, f := range fields {
			if !supportticketreplytemplate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != supportticketreplytemplate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(supportticketreplytemplate.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(supportticketreplytemplate.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(supportticketreplytemplate.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(supportticketreplytemplate.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(supportticketreplytemplate.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &SupportTicketReplyTemplate{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportticketreplytemplate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
