// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/tlsfingerprintcapturetask"
)

// TLSFingerprintCaptureTaskUpdate is the builder for updating TLSFingerprintCaptureTask entities.
type TLSFingerprintCaptureTaskUpdate struct {
	config
	hooks    []Hook
	mutation *TLSFingerprintCaptureTaskMutation
}

// Where appends a list predicates to the TLSFingerprintCaptureTaskUpdate builder.
func (_u *TLSFingerprintCaptureTaskUpdate) Where(ps ...predicate.TLSFingerprintCaptureTask) *TLSFingerprintCaptureTaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TLSFingerprintCaptureTaskUpdate) SetUpdatedAt(v time.Time) *TLSFingerprintCaptureTaskUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *TLSFingerprintCaptureTaskUpdate) SetName(v string) *TLSFingerprintCaptureTaskUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TLSFingerprintCaptureTaskUpdate) SetNillableName(v *string) *TLSFingerprintCaptureTaskUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TLSFingerprintCaptureTaskUpdate) SetStatus(v string) *TLSFingerprintCaptureTaskUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TLSFingerprintCaptureTaskUpdate) SetNillableStatus(v *string) *TLSFingerprintCaptureTaskUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetToken sets the "token" field.
func (_u *TLSFingerprintCaptureTaskUpdate) SetToken(v string) *TLSFingerprintCaptureTaskUpdate {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *TLSFingerprintCaptureTaskUpdate) SetNillableToken(v *string) *TLSFingerprintCaptureTaskUpdate {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetTargets sets the "targets" field.
func (_u *TLSFingerprintCaptureTaskUpdate) SetTargets(v map[string]int) *TLSFingerprintCaptureTaskUpdate {
	_u.mutation.SetTargets(v)
	return _u
}

// SetCounts sets the "counts" field.
func (_u *TLSFingerprintCaptureTaskUpdate) SetCounts(v map[string]int) *TLSFingerprintCaptureTaskUpdate {
	_u.mutation.SetCounts(v)
	return _u
}

// SetUaKeywords sets the "ua_keywords" field.
func (_u *TLSFingerprintCaptureTaskUpdate) SetUaKeywords(v []string) *TLSFingerprintCaptureTaskUpdate {
	_u.mutation.SetUaKeywords(v)
	return _u
}

// AppendUaKeywords appends value to the "ua_keywords" field.
func (_u *TLSFingerprintCaptureTaskUpdate) AppendUaKeywords(v []string) *TLSFingerprintCaptureTaskUpdate {
	_u.mutation.AppendUaKeywords(v)
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *TLSFingerprintCaptureTaskUpdate) SetCompletedAt(v time.Time) *TLSFingerprintCaptureTaskUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *TLSFingerprintCaptureTaskUpdate) SetNillableCompletedAt(v *time.Time) *TLSFingerprintCaptureTaskUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *TLSFingerprintCaptureTaskUpdate) ClearCompletedAt() *TLSFingerprintCaptureTaskUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// Mutation returns the TLSFingerprintCaptureTaskMutation object of the builder.
func (_u *TLSFingerprintCaptureTaskUpdate) Mutation() *TLSFingerprintCaptureTaskMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TLSFingerprintCaptureTaskUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TLSFingerprintCaptureTaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TLSFingerprintCaptureTaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TLSFingerprintCaptureTaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TLSFingerprintCaptureTaskUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tlsfingerprintcapturetask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TLSFingerprintCaptureTaskUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := tlsfingerprintcapturetask.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TLSFingerprintCaptureTask.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := tlsfingerprintcapturetask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TLSFingerprintCaptureTask.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Token(); ok {
		if err := tlsfingerprintcapturetask.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "TLSFingerprintCaptureTask.token": %w`, err)}
		}
	}
	return nil
}

func (_u *TLSFingerprintCaptureTaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tlsfingerprintcapturetask.Table, tlsfingerprintcapturetask.Columns, sqlgraph.NewFieldSpec(tlsfingerprintcapturetask.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tlsfingerprintcapturetask.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tlsfingerprintcapturetask.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tlsfingerprintcapturetask.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(tlsfingerprintcapturetask.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.Targets(); ok {
		_spec.SetField(tlsfingerprintcapturetask.FieldTargets, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Counts(); ok {
		_spec.SetField(tlsfingerprintcapturetask.FieldCounts, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.UaKeywords(); ok {
		_spec.SetField(tlsfingerprintcapturetask.FieldUaKeywords, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedUaKeywords(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tlsfingerprintcapturetask.FieldUaKeywords, value)
		})
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(tlsfingerprintcapturetask.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(tlsfingerprintcapturetask.FieldCompletedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tlsfingerprintcapturetask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TLSFingerprintCaptureTaskUpdateOne is the builder for updating a single TLSFingerprintCaptureTask entity.
type TLSFingerprintCaptureTaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TLSFingerprintCaptureTaskMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TLSFingerprintCaptureTaskUpdateOne) SetUpdatedAt(v time.Time) *TLSFingerprintCaptureTaskUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *TLSFingerprintCaptureTaskUpdateOne) SetName(v string) *TLSFingerprintCaptureTaskUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TLSFingerprintCaptureTaskUpdateOne) SetNillableName(v *string) *TLSFingerprintCaptureTaskUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TLSFingerprintCaptureTaskUpdateOne) SetStatus(v string) *TLSFingerprintCaptureTaskUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TLSFingerprintCaptureTaskUpdateOne) SetNillableStatus(v *string) *TLSFingerprintCaptureTaskUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetToken sets the "token" field.
func (_u *TLSFingerprintCaptureTaskUpdateOne) SetToken(v string) *TLSFingerprintCaptureTaskUpdateOne {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *TLSFingerprintCaptureTaskUpdateOne) SetNillableToken(v *string) *TLSFingerprintCaptureTaskUpdateOne {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetTargets sets the "targets" field.
func (_u *TLSFingerprintCaptureTaskUpdateOne) SetTargets(v map[string]int) *TLSFingerprintCaptureTaskUpdateOne {
	_u.mutation.SetTargets(v)
	return _u
}

// SetCounts sets the "counts" field.
func (_u *TLSFingerprintCaptureTaskUpdateOne) SetCounts(v map[string]int) *TLSFingerprintCaptureTaskUpdateOne {
	_u.mutation.SetCounts(v)
	return _u
}

// SetUaKeywords sets the "ua_keywords" field.
func (_u *TLSFingerprintCaptureTaskUpdateOne) SetUaKeywords(v []string) *TLSFingerprintCaptureTaskUpdateOne {
	_u.mutation.SetUaKeywords(v)
	return _u
}

// AppendUaKeywords appends value to the "ua_keywords" field.
func (_u *TLSFingerprintCaptureTaskUpdateOne) AppendUaKeywords(v []string) *TLSFingerprintCaptureTaskUpdateOne {
	_u.mutation.AppendUaKeywords(v)
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *TLSFingerprintCaptureTaskUpdateOne) SetCompletedAt(v time.Time) *TLSFingerprintCaptureTaskUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *TLSFingerprintCaptureTaskUpdateOne) SetNillableCompletedAt(v *time.Time) *TLSFingerprintCaptureTaskUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *TLSFingerprintCaptureTaskUpdateOne) ClearCompletedAt() *TLSFingerprintCaptureTaskUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// Mutation returns the TLSFingerprintCaptureTaskMutation object of the builder.
func (_u *TLSFingerprintCaptureTaskUpdateOne) Mutation() *TLSFingerprintCaptureTaskMutation {
	return _u.mutation
}

// Where appends a list predicates to the TLSFingerprintCaptureTaskUpdate builder.
func (_u *TLSFingerprintCaptureTaskUpdateOne) Where(ps ...predicate.TLSFingerprintCaptureTask) *TLSFingerprintCaptureTaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TLSFingerprintCaptureTaskUpdateOne) Select(field string, fields ...string) *TLSFingerprintCaptureTaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TLSFingerprintCaptureTask entity.
func (_u *TLSFingerprintCaptureTaskUpdateOne) Save(ctx context.Context) (*TLSFingerprintCaptureTask, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TLSFingerprintCaptureTaskUpdateOne) SaveX(ctx context.Context) *TLSFingerprintCaptureTask {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TLSFingerprintCaptureTaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TLSFingerprintCaptureTaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TLSFingerprintCaptureTaskUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tlsfingerprintcapturetask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TLSFingerprintCaptureTaskUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := tlsfingerprintcapturetask.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TLSFingerprintCaptureTask.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := tlsfingerprintcapturetask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TLSFingerprintCaptureTask.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Token(); ok {
		if err := tlsfingerprintcapturetask.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "TLSFingerprintCaptureTask.token": %w`, err)}
		}
	}
	return nil
}

func (_u *TLSFingerprintCaptureTaskUpdateOne) sqlSave(ctx context.Context) (_node *TLSFingerprintCaptureTask, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tlsfingerprintcapturetask.Table, tlsfingerprintcapturetask.Columns, sqlgraph.NewFieldSpec(tlsfingerprintcapturetask.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TLSFingerprintCaptureTask.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tlsfingerprintcapturetask.FieldID)
		for _, f := range fields {
			if !tlsfingerprintcapturetask.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tlsfingerprintcapturetask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tlsfingerprintcapturetask.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tlsfingerprintcapturetask.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tlsfingerprintcapturetask.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(tlsfingerprintcapturetask.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.Targets(); ok {
		_spec.SetField(tlsfingerprintcapturetask.FieldTargets, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Counts(); ok {
		_spec.SetField(tlsfingerprintcapturetask.FieldCounts, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.UaKeywords(); ok {
		_spec.SetField(tlsfingerprintcapturetask.FieldUaKeywords, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedUaKeywords(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tlsfingerprintcapturetask.FieldUaKeywords, value)
		})
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(tlsfingerprintcapturetask.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(tlsfingerprintcapturetask.FieldCompletedAt, field.TypeTime)
	}
	_node = &TLSFingerprintCaptureTask{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tlsfingerprintcapturetask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
