// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/tlsfingerprintcapturesessionevent"
)

// TLSFingerprintCaptureSessionEventUpdate is the builder for updating TLSFingerprintCaptureSessionEvent entities.
type TLSFingerprintCaptureSessionEventUpdate struct {
	config
	hooks    []Hook
	mutation *TLSFingerprintCaptureSessionEventMutation
}

// Where appends a list predicates to the TLSFingerprintCaptureSessionEventUpdate builder.
func (_u *TLSFingerprintCaptureSessionEventUpdate) Where(ps ...predicate.TLSFingerprintCaptureSessionEvent) *TLSFingerprintCaptureSessionEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetUpdatedAt(v time.Time) *TLSFingerprintCaptureSessionEventUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetTaskID(v int64) *TLSFingerprintCaptureSessionEventUpdate {
	_u.mutation.ResetTaskID()
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetNillableTaskID(v *int64) *TLSFingerprintCaptureSessionEventUpdate {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// AddTaskID adds value to the "task_id" field.
func (_u *TLSFingerprintCaptureSessionEventUpdate) AddTaskID(v int64) *TLSFingerprintCaptureSessionEventUpdate {
	_u.mutation.AddTaskID(v)
	return _u
}

// SetSessionRef sets the "session_ref" field.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetSessionRef(v int64) *TLSFingerprintCaptureSessionEventUpdate {
	_u.mutation.ResetSessionRef()
	_u.mutation.SetSessionRef(v)
	return _u
}

// SetNillableSessionRef sets the "session_ref" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetNillableSessionRef(v *int64) *TLSFingerprintCaptureSessionEventUpdate {
	if v != nil {
		_u.SetSessionRef(*v)
	}
	return _u
}

// AddSessionRef adds value to the "session_ref" field.
func (_u *TLSFingerprintCaptureSessionEventUpdate) AddSessionRef(v int64) *TLSFingerprintCaptureSessionEventUpdate {
	_u.mutation.AddSessionRef(v)
	return _u
}

// ClearSessionRef clears the value of the "session_ref" field.
func (_u *TLSFingerprintCaptureSessionEventUpdate) ClearSessionRef() *TLSFingerprintCaptureSessionEventUpdate {
	_u.mutation.ClearSessionRef()
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetSessionID(v string) *TLSFingerprintCaptureSessionEventUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetNillableSessionID(v *string) *TLSFingerprintCaptureSessionEventUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetEventID sets the "event_id" field.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetEventID(v string) *TLSFingerprintCaptureSessionEventUpdate {
	_u.mutation.SetEventID(v)
	return _u
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetNillableEventID(v *string) *TLSFingerprintCaptureSessionEventUpdate {
	if v != nil {
		_u.SetEventID(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetPlatform(v string) *TLSFingerprintCaptureSessionEventUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetNillablePlatform(v *string) *TLSFingerprintCaptureSessionEventUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetTransport sets the "transport" field.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetTransport(v string) *TLSFingerprintCaptureSessionEventUpdate {
	_u.mutation.SetTransport(v)
	return _u
}

// SetNillableTransport sets the "transport" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetNillableTransport(v *string) *TLSFingerprintCaptureSessionEventUpdate {
	if v != nil {
		_u.SetTransport(*v)
	}
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetEventType(v string) *TLSFingerprintCaptureSessionEventUpdate {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetNillableEventType(v *string) *TLSFingerprintCaptureSessionEventUpdate {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetRequestSequence sets the "request_sequence" field.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetRequestSequence(v int) *TLSFingerprintCaptureSessionEventUpdate {
	_u.mutation.ResetRequestSequence()
	_u.mutation.SetRequestSequence(v)
	return _u
}

// SetNillableRequestSequence sets the "request_sequence" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetNillableRequestSequence(v *int) *TLSFingerprintCaptureSessionEventUpdate {
	if v != nil {
		_u.SetRequestSequence(*v)
	}
	return _u
}

// AddRequestSequence adds value to the "request_sequence" field.
func (_u *TLSFingerprintCaptureSessionEventUpdate) AddRequestSequence(v int) *TLSFingerprintCaptureSessionEventUpdate {
	_u.mutation.AddRequestSequence(v)
	return _u
}

// SetStreamID sets the "stream_id" field.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetStreamID(v string) *TLSFingerprintCaptureSessionEventUpdate {
	_u.mutation.SetStreamID(v)
	return _u
}

// SetNillableStreamID sets the "stream_id" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetNillableStreamID(v *string) *TLSFingerprintCaptureSessionEventUpdate {
	if v != nil {
		_u.SetStreamID(*v)
	}
	return _u
}

// SetRequestPath sets the "request_path" field.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetRequestPath(v string) *TLSFingerprintCaptureSessionEventUpdate {
	_u.mutation.SetRequestPath(v)
	return _u
}

// SetNillableRequestPath sets the "request_path" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetNillableRequestPath(v *string) *TLSFingerprintCaptureSessionEventUpdate {
	if v != nil {
		_u.SetRequestPath(*v)
	}
	return _u
}

// SetHTTPMethod sets the "http_method" field.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetHTTPMethod(v string) *TLSFingerprintCaptureSessionEventUpdate {
	_u.mutation.SetHTTPMethod(v)
	return _u
}

// SetNillableHTTPMethod sets the "http_method" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetNillableHTTPMethod(v *string) *TLSFingerprintCaptureSessionEventUpdate {
	if v != nil {
		_u.SetHTTPMethod(*v)
	}
	return _u
}

// SetIsWebsocket sets the "is_websocket" field.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetIsWebsocket(v bool) *TLSFingerprintCaptureSessionEventUpdate {
	_u.mutation.SetIsWebsocket(v)
	return _u
}

// SetNillableIsWebsocket sets the "is_websocket" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetNillableIsWebsocket(v *bool) *TLSFingerprintCaptureSessionEventUpdate {
	if v != nil {
		_u.SetIsWebsocket(*v)
	}
	return _u
}

// SetWebsocketProtocol sets the "websocket_protocol" field.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetWebsocketProtocol(v string) *TLSFingerprintCaptureSessionEventUpdate {
	_u.mutation.SetWebsocketProtocol(v)
	return _u
}

// SetNillableWebsocketProtocol sets the "websocket_protocol" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetNillableWebsocketProtocol(v *string) *TLSFingerprintCaptureSessionEventUpdate {
	if v != nil {
		_u.SetWebsocketProtocol(*v)
	}
	return _u
}

// SetClientType sets the "client_type" field.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetClientType(v string) *TLSFingerprintCaptureSessionEventUpdate {
	_u.mutation.SetClientType(v)
	return _u
}

// SetNillableClientType sets the "client_type" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetNillableClientType(v *string) *TLSFingerprintCaptureSessionEventUpdate {
	if v != nil {
		_u.SetClientType(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetModel(v string) *TLSFingerprintCaptureSessionEventUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetNillableModel(v *string) *TLSFingerprintCaptureSessionEventUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetRequestKind sets the "request_kind" field.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetRequestKind(v string) *TLSFingerprintCaptureSessionEventUpdate {
	_u.mutation.SetRequestKind(v)
	return _u
}

// SetNillableRequestKind sets the "request_kind" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetNillableRequestKind(v *string) *TLSFingerprintCaptureSessionEventUpdate {
	if v != nil {
		_u.SetRequestKind(*v)
	}
	return _u
}

// SetStreaming sets the "streaming" field.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetStreaming(v bool) *TLSFingerprintCaptureSessionEventUpdate {
	_u.mutation.SetStreaming(v)
	return _u
}

// SetNillableStreaming sets the "streaming" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetNillableStreaming(v *bool) *TLSFingerprintCaptureSessionEventUpdate {
	if v != nil {
		_u.SetStreaming(*v)
	}
	return _u
}

// SetResponseMode sets the "response_mode" field.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetResponseMode(v string) *TLSFingerprintCaptureSessionEventUpdate {
	_u.mutation.SetResponseMode(v)
	return _u
}

// SetNillableResponseMode sets the "response_mode" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetNillableResponseMode(v *string) *TLSFingerprintCaptureSessionEventUpdate {
	if v != nil {
		_u.SetResponseMode(*v)
	}
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetUserAgent(v string) *TLSFingerprintCaptureSessionEventUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetNillableUserAgent(v *string) *TLSFingerprintCaptureSessionEventUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// SetOriginator sets the "originator" field.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetOriginator(v string) *TLSFingerprintCaptureSessionEventUpdate {
	_u.mutation.SetOriginator(v)
	return _u
}

// SetNillableOriginator sets the "originator" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetNillableOriginator(v *string) *TLSFingerprintCaptureSessionEventUpdate {
	if v != nil {
		_u.SetOriginator(*v)
	}
	return _u
}

// SetStainlessMetadata sets the "stainless_metadata" field.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetStainlessMetadata(v map[string]interface{}) *TLSFingerprintCaptureSessionEventUpdate {
	_u.mutation.SetStainlessMetadata(v)
	return _u
}

// SetHeadersSnapshot sets the "headers_snapshot" field.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetHeadersSnapshot(v map[string]interface{}) *TLSFingerprintCaptureSessionEventUpdate {
	_u.mutation.SetHeadersSnapshot(v)
	return _u
}

// SetBodySummary sets the "body_summary" field.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetBodySummary(v string) *TLSFingerprintCaptureSessionEventUpdate {
	_u.mutation.SetBodySummary(v)
	return _u
}

// SetNillableBodySummary sets the "body_summary" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetNillableBodySummary(v *string) *TLSFingerprintCaptureSessionEventUpdate {
	if v != nil {
		_u.SetBodySummary(*v)
	}
	return _u
}

// SetEventStatus sets the "event_status" field.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetEventStatus(v string) *TLSFingerprintCaptureSessionEventUpdate {
	_u.mutation.SetEventStatus(v)
	return _u
}

// SetNillableEventStatus sets the "event_status" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetNillableEventStatus(v *string) *TLSFingerprintCaptureSessionEventUpdate {
	if v != nil {
		_u.SetEventStatus(*v)
	}
	return _u
}

// SetEventError sets the "event_error" field.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetEventError(v string) *TLSFingerprintCaptureSessionEventUpdate {
	_u.mutation.SetEventError(v)
	return _u
}

// SetNillableEventError sets the "event_error" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetNillableEventError(v *string) *TLSFingerprintCaptureSessionEventUpdate {
	if v != nil {
		_u.SetEventError(*v)
	}
	return _u
}

// SetReplayable sets the "replayable" field.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetReplayable(v bool) *TLSFingerprintCaptureSessionEventUpdate {
	_u.mutation.SetReplayable(v)
	return _u
}

// SetNillableReplayable sets the "replayable" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetNillableReplayable(v *bool) *TLSFingerprintCaptureSessionEventUpdate {
	if v != nil {
		_u.SetReplayable(*v)
	}
	return _u
}

// SetSampleID sets the "sample_id" field.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetSampleID(v int64) *TLSFingerprintCaptureSessionEventUpdate {
	_u.mutation.ResetSampleID()
	_u.mutation.SetSampleID(v)
	return _u
}

// SetNillableSampleID sets the "sample_id" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetNillableSampleID(v *int64) *TLSFingerprintCaptureSessionEventUpdate {
	if v != nil {
		_u.SetSampleID(*v)
	}
	return _u
}

// AddSampleID adds value to the "sample_id" field.
func (_u *TLSFingerprintCaptureSessionEventUpdate) AddSampleID(v int64) *TLSFingerprintCaptureSessionEventUpdate {
	_u.mutation.AddSampleID(v)
	return _u
}

// ClearSampleID clears the value of the "sample_id" field.
func (_u *TLSFingerprintCaptureSessionEventUpdate) ClearSampleID() *TLSFingerprintCaptureSessionEventUpdate {
	_u.mutation.ClearSampleID()
	return _u
}

// SetReplayHash sets the "replay_hash" field.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetReplayHash(v string) *TLSFingerprintCaptureSessionEventUpdate {
	_u.mutation.SetReplayHash(v)
	return _u
}

// SetNillableReplayHash sets the "replay_hash" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SetNillableReplayHash(v *string) *TLSFingerprintCaptureSessionEventUpdate {
	if v != nil {
		_u.SetReplayHash(*v)
	}
	return _u
}

// Mutation returns the TLSFingerprintCaptureSessionEventMutation object of the builder.
func (_u *TLSFingerprintCaptureSessionEventUpdate) Mutation() *TLSFingerprintCaptureSessionEventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TLSFingerprintCaptureSessionEventUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TLSFingerprintCaptureSessionEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TLSFingerprintCaptureSessionEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TLSFingerprintCaptureSessionEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TLSFingerprintCaptureSessionEventUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tlsfingerprintcapturesessionevent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TLSFingerprintCaptureSessionEventUpdate) check() error {
	if v, ok := _u.mutation.SessionID(); ok {
		if err := tlsfingerprintcapturesessionevent.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "TLSFingerprintCaptureSessionEvent.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EventID(); ok {
		if err := tlsfingerprintcapturesessionevent.EventIDValidator(v); err != nil {
			return &ValidationError{Name: "event_id", err: fmt.Errorf(`ent: validator failed for field "TLSFingerprintCaptureSessionEvent.event_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := tlsfingerprintcapturesessionevent.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "TLSFingerprintCaptureSessionEvent.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Transport(); ok {
		if err := tlsfingerprintcapturesessionevent.TransportValidator(v); err != nil {
			return &ValidationError{Name: "transport", err: fmt.Errorf(`ent: validator failed for field "TLSFingerprintCaptureSessionEvent.transport": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EventType(); ok {
		if err := tlsfingerprintcapturesessionevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "TLSFingerprintCaptureSessionEvent.event_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StreamID(); ok {
		if err := tlsfingerprintcapturesessionevent.StreamIDValidator(v); err != nil {
			return &ValidationError{Name: "stream_id", err: fmt.Errorf(`ent: validator failed for field "TLSFingerprintCaptureSessionEvent.stream_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HTTPMethod(); ok {
		if err := tlsfingerprintcapturesessionevent.HTTPMethodValidator(v); err != nil {
			return &ValidationError{Name: "http_method", err: fmt.Errorf(`ent: validator failed for field "TLSFingerprintCaptureSessionEvent.http_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WebsocketProtocol(); ok {
		if err := tlsfingerprintcapturesessionevent.WebsocketProtocolValidator(v); err != nil {
			return &ValidationError{Name: "websocket_protocol", err: fmt.Errorf(`ent: validator failed for field "TLSFingerprintCaptureSessionEvent.websocket_protocol": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientType(); ok {
		if err := tlsfingerprintcapturesessionevent.ClientTypeValidator(v); err != nil {
			return &ValidationError{Name: "client_type", err: fmt.Errorf(`ent: validator failed for field "TLSFingerprintCaptureSessionEvent.client_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := tlsfingerprintcapturesessionevent.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "TLSFingerprintCaptureSessionEvent.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestKind(); ok {
		if err := tlsfingerprintcapturesessionevent.RequestKindValidator(v); err != nil {
			return &ValidationError{Name: "request_kind", err: fmt.Errorf(`ent: validator failed for field "TLSFingerprintCaptureSessionEvent.request_kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResponseMode(); ok {
		if err := tlsfingerprintcapturesessionevent.ResponseModeValidator(v); err != nil {
			return &ValidationError{Name: "response_mode", err: fmt.Errorf(`ent: validator failed for field "TLSFingerprintCaptureSessionEvent.response_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Originator(); ok {
		if err := tlsfingerprintcapturesessionevent.OriginatorValidator(v); err != nil {
			return &ValidationError{Name: "originator", err: fmt.Errorf(`ent: validator failed for field "TLSFingerprintCaptureSessionEvent.originator": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EventStatus(); ok {
		if err := tlsfingerprintcapturesessionevent.EventStatusValidator(v); err != nil {
			return &ValidationError{Name: "event_status", err: fmt.Errorf(`ent: validator failed for field "TLSFingerprintCaptureSessionEvent.event_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReplayHash(); ok {
		if err := tlsfingerprintcapturesessionevent.ReplayHashValidator(v); err != nil {
			return &ValidationError{Name: "replay_hash", err: fmt.Errorf(`ent: validator failed for field "TLSFingerprintCaptureSessionEvent.replay_hash": %w`, err)}
		}
	}
	return nil
}

func (_u *TLSFingerprintCaptureSessionEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tlsfingerprintcapturesessionevent.Table, tlsfingerprintcapturesessionevent.Columns, sqlgraph.NewFieldSpec(tlsfingerprintcapturesessionevent.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TaskID(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldTaskID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTaskID(); ok {
		_spec.AddField(tlsfingerprintcapturesessionevent.FieldTaskID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SessionRef(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldSessionRef, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSessionRef(); ok {
		_spec.AddField(tlsfingerprintcapturesessionevent.FieldSessionRef, field.TypeInt64, value)
	}
	if _u.mutation.SessionRefCleared() {
		_spec.ClearField(tlsfingerprintcapturesessionevent.FieldSessionRef, field.TypeInt64)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventID(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldEventID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Transport(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldTransport, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestSequence(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldRequestSequence, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRequestSequence(); ok {
		_spec.AddField(tlsfingerprintcapturesessionevent.FieldRequestSequence, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StreamID(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldStreamID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestPath(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldRequestPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.HTTPMethod(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldHTTPMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsWebsocket(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldIsWebsocket, field.TypeBool, value)
	}
	if value, ok := _u.mutation.WebsocketProtocol(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldWebsocketProtocol, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientType(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldClientType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestKind(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldRequestKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Streaming(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldStreaming, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ResponseMode(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldResponseMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldUserAgent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Originator(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldOriginator, field.TypeString, value)
	}
	if value, ok := _u.mutation.StainlessMetadata(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldStainlessMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.HeadersSnapshot(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldHeadersSnapshot, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.BodySummary(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldBodySummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventStatus(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldEventStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventError(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldEventError, field.TypeString, value)
	}
	if value, ok := _u.mutation.Replayable(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldReplayable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SampleID(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldSampleID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSampleID(); ok {
		_spec.AddField(tlsfingerprintcapturesessionevent.FieldSampleID, field.TypeInt64, value)
	}
	if _u.mutation.SampleIDCleared() {
		_spec.ClearField(tlsfingerprintcapturesessionevent.FieldSampleID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ReplayHash(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldReplayHash, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tlsfingerprintcapturesessionevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TLSFingerprintCaptureSessionEventUpdateOne is the builder for updating a single TLSFingerprintCaptureSessionEvent entity.
type TLSFingerprintCaptureSessionEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TLSFingerprintCaptureSessionEventMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetUpdatedAt(v time.Time) *TLSFingerprintCaptureSessionEventUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetTaskID(v int64) *TLSFingerprintCaptureSessionEventUpdateOne {
	_u.mutation.ResetTaskID()
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetNillableTaskID(v *int64) *TLSFingerprintCaptureSessionEventUpdateOne {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// AddTaskID adds value to the "task_id" field.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) AddTaskID(v int64) *TLSFingerprintCaptureSessionEventUpdateOne {
	_u.mutation.AddTaskID(v)
	return _u
}

// SetSessionRef sets the "session_ref" field.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetSessionRef(v int64) *TLSFingerprintCaptureSessionEventUpdateOne {
	_u.mutation.ResetSessionRef()
	_u.mutation.SetSessionRef(v)
	return _u
}

// SetNillableSessionRef sets the "session_ref" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetNillableSessionRef(v *int64) *TLSFingerprintCaptureSessionEventUpdateOne {
	if v != nil {
		_u.SetSessionRef(*v)
	}
	return _u
}

// AddSessionRef adds value to the "session_ref" field.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) AddSessionRef(v int64) *TLSFingerprintCaptureSessionEventUpdateOne {
	_u.mutation.AddSessionRef(v)
	return _u
}

// ClearSessionRef clears the value of the "session_ref" field.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) ClearSessionRef() *TLSFingerprintCaptureSessionEventUpdateOne {
	_u.mutation.ClearSessionRef()
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetSessionID(v string) *TLSFingerprintCaptureSessionEventUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetNillableSessionID(v *string) *TLSFingerprintCaptureSessionEventUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetEventID sets the "event_id" field.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetEventID(v string) *TLSFingerprintCaptureSessionEventUpdateOne {
	_u.mutation.SetEventID(v)
	return _u
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetNillableEventID(v *string) *TLSFingerprintCaptureSessionEventUpdateOne {
	if v != nil {
		_u.SetEventID(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetPlatform(v string) *TLSFingerprintCaptureSessionEventUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetNillablePlatform(v *string) *TLSFingerprintCaptureSessionEventUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetTransport sets the "transport" field.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetTransport(v string) *TLSFingerprintCaptureSessionEventUpdateOne {
	_u.mutation.SetTransport(v)
	return _u
}

// SetNillableTransport sets the "transport" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetNillableTransport(v *string) *TLSFingerprintCaptureSessionEventUpdateOne {
	if v != nil {
		_u.SetTransport(*v)
	}
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetEventType(v string) *TLSFingerprintCaptureSessionEventUpdateOne {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetNillableEventType(v *string) *TLSFingerprintCaptureSessionEventUpdateOne {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetRequestSequence sets the "request_sequence" field.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetRequestSequence(v int) *TLSFingerprintCaptureSessionEventUpdateOne {
	_u.mutation.ResetRequestSequence()
	_u.mutation.SetRequestSequence(v)
	return _u
}

// SetNillableRequestSequence sets the "request_sequence" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetNillableRequestSequence(v *int) *TLSFingerprintCaptureSessionEventUpdateOne {
	if v != nil {
		_u.SetRequestSequence(*v)
	}
	return _u
}

// AddRequestSequence adds value to the "request_sequence" field.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) AddRequestSequence(v int) *TLSFingerprintCaptureSessionEventUpdateOne {
	_u.mutation.AddRequestSequence(v)
	return _u
}

// SetStreamID sets the "stream_id" field.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetStreamID(v string) *TLSFingerprintCaptureSessionEventUpdateOne {
	_u.mutation.SetStreamID(v)
	return _u
}

// SetNillableStreamID sets the "stream_id" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetNillableStreamID(v *string) *TLSFingerprintCaptureSessionEventUpdateOne {
	if v != nil {
		_u.SetStreamID(*v)
	}
	return _u
}

// SetRequestPath sets the "request_path" field.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetRequestPath(v string) *TLSFingerprintCaptureSessionEventUpdateOne {
	_u.mutation.SetRequestPath(v)
	return _u
}

// SetNillableRequestPath sets the "request_path" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetNillableRequestPath(v *string) *TLSFingerprintCaptureSessionEventUpdateOne {
	if v != nil {
		_u.SetRequestPath(*v)
	}
	return _u
}

// SetHTTPMethod sets the "http_method" field.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetHTTPMethod(v string) *TLSFingerprintCaptureSessionEventUpdateOne {
	_u.mutation.SetHTTPMethod(v)
	return _u
}

// SetNillableHTTPMethod sets the "http_method" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetNillableHTTPMethod(v *string) *TLSFingerprintCaptureSessionEventUpdateOne {
	if v != nil {
		_u.SetHTTPMethod(*v)
	}
	return _u
}

// SetIsWebsocket sets the "is_websocket" field.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetIsWebsocket(v bool) *TLSFingerprintCaptureSessionEventUpdateOne {
	_u.mutation.SetIsWebsocket(v)
	return _u
}

// SetNillableIsWebsocket sets the "is_websocket" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetNillableIsWebsocket(v *bool) *TLSFingerprintCaptureSessionEventUpdateOne {
	if v != nil {
		_u.SetIsWebsocket(*v)
	}
	return _u
}

// SetWebsocketProtocol sets the "websocket_protocol" field.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetWebsocketProtocol(v string) *TLSFingerprintCaptureSessionEventUpdateOne {
	_u.mutation.SetWebsocketProtocol(v)
	return _u
}

// SetNillableWebsocketProtocol sets the "websocket_protocol" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetNillableWebsocketProtocol(v *string) *TLSFingerprintCaptureSessionEventUpdateOne {
	if v != nil {
		_u.SetWebsocketProtocol(*v)
	}
	return _u
}

// SetClientType sets the "client_type" field.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetClientType(v string) *TLSFingerprintCaptureSessionEventUpdateOne {
	_u.mutation.SetClientType(v)
	return _u
}

// SetNillableClientType sets the "client_type" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetNillableClientType(v *string) *TLSFingerprintCaptureSessionEventUpdateOne {
	if v != nil {
		_u.SetClientType(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetModel(v string) *TLSFingerprintCaptureSessionEventUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetNillableModel(v *string) *TLSFingerprintCaptureSessionEventUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetRequestKind sets the "request_kind" field.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetRequestKind(v string) *TLSFingerprintCaptureSessionEventUpdateOne {
	_u.mutation.SetRequestKind(v)
	return _u
}

// SetNillableRequestKind sets the "request_kind" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetNillableRequestKind(v *string) *TLSFingerprintCaptureSessionEventUpdateOne {
	if v != nil {
		_u.SetRequestKind(*v)
	}
	return _u
}

// SetStreaming sets the "streaming" field.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetStreaming(v bool) *TLSFingerprintCaptureSessionEventUpdateOne {
	_u.mutation.SetStreaming(v)
	return _u
}

// SetNillableStreaming sets the "streaming" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetNillableStreaming(v *bool) *TLSFingerprintCaptureSessionEventUpdateOne {
	if v != nil {
		_u.SetStreaming(*v)
	}
	return _u
}

// SetResponseMode sets the "response_mode" field.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetResponseMode(v string) *TLSFingerprintCaptureSessionEventUpdateOne {
	_u.mutation.SetResponseMode(v)
	return _u
}

// SetNillableResponseMode sets the "response_mode" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetNillableResponseMode(v *string) *TLSFingerprintCaptureSessionEventUpdateOne {
	if v != nil {
		_u.SetResponseMode(*v)
	}
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetUserAgent(v string) *TLSFingerprintCaptureSessionEventUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetNillableUserAgent(v *string) *TLSFingerprintCaptureSessionEventUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// SetOriginator sets the "originator" field.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetOriginator(v string) *TLSFingerprintCaptureSessionEventUpdateOne {
	_u.mutation.SetOriginator(v)
	return _u
}

// SetNillableOriginator sets the "originator" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetNillableOriginator(v *string) *TLSFingerprintCaptureSessionEventUpdateOne {
	if v != nil {
		_u.SetOriginator(*v)
	}
	return _u
}

// SetStainlessMetadata sets the "stainless_metadata" field.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetStainlessMetadata(v map[string]interface{}) *TLSFingerprintCaptureSessionEventUpdateOne {
	_u.mutation.SetStainlessMetadata(v)
	return _u
}

// SetHeadersSnapshot sets the "headers_snapshot" field.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetHeadersSnapshot(v map[string]interface{}) *TLSFingerprintCaptureSessionEventUpdateOne {
	_u.mutation.SetHeadersSnapshot(v)
	return _u
}

// SetBodySummary sets the "body_summary" field.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetBodySummary(v string) *TLSFingerprintCaptureSessionEventUpdateOne {
	_u.mutation.SetBodySummary(v)
	return _u
}

// SetNillableBodySummary sets the "body_summary" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetNillableBodySummary(v *string) *TLSFingerprintCaptureSessionEventUpdateOne {
	if v != nil {
		_u.SetBodySummary(*v)
	}
	return _u
}

// SetEventStatus sets the "event_status" field.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetEventStatus(v string) *TLSFingerprintCaptureSessionEventUpdateOne {
	_u.mutation.SetEventStatus(v)
	return _u
}

// SetNillableEventStatus sets the "event_status" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetNillableEventStatus(v *string) *TLSFingerprintCaptureSessionEventUpdateOne {
	if v != nil {
		_u.SetEventStatus(*v)
	}
	return _u
}

// SetEventError sets the "event_error" field.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetEventError(v string) *TLSFingerprintCaptureSessionEventUpdateOne {
	_u.mutation.SetEventError(v)
	return _u
}

// SetNillableEventError sets the "event_error" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetNillableEventError(v *string) *TLSFingerprintCaptureSessionEventUpdateOne {
	if v != nil {
		_u.SetEventError(*v)
	}
	return _u
}

// SetReplayable sets the "replayable" field.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetReplayable(v bool) *TLSFingerprintCaptureSessionEventUpdateOne {
	_u.mutation.SetReplayable(v)
	return _u
}

// SetNillableReplayable sets the "replayable" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetNillableReplayable(v *bool) *TLSFingerprintCaptureSessionEventUpdateOne {
	if v != nil {
		_u.SetReplayable(*v)
	}
	return _u
}

// SetSampleID sets the "sample_id" field.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetSampleID(v int64) *TLSFingerprintCaptureSessionEventUpdateOne {
	_u.mutation.ResetSampleID()
	_u.mutation.SetSampleID(v)
	return _u
}

// SetNillableSampleID sets the "sample_id" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetNillableSampleID(v *int64) *TLSFingerprintCaptureSessionEventUpdateOne {
	if v != nil {
		_u.SetSampleID(*v)
	}
	return _u
}

// AddSampleID adds value to the "sample_id" field.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) AddSampleID(v int64) *TLSFingerprintCaptureSessionEventUpdateOne {
	_u.mutation.AddSampleID(v)
	return _u
}

// ClearSampleID clears the value of the "sample_id" field.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) ClearSampleID() *TLSFingerprintCaptureSessionEventUpdateOne {
	_u.mutation.ClearSampleID()
	return _u
}

// SetReplayHash sets the "replay_hash" field.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetReplayHash(v string) *TLSFingerprintCaptureSessionEventUpdateOne {
	_u.mutation.SetReplayHash(v)
	return _u
}

// SetNillableReplayHash sets the "replay_hash" field if the given value is not nil.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SetNillableReplayHash(v *string) *TLSFingerprintCaptureSessionEventUpdateOne {
	if v != nil {
		_u.SetReplayHash(*v)
	}
	return _u
}

// Mutation returns the TLSFingerprintCaptureSessionEventMutation object of the builder.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) Mutation() *TLSFingerprintCaptureSessionEventMutation {
	return _u.mutation
}

// Where appends a list predicates to the TLSFingerprintCaptureSessionEventUpdate builder.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) Where(ps ...predicate.TLSFingerprintCaptureSessionEvent) *TLSFingerprintCaptureSessionEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) Select(field string, fields ...string) *TLSFingerprintCaptureSessionEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TLSFingerprintCaptureSessionEvent entity.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) Save(ctx context.Context) (*TLSFingerprintCaptureSessionEvent, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) SaveX(ctx context.Context) *TLSFingerprintCaptureSessionEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tlsfingerprintcapturesessionevent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TLSFingerprintCaptureSessionEventUpdateOne) check() error {
	if v, ok := _u.mutation.SessionID(); ok {
		if err := tlsfingerprintcapturesessionevent.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "TLSFingerprintCaptureSessionEvent.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EventID(); ok {
		if err := tlsfingerprintcapturesessionevent.EventIDValidator(v); err != nil {
			return &ValidationError{Name: "event_id", err: fmt.Errorf(`ent: validator failed for field "TLSFingerprintCaptureSessionEvent.event_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := tlsfingerprintcapturesessionevent.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "TLSFingerprintCaptureSessionEvent.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Transport(); ok {
		if err := tlsfingerprintcapturesessionevent.TransportValidator(v); err != nil {
			return &ValidationError{Name: "transport", err: fmt.Errorf(`ent: validator failed for field "TLSFingerprintCaptureSessionEvent.transport": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EventType(); ok {
		if err := tlsfingerprintcapturesessionevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "TLSFingerprintCaptureSessionEvent.event_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StreamID(); ok {
		if err := tlsfingerprintcapturesessionevent.StreamIDValidator(v); err != nil {
			return &ValidationError{Name: "stream_id", err: fmt.Errorf(`ent: validator failed for field "TLSFingerprintCaptureSessionEvent.stream_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HTTPMethod(); ok {
		if err := tlsfingerprintcapturesessionevent.HTTPMethodValidator(v); err != nil {
			return &ValidationError{Name: "http_method", err: fmt.Errorf(`ent: validator failed for field "TLSFingerprintCaptureSessionEvent.http_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WebsocketProtocol(); ok {
		if err := tlsfingerprintcapturesessionevent.WebsocketProtocolValidator(v); err != nil {
			return &ValidationError{Name: "websocket_protocol", err: fmt.Errorf(`ent: validator failed for field "TLSFingerprintCaptureSessionEvent.websocket_protocol": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientType(); ok {
		if err := tlsfingerprintcapturesessionevent.ClientTypeValidator(v); err != nil {
			return &ValidationError{Name: "client_type", err: fmt.Errorf(`ent: validator failed for field "TLSFingerprintCaptureSessionEvent.client_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := tlsfingerprintcapturesessionevent.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "TLSFingerprintCaptureSessionEvent.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestKind(); ok {
		if err := tlsfingerprintcapturesessionevent.RequestKindValidator(v); err != nil {
			return &ValidationError{Name: "request_kind", err: fmt.Errorf(`ent: validator failed for field "TLSFingerprintCaptureSessionEvent.request_kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResponseMode(); ok {
		if err := tlsfingerprintcapturesessionevent.ResponseModeValidator(v); err != nil {
			return &ValidationError{Name: "response_mode", err: fmt.Errorf(`ent: validator failed for field "TLSFingerprintCaptureSessionEvent.response_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Originator(); ok {
		if err := tlsfingerprintcapturesessionevent.OriginatorValidator(v); err != nil {
			return &ValidationError{Name: "originator", err: fmt.Errorf(`ent: validator failed for field "TLSFingerprintCaptureSessionEvent.originator": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EventStatus(); ok {
		if err := tlsfingerprintcapturesessionevent.EventStatusValidator(v); err != nil {
			return &ValidationError{Name: "event_status", err: fmt.Errorf(`ent: validator failed for field "TLSFingerprintCaptureSessionEvent.event_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReplayHash(); ok {
		if err := tlsfingerprintcapturesessionevent.ReplayHashValidator(v); err != nil {
			return &ValidationError{Name: "replay_hash", err: fmt.Errorf(`ent: validator failed for field "TLSFingerprintCaptureSessionEvent.replay_hash": %w`, err)}
		}
	}
	return nil
}

func (_u *TLSFingerprintCaptureSessionEventUpdateOne) sqlSave(ctx context.Context) (_node *TLSFingerprintCaptureSessionEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tlsfingerprintcapturesessionevent.Table, tlsfingerprintcapturesessionevent.Columns, sqlgraph.NewFieldSpec(tlsfingerprintcapturesessionevent.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TLSFingerprintCaptureSessionEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tlsfingerprintcapturesessionevent.FieldID)
		for _, f := range fields {
			if !tlsfingerprintcapturesessionevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tlsfingerprintcapturesessionevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TaskID(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldTaskID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTaskID(); ok {
		_spec.AddField(tlsfingerprintcapturesessionevent.FieldTaskID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SessionRef(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldSessionRef, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSessionRef(); ok {
		_spec.AddField(tlsfingerprintcapturesessionevent.FieldSessionRef, field.TypeInt64, value)
	}
	if _u.mutation.SessionRefCleared() {
		_spec.ClearField(tlsfingerprintcapturesessionevent.FieldSessionRef, field.TypeInt64)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventID(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldEventID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Transport(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldTransport, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestSequence(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldRequestSequence, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRequestSequence(); ok {
		_spec.AddField(tlsfingerprintcapturesessionevent.FieldRequestSequence, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StreamID(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldStreamID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestPath(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldRequestPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.HTTPMethod(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldHTTPMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsWebsocket(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldIsWebsocket, field.TypeBool, value)
	}
	if value, ok := _u.mutation.WebsocketProtocol(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldWebsocketProtocol, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientType(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldClientType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestKind(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldRequestKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Streaming(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldStreaming, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ResponseMode(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldResponseMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldUserAgent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Originator(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldOriginator, field.TypeString, value)
	}
	if value, ok := _u.mutation.StainlessMetadata(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldStainlessMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.HeadersSnapshot(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldHeadersSnapshot, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.BodySummary(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldBodySummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventStatus(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldEventStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventError(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldEventError, field.TypeString, value)
	}
	if value, ok := _u.mutation.Replayable(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldReplayable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SampleID(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldSampleID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSampleID(); ok {
		_spec.AddField(tlsfingerprintcapturesessionevent.FieldSampleID, field.TypeInt64, value)
	}
	if _u.mutation.SampleIDCleared() {
		_spec.ClearField(tlsfingerprintcapturesessionevent.FieldSampleID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ReplayHash(); ok {
		_spec.SetField(tlsfingerprintcapturesessionevent.FieldReplayHash, field.TypeString, value)
	}
	_node = &TLSFingerprintCaptureSessionEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tlsfingerprintcapturesessionevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
