// Code generated by ent, DO NOT EDIT.

package tlsfingerprintcapturesample

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the tlsfingerprintcapturesample type in the database.
	Label = "tls_fingerprint_capture_sample"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldTaskID holds the string denoting the task_id field in the database.
	FieldTaskID = "task_id"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldUserAgent holds the string denoting the user_agent field in the database.
	FieldUserAgent = "user_agent"
	// FieldFingerprintHash holds the string denoting the fingerprint_hash field in the database.
	FieldFingerprintHash = "fingerprint_hash"
	// FieldProfile holds the string denoting the profile field in the database.
	FieldProfile = "profile"
	// FieldRawPayload holds the string denoting the raw_payload field in the database.
	FieldRawPayload = "raw_payload"
	// Table holds the table name of the tlsfingerprintcapturesample in the database.
	Table = "tls_fingerprint_capture_samples"
)

// Columns holds all SQL columns for tlsfingerprintcapturesample fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldTaskID,
	FieldPlatform,
	FieldUserAgent,
	FieldFingerprintHash,
	FieldProfile,
	FieldRawPayload,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultPlatform holds the default value on creation for the "platform" field.
	DefaultPlatform string
	// PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	PlatformValidator func(string) error
	// DefaultUserAgent holds the default value on creation for the "user_agent" field.
	DefaultUserAgent string
	// FingerprintHashValidator is a validator for the "fingerprint_hash" field. It is called by the builders before save.
	FingerprintHashValidator func(string) error
	// DefaultRawPayload holds the default value on creation for the "raw_payload" field.
	DefaultRawPayload string
)

// OrderOption defines the ordering options for the TLSFingerprintCaptureSample queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTaskID orders the results by the task_id field.
func ByTaskID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaskID, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByUserAgent orders the results by the user_agent field.
func ByUserAgent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserAgent, opts...).ToFunc()
}

// ByFingerprintHash orders the results by the fingerprint_hash field.
func ByFingerprintHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFingerprintHash, opts...).ToFunc()
}

// ByRawPayload orders the results by the raw_payload field.
func ByRawPayload(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRawPayload, opts...).ToFunc()
}
