// Code generated by ent, DO NOT EDIT.

package aiskillsettlement

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the aiskillsettlement type in the database.
	Label = "ai_skill_settlement"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldSkillID holds the string denoting the skill_id field in the database.
	FieldSkillID = "skill_id"
	// FieldVersionID holds the string denoting the version_id field in the database.
	FieldVersionID = "version_id"
	// FieldRunID holds the string denoting the run_id field in the database.
	FieldRunID = "run_id"
	// FieldOwnerUserID holds the string denoting the owner_user_id field in the database.
	FieldOwnerUserID = "owner_user_id"
	// FieldBuyerUserID holds the string denoting the buyer_user_id field in the database.
	FieldBuyerUserID = "buyer_user_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldBillingMode holds the string denoting the billing_mode field in the database.
	FieldBillingMode = "billing_mode"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldQuotaAmount holds the string denoting the quota_amount field in the database.
	FieldQuotaAmount = "quota_amount"
	// FieldQuotaAppliedAt holds the string denoting the quota_applied_at field in the database.
	FieldQuotaAppliedAt = "quota_applied_at"
	// FieldBalanceTransferredAt holds the string denoting the balance_transferred_at field in the database.
	FieldBalanceTransferredAt = "balance_transferred_at"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldUsageLogID holds the string denoting the usage_log_id field in the database.
	FieldUsageLogID = "usage_log_id"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// EdgeSkill holds the string denoting the skill edge name in mutations.
	EdgeSkill = "skill"
	// EdgeVersion holds the string denoting the version edge name in mutations.
	EdgeVersion = "version"
	// EdgeRun holds the string denoting the run edge name in mutations.
	EdgeRun = "run"
	// Table holds the table name of the aiskillsettlement in the database.
	Table = "ai_skill_settlements"
	// SkillTable is the table that holds the skill relation/edge.
	SkillTable = "ai_skill_settlements"
	// SkillInverseTable is the table name for the AISkill entity.
	// It exists in this package in order to avoid circular dependency with the "aiskill" package.
	SkillInverseTable = "ai_skills"
	// SkillColumn is the table column denoting the skill relation/edge.
	SkillColumn = "skill_id"
	// VersionTable is the table that holds the version relation/edge.
	VersionTable = "ai_skill_settlements"
	// VersionInverseTable is the table name for the AISkillVersion entity.
	// It exists in this package in order to avoid circular dependency with the "aiskillversion" package.
	VersionInverseTable = "ai_skill_versions"
	// VersionColumn is the table column denoting the version relation/edge.
	VersionColumn = "version_id"
	// RunTable is the table that holds the run relation/edge.
	RunTable = "ai_skill_settlements"
	// RunInverseTable is the table name for the AISkillRun entity.
	// It exists in this package in order to avoid circular dependency with the "aiskillrun" package.
	RunInverseTable = "ai_skill_runs"
	// RunColumn is the table column denoting the run relation/edge.
	RunColumn = "run_id"
)

// Columns holds all SQL columns for aiskillsettlement fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldSkillID,
	FieldVersionID,
	FieldRunID,
	FieldOwnerUserID,
	FieldBuyerUserID,
	FieldStatus,
	FieldBillingMode,
	FieldAmount,
	FieldQuotaAmount,
	FieldQuotaAppliedAt,
	FieldBalanceTransferredAt,
	FieldMetadata,
	FieldRequestID,
	FieldUsageLogID,
	FieldAPIKeyID,
	FieldGroupID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultBillingMode holds the default value on creation for the "billing_mode" field.
	DefaultBillingMode string
	// BillingModeValidator is a validator for the "billing_mode" field. It is called by the builders before save.
	BillingModeValidator func(string) error
	// DefaultAmount holds the default value on creation for the "amount" field.
	DefaultAmount float64
	// DefaultQuotaAmount holds the default value on creation for the "quota_amount" field.
	DefaultQuotaAmount float64
	// DefaultMetadata holds the default value on creation for the "metadata" field.
	DefaultMetadata func() map[string]interface{}
	// RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	RequestIDValidator func(string) error
)

// OrderOption defines the ordering options for the AISkillSettlement queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// BySkillID orders the results by the skill_id field.
func BySkillID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSkillID, opts...).ToFunc()
}

// ByVersionID orders the results by the version_id field.
func ByVersionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersionID, opts...).ToFunc()
}

// ByRunID orders the results by the run_id field.
func ByRunID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRunID, opts...).ToFunc()
}

// ByOwnerUserID orders the results by the owner_user_id field.
func ByOwnerUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerUserID, opts...).ToFunc()
}

// ByBuyerUserID orders the results by the buyer_user_id field.
func ByBuyerUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBuyerUserID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByBillingMode orders the results by the billing_mode field.
func ByBillingMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillingMode, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByQuotaAmount orders the results by the quota_amount field.
func ByQuotaAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuotaAmount, opts...).ToFunc()
}

// ByQuotaAppliedAt orders the results by the quota_applied_at field.
func ByQuotaAppliedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuotaAppliedAt, opts...).ToFunc()
}

// ByBalanceTransferredAt orders the results by the balance_transferred_at field.
func ByBalanceTransferredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceTransferredAt, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByUsageLogID orders the results by the usage_log_id field.
func ByUsageLogID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsageLogID, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// BySkillField orders the results by skill field.
func BySkillField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSkillStep(), sql.OrderByField(field, opts...))
	}
}

// ByVersionField orders the results by version field.
func ByVersionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newVersionStep(), sql.OrderByField(field, opts...))
	}
}

// ByRunField orders the results by run field.
func ByRunField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRunStep(), sql.OrderByField(field, opts...))
	}
}
func newSkillStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SkillInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SkillTable, SkillColumn),
	)
}
func newVersionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(VersionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, VersionTable, VersionColumn),
	)
}
func newRunStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RunInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RunTable, RunColumn),
	)
}
