// Code generated by ent, DO NOT EDIT.

package aiskillsettlement

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldEQ(FieldUpdatedAt, v))
}

// SkillID applies equality check predicate on the "skill_id" field. It's identical to SkillIDEQ.
func SkillID(v int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldEQ(FieldSkillID, v))
}

// VersionID applies equality check predicate on the "version_id" field. It's identical to VersionIDEQ.
func VersionID(v int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldEQ(FieldVersionID, v))
}

// RunID applies equality check predicate on the "run_id" field. It's identical to RunIDEQ.
func RunID(v int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldEQ(FieldRunID, v))
}

// OwnerUserID applies equality check predicate on the "owner_user_id" field. It's identical to OwnerUserIDEQ.
func OwnerUserID(v int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldEQ(FieldOwnerUserID, v))
}

// BuyerUserID applies equality check predicate on the "buyer_user_id" field. It's identical to BuyerUserIDEQ.
func BuyerUserID(v int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldEQ(FieldBuyerUserID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldEQ(FieldStatus, v))
}

// BillingMode applies equality check predicate on the "billing_mode" field. It's identical to BillingModeEQ.
func BillingMode(v string) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldEQ(FieldBillingMode, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldEQ(FieldAmount, v))
}

// QuotaAmount applies equality check predicate on the "quota_amount" field. It's identical to QuotaAmountEQ.
func QuotaAmount(v float64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldEQ(FieldQuotaAmount, v))
}

// QuotaAppliedAt applies equality check predicate on the "quota_applied_at" field. It's identical to QuotaAppliedAtEQ.
func QuotaAppliedAt(v time.Time) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldEQ(FieldQuotaAppliedAt, v))
}

// BalanceTransferredAt applies equality check predicate on the "balance_transferred_at" field. It's identical to BalanceTransferredAtEQ.
func BalanceTransferredAt(v time.Time) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldEQ(FieldBalanceTransferredAt, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldEQ(FieldRequestID, v))
}

// UsageLogID applies equality check predicate on the "usage_log_id" field. It's identical to UsageLogIDEQ.
func UsageLogID(v int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldEQ(FieldUsageLogID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldEQ(FieldAPIKeyID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldEQ(FieldGroupID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldLTE(FieldUpdatedAt, v))
}

// SkillIDEQ applies the EQ predicate on the "skill_id" field.
func SkillIDEQ(v int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldEQ(FieldSkillID, v))
}

// SkillIDNEQ applies the NEQ predicate on the "skill_id" field.
func SkillIDNEQ(v int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldNEQ(FieldSkillID, v))
}

// SkillIDIn applies the In predicate on the "skill_id" field.
func SkillIDIn(vs ...int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldIn(FieldSkillID, vs...))
}

// SkillIDNotIn applies the NotIn predicate on the "skill_id" field.
func SkillIDNotIn(vs ...int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldNotIn(FieldSkillID, vs...))
}

// VersionIDEQ applies the EQ predicate on the "version_id" field.
func VersionIDEQ(v int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldEQ(FieldVersionID, v))
}

// VersionIDNEQ applies the NEQ predicate on the "version_id" field.
func VersionIDNEQ(v int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldNEQ(FieldVersionID, v))
}

// VersionIDIn applies the In predicate on the "version_id" field.
func VersionIDIn(vs ...int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldIn(FieldVersionID, vs...))
}

// VersionIDNotIn applies the NotIn predicate on the "version_id" field.
func VersionIDNotIn(vs ...int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldNotIn(FieldVersionID, vs...))
}

// RunIDEQ applies the EQ predicate on the "run_id" field.
func RunIDEQ(v int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldEQ(FieldRunID, v))
}

// RunIDNEQ applies the NEQ predicate on the "run_id" field.
func RunIDNEQ(v int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldNEQ(FieldRunID, v))
}

// RunIDIn applies the In predicate on the "run_id" field.
func RunIDIn(vs ...int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldIn(FieldRunID, vs...))
}

// RunIDNotIn applies the NotIn predicate on the "run_id" field.
func RunIDNotIn(vs ...int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldNotIn(FieldRunID, vs...))
}

// OwnerUserIDEQ applies the EQ predicate on the "owner_user_id" field.
func OwnerUserIDEQ(v int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldEQ(FieldOwnerUserID, v))
}

// OwnerUserIDNEQ applies the NEQ predicate on the "owner_user_id" field.
func OwnerUserIDNEQ(v int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldNEQ(FieldOwnerUserID, v))
}

// OwnerUserIDIn applies the In predicate on the "owner_user_id" field.
func OwnerUserIDIn(vs ...int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldIn(FieldOwnerUserID, vs...))
}

// OwnerUserIDNotIn applies the NotIn predicate on the "owner_user_id" field.
func OwnerUserIDNotIn(vs ...int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldNotIn(FieldOwnerUserID, vs...))
}

// BuyerUserIDEQ applies the EQ predicate on the "buyer_user_id" field.
func BuyerUserIDEQ(v int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldEQ(FieldBuyerUserID, v))
}

// BuyerUserIDNEQ applies the NEQ predicate on the "buyer_user_id" field.
func BuyerUserIDNEQ(v int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldNEQ(FieldBuyerUserID, v))
}

// BuyerUserIDIn applies the In predicate on the "buyer_user_id" field.
func BuyerUserIDIn(vs ...int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldIn(FieldBuyerUserID, vs...))
}

// BuyerUserIDNotIn applies the NotIn predicate on the "buyer_user_id" field.
func BuyerUserIDNotIn(vs ...int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldNotIn(FieldBuyerUserID, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldContainsFold(FieldStatus, v))
}

// BillingModeEQ applies the EQ predicate on the "billing_mode" field.
func BillingModeEQ(v string) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldEQ(FieldBillingMode, v))
}

// BillingModeNEQ applies the NEQ predicate on the "billing_mode" field.
func BillingModeNEQ(v string) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldNEQ(FieldBillingMode, v))
}

// BillingModeIn applies the In predicate on the "billing_mode" field.
func BillingModeIn(vs ...string) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldIn(FieldBillingMode, vs...))
}

// BillingModeNotIn applies the NotIn predicate on the "billing_mode" field.
func BillingModeNotIn(vs ...string) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldNotIn(FieldBillingMode, vs...))
}

// BillingModeGT applies the GT predicate on the "billing_mode" field.
func BillingModeGT(v string) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldGT(FieldBillingMode, v))
}

// BillingModeGTE applies the GTE predicate on the "billing_mode" field.
func BillingModeGTE(v string) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldGTE(FieldBillingMode, v))
}

// BillingModeLT applies the LT predicate on the "billing_mode" field.
func BillingModeLT(v string) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldLT(FieldBillingMode, v))
}

// BillingModeLTE applies the LTE predicate on the "billing_mode" field.
func BillingModeLTE(v string) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldLTE(FieldBillingMode, v))
}

// BillingModeContains applies the Contains predicate on the "billing_mode" field.
func BillingModeContains(v string) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldContains(FieldBillingMode, v))
}

// BillingModeHasPrefix applies the HasPrefix predicate on the "billing_mode" field.
func BillingModeHasPrefix(v string) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldHasPrefix(FieldBillingMode, v))
}

// BillingModeHasSuffix applies the HasSuffix predicate on the "billing_mode" field.
func BillingModeHasSuffix(v string) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldHasSuffix(FieldBillingMode, v))
}

// BillingModeEqualFold applies the EqualFold predicate on the "billing_mode" field.
func BillingModeEqualFold(v string) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldEqualFold(FieldBillingMode, v))
}

// BillingModeContainsFold applies the ContainsFold predicate on the "billing_mode" field.
func BillingModeContainsFold(v string) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldContainsFold(FieldBillingMode, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldLTE(FieldAmount, v))
}

// QuotaAmountEQ applies the EQ predicate on the "quota_amount" field.
func QuotaAmountEQ(v float64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldEQ(FieldQuotaAmount, v))
}

// QuotaAmountNEQ applies the NEQ predicate on the "quota_amount" field.
func QuotaAmountNEQ(v float64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldNEQ(FieldQuotaAmount, v))
}

// QuotaAmountIn applies the In predicate on the "quota_amount" field.
func QuotaAmountIn(vs ...float64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldIn(FieldQuotaAmount, vs...))
}

// QuotaAmountNotIn applies the NotIn predicate on the "quota_amount" field.
func QuotaAmountNotIn(vs ...float64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldNotIn(FieldQuotaAmount, vs...))
}

// QuotaAmountGT applies the GT predicate on the "quota_amount" field.
func QuotaAmountGT(v float64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldGT(FieldQuotaAmount, v))
}

// QuotaAmountGTE applies the GTE predicate on the "quota_amount" field.
func QuotaAmountGTE(v float64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldGTE(FieldQuotaAmount, v))
}

// QuotaAmountLT applies the LT predicate on the "quota_amount" field.
func QuotaAmountLT(v float64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldLT(FieldQuotaAmount, v))
}

// QuotaAmountLTE applies the LTE predicate on the "quota_amount" field.
func QuotaAmountLTE(v float64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldLTE(FieldQuotaAmount, v))
}

// QuotaAppliedAtEQ applies the EQ predicate on the "quota_applied_at" field.
func QuotaAppliedAtEQ(v time.Time) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldEQ(FieldQuotaAppliedAt, v))
}

// QuotaAppliedAtNEQ applies the NEQ predicate on the "quota_applied_at" field.
func QuotaAppliedAtNEQ(v time.Time) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldNEQ(FieldQuotaAppliedAt, v))
}

// QuotaAppliedAtIn applies the In predicate on the "quota_applied_at" field.
func QuotaAppliedAtIn(vs ...time.Time) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldIn(FieldQuotaAppliedAt, vs...))
}

// QuotaAppliedAtNotIn applies the NotIn predicate on the "quota_applied_at" field.
func QuotaAppliedAtNotIn(vs ...time.Time) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldNotIn(FieldQuotaAppliedAt, vs...))
}

// QuotaAppliedAtGT applies the GT predicate on the "quota_applied_at" field.
func QuotaAppliedAtGT(v time.Time) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldGT(FieldQuotaAppliedAt, v))
}

// QuotaAppliedAtGTE applies the GTE predicate on the "quota_applied_at" field.
func QuotaAppliedAtGTE(v time.Time) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldGTE(FieldQuotaAppliedAt, v))
}

// QuotaAppliedAtLT applies the LT predicate on the "quota_applied_at" field.
func QuotaAppliedAtLT(v time.Time) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldLT(FieldQuotaAppliedAt, v))
}

// QuotaAppliedAtLTE applies the LTE predicate on the "quota_applied_at" field.
func QuotaAppliedAtLTE(v time.Time) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldLTE(FieldQuotaAppliedAt, v))
}

// QuotaAppliedAtIsNil applies the IsNil predicate on the "quota_applied_at" field.
func QuotaAppliedAtIsNil() predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldIsNull(FieldQuotaAppliedAt))
}

// QuotaAppliedAtNotNil applies the NotNil predicate on the "quota_applied_at" field.
func QuotaAppliedAtNotNil() predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldNotNull(FieldQuotaAppliedAt))
}

// BalanceTransferredAtEQ applies the EQ predicate on the "balance_transferred_at" field.
func BalanceTransferredAtEQ(v time.Time) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldEQ(FieldBalanceTransferredAt, v))
}

// BalanceTransferredAtNEQ applies the NEQ predicate on the "balance_transferred_at" field.
func BalanceTransferredAtNEQ(v time.Time) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldNEQ(FieldBalanceTransferredAt, v))
}

// BalanceTransferredAtIn applies the In predicate on the "balance_transferred_at" field.
func BalanceTransferredAtIn(vs ...time.Time) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldIn(FieldBalanceTransferredAt, vs...))
}

// BalanceTransferredAtNotIn applies the NotIn predicate on the "balance_transferred_at" field.
func BalanceTransferredAtNotIn(vs ...time.Time) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldNotIn(FieldBalanceTransferredAt, vs...))
}

// BalanceTransferredAtGT applies the GT predicate on the "balance_transferred_at" field.
func BalanceTransferredAtGT(v time.Time) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldGT(FieldBalanceTransferredAt, v))
}

// BalanceTransferredAtGTE applies the GTE predicate on the "balance_transferred_at" field.
func BalanceTransferredAtGTE(v time.Time) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldGTE(FieldBalanceTransferredAt, v))
}

// BalanceTransferredAtLT applies the LT predicate on the "balance_transferred_at" field.
func BalanceTransferredAtLT(v time.Time) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldLT(FieldBalanceTransferredAt, v))
}

// BalanceTransferredAtLTE applies the LTE predicate on the "balance_transferred_at" field.
func BalanceTransferredAtLTE(v time.Time) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldLTE(FieldBalanceTransferredAt, v))
}

// BalanceTransferredAtIsNil applies the IsNil predicate on the "balance_transferred_at" field.
func BalanceTransferredAtIsNil() predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldIsNull(FieldBalanceTransferredAt))
}

// BalanceTransferredAtNotNil applies the NotNil predicate on the "balance_transferred_at" field.
func BalanceTransferredAtNotNil() predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldNotNull(FieldBalanceTransferredAt))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDIsNil applies the IsNil predicate on the "request_id" field.
func RequestIDIsNil() predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldIsNull(FieldRequestID))
}

// RequestIDNotNil applies the NotNil predicate on the "request_id" field.
func RequestIDNotNil() predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldNotNull(FieldRequestID))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldContainsFold(FieldRequestID, v))
}

// UsageLogIDEQ applies the EQ predicate on the "usage_log_id" field.
func UsageLogIDEQ(v int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldEQ(FieldUsageLogID, v))
}

// UsageLogIDNEQ applies the NEQ predicate on the "usage_log_id" field.
func UsageLogIDNEQ(v int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldNEQ(FieldUsageLogID, v))
}

// UsageLogIDIn applies the In predicate on the "usage_log_id" field.
func UsageLogIDIn(vs ...int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldIn(FieldUsageLogID, vs...))
}

// UsageLogIDNotIn applies the NotIn predicate on the "usage_log_id" field.
func UsageLogIDNotIn(vs ...int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldNotIn(FieldUsageLogID, vs...))
}

// UsageLogIDGT applies the GT predicate on the "usage_log_id" field.
func UsageLogIDGT(v int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldGT(FieldUsageLogID, v))
}

// UsageLogIDGTE applies the GTE predicate on the "usage_log_id" field.
func UsageLogIDGTE(v int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldGTE(FieldUsageLogID, v))
}

// UsageLogIDLT applies the LT predicate on the "usage_log_id" field.
func UsageLogIDLT(v int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldLT(FieldUsageLogID, v))
}

// UsageLogIDLTE applies the LTE predicate on the "usage_log_id" field.
func UsageLogIDLTE(v int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldLTE(FieldUsageLogID, v))
}

// UsageLogIDIsNil applies the IsNil predicate on the "usage_log_id" field.
func UsageLogIDIsNil() predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldIsNull(FieldUsageLogID))
}

// UsageLogIDNotNil applies the NotNil predicate on the "usage_log_id" field.
func UsageLogIDNotNil() predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldNotNull(FieldUsageLogID))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldLTE(FieldAPIKeyID, v))
}

// APIKeyIDIsNil applies the IsNil predicate on the "api_key_id" field.
func APIKeyIDIsNil() predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldIsNull(FieldAPIKeyID))
}

// APIKeyIDNotNil applies the NotNil predicate on the "api_key_id" field.
func APIKeyIDNotNil() predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldNotNull(FieldAPIKeyID))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldLTE(FieldGroupID, v))
}

// GroupIDIsNil applies the IsNil predicate on the "group_id" field.
func GroupIDIsNil() predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldIsNull(FieldGroupID))
}

// GroupIDNotNil applies the NotNil predicate on the "group_id" field.
func GroupIDNotNil() predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.FieldNotNull(FieldGroupID))
}

// HasSkill applies the HasEdge predicate on the "skill" edge.
func HasSkill() predicate.AISkillSettlement {
	return predicate.AISkillSettlement(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SkillTable, SkillColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSkillWith applies the HasEdge predicate on the "skill" edge with a given conditions (other predicates).
func HasSkillWith(preds ...predicate.AISkill) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(func(s *sql.Selector) {
		step := newSkillStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasVersion applies the HasEdge predicate on the "version" edge.
func HasVersion() predicate.AISkillSettlement {
	return predicate.AISkillSettlement(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, VersionTable, VersionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasVersionWith applies the HasEdge predicate on the "version" edge with a given conditions (other predicates).
func HasVersionWith(preds ...predicate.AISkillVersion) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(func(s *sql.Selector) {
		step := newVersionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRun applies the HasEdge predicate on the "run" edge.
func HasRun() predicate.AISkillSettlement {
	return predicate.AISkillSettlement(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RunTable, RunColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRunWith applies the HasEdge predicate on the "run" edge with a given conditions (other predicates).
func HasRunWith(preds ...predicate.AISkillRun) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(func(s *sql.Selector) {
		step := newRunStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOwnerUser applies the HasEdge predicate on the "owner_user" edge.
func HasOwnerUser() predicate.AISkillSettlement {
	return predicate.AISkillSettlement(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerUserTable, OwnerUserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerUserWith applies the HasEdge predicate on the "owner_user" edge with a given conditions (other predicates).
func HasOwnerUserWith(preds ...predicate.User) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(func(s *sql.Selector) {
		step := newOwnerUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBuyerUser applies the HasEdge predicate on the "buyer_user" edge.
func HasBuyerUser() predicate.AISkillSettlement {
	return predicate.AISkillSettlement(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, BuyerUserTable, BuyerUserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBuyerUserWith applies the HasEdge predicate on the "buyer_user" edge with a given conditions (other predicates).
func HasBuyerUserWith(preds ...predicate.User) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(func(s *sql.Selector) {
		step := newBuyerUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AISkillSettlement) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AISkillSettlement) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AISkillSettlement) predicate.AISkillSettlement {
	return predicate.AISkillSettlement(sql.NotPredicates(p))
}
